/*
 * Generated by the Jasper component of Apache Tomcat
 * Version: Apache Tomcat/10.1.7
 * Generated at: 2023-08-28 17:43:58 UTC
 * Note: The last modified time of this file was set to
 *       the last modified time of the source file after
 *       generation to assist with modification tracking.
 */
package org.apache.jsp.WEB_002dINF.views.frontend.include;

import jakarta.servlet.*;
import jakarta.servlet.http.*;
import jakarta.servlet.jsp.*;

public final class footer_jsp extends org.apache.jasper.runtime.HttpJspBase
    implements org.apache.jasper.runtime.JspSourceDependent,
                 org.apache.jasper.runtime.JspSourceImports,
                 org.apache.jasper.runtime.JspSourceDirectives {

  private static final jakarta.servlet.jsp.JspFactory _jspxFactory =
          jakarta.servlet.jsp.JspFactory.getDefaultFactory();

  private static java.util.Map<java.lang.String,java.lang.Long> _jspx_dependants;

  private static final java.util.Set<java.lang.String> _jspx_imports_packages;

  private static final java.util.Set<java.lang.String> _jspx_imports_classes;

  static {
    _jspx_imports_packages = new java.util.HashSet<>();
    _jspx_imports_packages.add("jakarta.servlet");
    _jspx_imports_packages.add("jakarta.servlet.http");
    _jspx_imports_packages.add("jakarta.servlet.jsp");
    _jspx_imports_classes = null;
  }

  private volatile jakarta.el.ExpressionFactory _el_expressionfactory;
  private volatile org.apache.tomcat.InstanceManager _jsp_instancemanager;

  public java.util.Map<java.lang.String,java.lang.Long> getDependants() {
    return _jspx_dependants;
  }

  public java.util.Set<java.lang.String> getPackageImports() {
    return _jspx_imports_packages;
  }

  public java.util.Set<java.lang.String> getClassImports() {
    return _jspx_imports_classes;
  }

  public boolean getErrorOnELNotFound() {
    return false;
  }

  public jakarta.el.ExpressionFactory _jsp_getExpressionFactory() {
    if (_el_expressionfactory == null) {
      synchronized (this) {
        if (_el_expressionfactory == null) {
          _el_expressionfactory = _jspxFactory.getJspApplicationContext(getServletConfig().getServletContext()).getExpressionFactory();
        }
      }
    }
    return _el_expressionfactory;
  }

  public org.apache.tomcat.InstanceManager _jsp_getInstanceManager() {
    if (_jsp_instancemanager == null) {
      synchronized (this) {
        if (_jsp_instancemanager == null) {
          _jsp_instancemanager = org.apache.jasper.runtime.InstanceManagerFactory.getInstanceManager(getServletConfig());
        }
      }
    }
    return _jsp_instancemanager;
  }

  public void _jspInit() {
  }

  public void _jspDestroy() {
  }

  public void _jspService(final jakarta.servlet.http.HttpServletRequest request, final jakarta.servlet.http.HttpServletResponse response)
      throws java.io.IOException, jakarta.servlet.ServletException {

    if (!jakarta.servlet.DispatcherType.ERROR.equals(request.getDispatcherType())) {
      final java.lang.String _jspx_method = request.getMethod();
      if ("OPTIONS".equals(_jspx_method)) {
        response.setHeader("Allow","GET, HEAD, POST, OPTIONS");
        return;
      }
      if (!"GET".equals(_jspx_method) && !"POST".equals(_jspx_method) && !"HEAD".equals(_jspx_method)) {
        response.setHeader("Allow","GET, HEAD, POST, OPTIONS");
        response.sendError(HttpServletResponse.SC_METHOD_NOT_ALLOWED, "JSPs only permit GET, POST or HEAD. Jasper also permits OPTIONS");
        return;
      }
    }

    final jakarta.servlet.jsp.PageContext pageContext;
    jakarta.servlet.http.HttpSession session = null;
    final jakarta.servlet.ServletContext application;
    final jakarta.servlet.ServletConfig config;
    jakarta.servlet.jsp.JspWriter out = null;
    final java.lang.Object page = this;
    jakarta.servlet.jsp.JspWriter _jspx_out = null;
    jakarta.servlet.jsp.PageContext _jspx_page_context = null;


    try {
      response.setContentType("text/html");
      pageContext = _jspxFactory.getPageContext(this, request, response,
      			null, true, 8192, true);
      _jspx_page_context = pageContext;
      application = pageContext.getServletContext();
      config = pageContext.getServletConfig();
      session = pageContext.getSession();
      out = pageContext.getOut();
      _jspx_out = out;

      out.write("<!--------------------footer--------------->\r\n");
      out.write("<footer class=\"site-footer_v2\">\r\n");
      out.write("    <div class=\"space-top-3 bg-gray-850\">\r\n");
      out.write("        <div class=\"pb-5 space-bottom-lg-3\">\r\n");
      out.write("            <div class=\"container\">\r\n");
      out.write("                <div class=\"row\">\r\n");
      out.write("\r\n");
      out.write("                    <div class=\"col-lg-3 mb-6 mb-lg-0\">\r\n");
      out.write("                        <h4 class=\"font-size-3 font-weight-medium mb-2 mb-xl-5 pb-xl-1 text-white\">Customer Service</h4>\r\n");
      out.write("                        <ul class=\"list-unstyled mb-0\">\r\n");
      out.write("                            <li class=\"h-white pb-2\">\r\n");
      out.write("                                <a class=\"font-size-2 text-gray-450 widgets-hover transition-3d-hover\" href=\"contactUs\">Help\r\n");
      out.write("                                    Center</a>\r\n");
      out.write("                            </li>\r\n");
      out.write("                            <li class=\"h-white py-2\">\r\n");
      out.write("                                <a class=\"font-size-2 text-gray-450 widgets-hover transition-3d-hover\"\r\n");
      out.write("                                   href=\"#\">Returns</a>\r\n");
      out.write("                            </li>\r\n");
      out.write("                            <li class=\"h-white py-2\">\r\n");
      out.write("                                <a class=\"font-size-2 text-gray-450 widgets-hover transition-3d-hover\" href=\"#\">Product\r\n");
      out.write("                                    Recalls</a>\r\n");
      out.write("                            </li>\r\n");
      out.write("                            <li class=\"h-white py-2\">\r\n");
      out.write("                                <a class=\"font-size-2 text-gray-450 widgets-hover transition-3d-hover\" href=\"#\">Accessibility</a>\r\n");
      out.write("                            </li>\r\n");
      out.write("                            <li class=\"h-white py-2\">\r\n");
      out.write("                                <a class=\"font-size-2 text-gray-450 widgets-hover transition-3d-hover\" href=\"#\">Contact\r\n");
      out.write("                                    Us</a>\r\n");
      out.write("                            </li>\r\n");
      out.write("                            <li class=\"h-white pt-2\">\r\n");
      out.write("                                <a class=\"font-size-2 text-gray-450 widgets-hover transition-3d-hover\" href=\"#\">Store\r\n");
      out.write("                                    Pickup</a>\r\n");
      out.write("                            </li>\r\n");
      out.write("                        </ul>\r\n");
      out.write("                    </div>\r\n");
      out.write("                    <div class=\"col-lg-3 mb-6 mb-lg-0\">\r\n");
      out.write("                        <h4 class=\"font-size-3 font-weight-medium mb-2 mb-xl-5 pb-xl-1 text-white\">Policy</h4>\r\n");
      out.write("                        <ul class=\"list-unstyled mb-0\">\r\n");
      out.write("                            <li class=\"h-white pb-2\">\r\n");
      out.write("                                <a class=\"font-size-2 text-gray-450 widgets-hover transition-3d-hover\" href=\"#\">Return\r\n");
      out.write("                                    Policy</a>\r\n");
      out.write("                            </li>\r\n");
      out.write("                            <li class=\"h-white py-2\">\r\n");
      out.write("                                <a class=\"font-size-2 text-gray-450 widgets-hover transition-3d-hover\" href=\"#\">Terms Of\r\n");
      out.write("                                    Use</a>\r\n");
      out.write("                            </li>\r\n");
      out.write("                            <li class=\"h-white py-2\">\r\n");
      out.write("                                <a class=\"font-size-2 text-gray-450 widgets-hover transition-3d-hover\"\r\n");
      out.write("                                   href=\"#\">Security</a>\r\n");
      out.write("                            </li>\r\n");
      out.write("                            <li class=\"h-white pt-2\">\r\n");
      out.write("                                <a class=\"font-size-2 text-gray-450 widgets-hover transition-3d-hover\"\r\n");
      out.write("                                   href=\"#\">Privacy</a>\r\n");
      out.write("                            </li>\r\n");
      out.write("                        </ul>\r\n");
      out.write("                    </div>\r\n");
      out.write("                    <div class=\"col-lg-3 mb-6 mb-lg-0\">\r\n");
      out.write("                        <div class=\"pb-lg-6\">\r\n");
      out.write("                            <h4 class=\"font-size-3 font-weight-medium mb-2 mb-xl-5 pb-xl-1 text-white\">Contact Us</h4>\r\n");
      out.write("                            <address class=\"font-size-2 mb-5\">\r\n");
      out.write("<span class=\"mb-2 font-weight-normal text-gray-450\">\r\n");
      out.write("Mawanella,Kegalle.<br> Sri Lanka\r\n");
      out.write("</span>\r\n");
      out.write("                            </address>\r\n");
      out.write("                            <div class=\"mb-4 h-white\">\r\n");
      out.write("                                <a href=\"mailto:sale@bookworm.com\" class=\"font-size-2 d-block text-gray-450 mb-1\">sales@ebookstore.com</a>\r\n");
      out.write("                                <a href=\"tel:+1246-345-0695\" class=\"font-size-2 d-block text-gray-450\">+94\r\n");
      out.write("                                    76-268-4595</a>\r\n");
      out.write("                            </div>\r\n");
      out.write("                            <ul class=\"list-unstyled mb-0 d-flex\">\r\n");
      out.write("                                <li class=\"h-white btn pl-0\">\r\n");
      out.write("                                    <a class=\"text-gray-450\" href=\"#\">\r\n");
      out.write("                                        <span class=\"fab fa-instagram\"></span>\r\n");
      out.write("                                    </a>\r\n");
      out.write("                                </li>\r\n");
      out.write("                                <li class=\"h-white btn\">\r\n");
      out.write("                                    <a class=\"text-gray-450\" href=\"#\">\r\n");
      out.write("                                        <span class=\"fab fa-facebook-f\"></span>\r\n");
      out.write("                                    </a>\r\n");
      out.write("                                </li>\r\n");
      out.write("                                <li class=\"h-white btn\">\r\n");
      out.write("                                    <a class=\"text-gray-450\" href=\"#\">\r\n");
      out.write("                                        <span class=\"fab fa-youtube\"></span>\r\n");
      out.write("                                    </a>\r\n");
      out.write("                                </li>\r\n");
      out.write("                                <li class=\"h-white btn\">\r\n");
      out.write("                                    <a class=\"text-gray-450\" href=\"#\">\r\n");
      out.write("                                        <span class=\"fab fa-twitter\"></span>\r\n");
      out.write("                                    </a>\r\n");
      out.write("                                </li>\r\n");
      out.write("                                <li class=\"h-white btn\">\r\n");
      out.write("                                    <a class=\"text-gray-450\" href=\"#\">\r\n");
      out.write("                                        <span class=\"fab fa-pinterest\"></span>\r\n");
      out.write("                                    </a>\r\n");
      out.write("                                </li>\r\n");
      out.write("                            </ul>\r\n");
      out.write("                        </div>\r\n");
      out.write("                    </div>\r\n");
      out.write("                    <div class=\"col-lg-3 mb-6 mb-lg-0\">\r\n");
      out.write("\r\n");
      out.write("                        <div>\r\n");
      out.write("                            <div class=\"mb-5\">\r\n");
      out.write("                                <h5 class=\"font-size-3 font-weight-medium text-white mb-2 mb-xl-5 pb-xl-1\">Join Our\r\n");
      out.write("                                    Newsletter\r\n");
      out.write("                                </h5>\r\n");
      out.write("                                <p class=\"text-gray-450 font-size-2\">Signup to be the first to hear about exclusive\r\n");
      out.write("                                    deals, special offers and upcoming collections</p>\r\n");
      out.write("                            </div>\r\n");
      out.write("                            <form class=\"js-validate js-form-message\" novalidate=\"novalidate\">\r\n");
      out.write("                                <div class=\"input-group\">\r\n");
      out.write("                                    <input type=\"email\"\r\n");
      out.write("                                           class=\"form-control height-50 font-size-2 pl-4 border-0 rounded-left-pill\"\r\n");
      out.write("                                           name=\"email\" id=\"subscribeSrEmail\" placeholder=\"Enter email\"\r\n");
      out.write("                                           aria-label=\"Your email\" aria-describedby=\"subscribeButton\" required\r\n");
      out.write("                                           data-msg=\"Please enter a valid email address.\">\r\n");
      out.write("                                    <div class=\"input-group-append\">\r\n");
      out.write("                                        <button type=\"submit\"\r\n");
      out.write("                                                class=\"btn btn-primary-green text-white px-3 py-2 font-size-4 border-0\"\r\n");
      out.write("                                                id=\"subscribeButton\">\r\n");
      out.write("                                            <span class=\"flaticon-send mx-1\"></span>\r\n");
      out.write("                                        </button>\r\n");
      out.write("                                    </div>\r\n");
      out.write("                                </div>\r\n");
      out.write("                            </form>\r\n");
      out.write("                        </div>\r\n");
      out.write("\r\n");
      out.write("                    </div>\r\n");
      out.write("                </div>\r\n");
      out.write("            </div>\r\n");
      out.write("        </div>\r\n");
      out.write("    </div>\r\n");
      out.write("</footer>\r\n");
      out.write("<!--------------------footer--------------->\r\n");
    } catch (java.lang.Throwable t) {
      if (!(t instanceof jakarta.servlet.jsp.SkipPageException)){
        out = _jspx_out;
        if (out != null && out.getBufferSize() != 0)
          try {
            if (response.isCommitted()) {
              out.flush();
            } else {
              out.clearBuffer();
            }
          } catch (java.io.IOException e) {}
        if (_jspx_page_context != null) _jspx_page_context.handlePageException(t);
        else throw new ServletException(t);
      }
    } finally {
      _jspxFactory.releasePageContext(_jspx_page_context);
    }
  }
}
