/*
 * Generated by the Jasper component of Apache Tomcat
 * Version: Apache Tomcat/10.1.7
 * Generated at: 2023-09-01 13:44:57 UTC
 * Note: The last modified time of this file was set to
 *       the last modified time of the source file after
 *       generation to assist with modification tracking.
 */
package org.apache.jsp.WEB_002dINF.views.frontend;

import jakarta.servlet.*;
import jakarta.servlet.http.*;
import jakarta.servlet.jsp.*;

public final class aboutUs_jsp extends org.apache.jasper.runtime.HttpJspBase
    implements org.apache.jasper.runtime.JspSourceDependent,
                 org.apache.jasper.runtime.JspSourceImports,
                 org.apache.jasper.runtime.JspSourceDirectives {

  private static final jakarta.servlet.jsp.JspFactory _jspxFactory =
          jakarta.servlet.jsp.JspFactory.getDefaultFactory();

  private static java.util.Map<java.lang.String,java.lang.Long> _jspx_dependants;

  static {
    _jspx_dependants = new java.util.HashMap<java.lang.String,java.lang.Long>(2);
    _jspx_dependants.put("file:/C:/Users/Jasir/.m2/repository/lk/callidora/jsp/jsp-template-inheritance/1.0.1/jsp-template-inheritance-1.0.1.jar", Long.valueOf(1692244300354L));
    _jspx_dependants.put("jar:file:/C:/Users/Jasir/.m2/repository/lk/callidora/jsp/jsp-template-inheritance/1.0.1/jsp-template-inheritance-1.0.1.jar!/META-INF/jsp-inheritance.tld", Long.valueOf(1692219220000L));
  }

  private static final java.util.Set<java.lang.String> _jspx_imports_packages;

  private static final java.util.Set<java.lang.String> _jspx_imports_classes;

  static {
    _jspx_imports_packages = new java.util.HashSet<>();
    _jspx_imports_packages.add("jakarta.servlet");
    _jspx_imports_packages.add("jakarta.servlet.http");
    _jspx_imports_packages.add("jakarta.servlet.jsp");
    _jspx_imports_classes = null;
  }

  private volatile jakarta.el.ExpressionFactory _el_expressionfactory;
  private volatile org.apache.tomcat.InstanceManager _jsp_instancemanager;

  public java.util.Map<java.lang.String,java.lang.Long> getDependants() {
    return _jspx_dependants;
  }

  public java.util.Set<java.lang.String> getPackageImports() {
    return _jspx_imports_packages;
  }

  public java.util.Set<java.lang.String> getClassImports() {
    return _jspx_imports_classes;
  }

  public boolean getErrorOnELNotFound() {
    return false;
  }

  public jakarta.el.ExpressionFactory _jsp_getExpressionFactory() {
    if (_el_expressionfactory == null) {
      synchronized (this) {
        if (_el_expressionfactory == null) {
          _el_expressionfactory = _jspxFactory.getJspApplicationContext(getServletConfig().getServletContext()).getExpressionFactory();
        }
      }
    }
    return _el_expressionfactory;
  }

  public org.apache.tomcat.InstanceManager _jsp_getInstanceManager() {
    if (_jsp_instancemanager == null) {
      synchronized (this) {
        if (_jsp_instancemanager == null) {
          _jsp_instancemanager = org.apache.jasper.runtime.InstanceManagerFactory.getInstanceManager(getServletConfig());
        }
      }
    }
    return _jsp_instancemanager;
  }

  public void _jspInit() {
  }

  public void _jspDestroy() {
  }

  public void _jspService(final jakarta.servlet.http.HttpServletRequest request, final jakarta.servlet.http.HttpServletResponse response)
      throws java.io.IOException, jakarta.servlet.ServletException {

    if (!jakarta.servlet.DispatcherType.ERROR.equals(request.getDispatcherType())) {
      final java.lang.String _jspx_method = request.getMethod();
      if ("OPTIONS".equals(_jspx_method)) {
        response.setHeader("Allow","GET, HEAD, POST, OPTIONS");
        return;
      }
      if (!"GET".equals(_jspx_method) && !"POST".equals(_jspx_method) && !"HEAD".equals(_jspx_method)) {
        response.setHeader("Allow","GET, HEAD, POST, OPTIONS");
        response.sendError(HttpServletResponse.SC_METHOD_NOT_ALLOWED, "JSPs only permit GET, POST or HEAD. Jasper also permits OPTIONS");
        return;
      }
    }

    final jakarta.servlet.jsp.PageContext pageContext;
    jakarta.servlet.http.HttpSession session = null;
    final jakarta.servlet.ServletContext application;
    final jakarta.servlet.ServletConfig config;
    jakarta.servlet.jsp.JspWriter out = null;
    final java.lang.Object page = this;
    jakarta.servlet.jsp.JspWriter _jspx_out = null;
    jakarta.servlet.jsp.PageContext _jspx_page_context = null;


    try {
      response.setContentType("text/html;charset=UTF-8");
      pageContext = _jspxFactory.getPageContext(this, request, response,
      			null, true, 8192, true);
      _jspx_page_context = pageContext;
      application = pageContext.getServletContext();
      config = pageContext.getServletConfig();
      session = pageContext.getSession();
      out = pageContext.getOut();
      _jspx_out = out;

      out.write("\r\n");
      out.write("\r\n");
      out.write("\r\n");
      if (_jspx_meth_layout_005fextends_005f0(_jspx_page_context))
        return;
      out.write('\r');
      out.write('\n');
    } catch (java.lang.Throwable t) {
      if (!(t instanceof jakarta.servlet.jsp.SkipPageException)){
        out = _jspx_out;
        if (out != null && out.getBufferSize() != 0)
          try {
            if (response.isCommitted()) {
              out.flush();
            } else {
              out.clearBuffer();
            }
          } catch (java.io.IOException e) {}
        if (_jspx_page_context != null) _jspx_page_context.handlePageException(t);
        else throw new ServletException(t);
      }
    } finally {
      _jspxFactory.releasePageContext(_jspx_page_context);
    }
  }

  private boolean _jspx_meth_layout_005fextends_005f0(jakarta.servlet.jsp.PageContext _jspx_page_context)
          throws java.lang.Throwable {
    jakarta.servlet.jsp.PageContext pageContext = _jspx_page_context;
    jakarta.servlet.jsp.JspWriter out = _jspx_page_context.getOut();
    //  layout:extends
    lk.callidora.jsp.inheritance.ExtendsTag _jspx_th_layout_005fextends_005f0 = new lk.callidora.jsp.inheritance.ExtendsTag();
    _jsp_getInstanceManager().newInstance(_jspx_th_layout_005fextends_005f0);
    try {
      _jspx_th_layout_005fextends_005f0.setJspContext(_jspx_page_context);
      // /WEB-INF/views/frontend/aboutUs.jsp(4,0) name = name type = null reqTime = true required = true fragment = false deferredValue = false expectedTypeName = null deferredMethod = false methodSignature = null
      _jspx_th_layout_005fextends_005f0.setName("base");
      _jspx_th_layout_005fextends_005f0.setJspBody(new Helper( 0, _jspx_page_context, _jspx_th_layout_005fextends_005f0, null));
      _jspx_th_layout_005fextends_005f0.doTag();
    } finally {
      _jsp_getInstanceManager().destroyInstance(_jspx_th_layout_005fextends_005f0);
    }
    return false;
  }

  private boolean _jspx_meth_layout_005fput_005f0(jakarta.servlet.jsp.tagext.JspTag _jspx_parent, jakarta.servlet.jsp.PageContext _jspx_page_context)
          throws java.lang.Throwable {
    jakarta.servlet.jsp.PageContext pageContext = _jspx_page_context;
    jakarta.servlet.jsp.JspWriter out = _jspx_page_context.getOut();
    //  layout:put
    lk.callidora.jsp.inheritance.PutTag _jspx_th_layout_005fput_005f0 = new lk.callidora.jsp.inheritance.PutTag();
    _jsp_getInstanceManager().newInstance(_jspx_th_layout_005fput_005f0);
    try {
      _jspx_th_layout_005fput_005f0.setJspContext(_jspx_page_context);
      _jspx_th_layout_005fput_005f0.setParent(_jspx_parent);
      // /WEB-INF/views/frontend/aboutUs.jsp(5,4) name = block type = null reqTime = true required = true fragment = false deferredValue = false expectedTypeName = null deferredMethod = false methodSignature = null
      _jspx_th_layout_005fput_005f0.setBlock("title");
      _jspx_th_layout_005fput_005f0.setJspBody(new Helper( 1, _jspx_page_context, _jspx_th_layout_005fput_005f0, null));
      _jspx_th_layout_005fput_005f0.doTag();
    } finally {
      _jsp_getInstanceManager().destroyInstance(_jspx_th_layout_005fput_005f0);
    }
    return false;
  }

  private boolean _jspx_meth_layout_005fput_005f1(jakarta.servlet.jsp.tagext.JspTag _jspx_parent, jakarta.servlet.jsp.PageContext _jspx_page_context)
          throws java.lang.Throwable {
    jakarta.servlet.jsp.PageContext pageContext = _jspx_page_context;
    jakarta.servlet.jsp.JspWriter out = _jspx_page_context.getOut();
    //  layout:put
    lk.callidora.jsp.inheritance.PutTag _jspx_th_layout_005fput_005f1 = new lk.callidora.jsp.inheritance.PutTag();
    _jsp_getInstanceManager().newInstance(_jspx_th_layout_005fput_005f1);
    try {
      _jspx_th_layout_005fput_005f1.setJspContext(_jspx_page_context);
      _jspx_th_layout_005fput_005f1.setParent(_jspx_parent);
      // /WEB-INF/views/frontend/aboutUs.jsp(8,4) name = block type = null reqTime = true required = true fragment = false deferredValue = false expectedTypeName = null deferredMethod = false methodSignature = null
      _jspx_th_layout_005fput_005f1.setBlock("contents");
      _jspx_th_layout_005fput_005f1.setJspBody(new Helper( 2, _jspx_page_context, _jspx_th_layout_005fput_005f1, null));
      _jspx_th_layout_005fput_005f1.doTag();
    } finally {
      _jsp_getInstanceManager().destroyInstance(_jspx_th_layout_005fput_005f1);
    }
    return false;
  }

  private class Helper
      extends org.apache.jasper.runtime.JspFragmentHelper
  {
    private jakarta.servlet.jsp.tagext.JspTag _jspx_parent;
    private int[] _jspx_push_body_count;

    public Helper( int discriminator, jakarta.servlet.jsp.JspContext jspContext, jakarta.servlet.jsp.tagext.JspTag _jspx_parent, int[] _jspx_push_body_count ) {
      super( discriminator, jspContext, _jspx_parent );
      this._jspx_parent = _jspx_parent;
      this._jspx_push_body_count = _jspx_push_body_count;
    }
    public boolean invoke0( jakarta.servlet.jsp.JspWriter out ) 
      throws java.lang.Throwable
    {
      out.write("\r\n");
      out.write("    ");
      if (_jspx_meth_layout_005fput_005f0(_jspx_parent, _jspx_page_context))
        return true;
      out.write("\r\n");
      out.write("    ");
      if (_jspx_meth_layout_005fput_005f1(_jspx_parent, _jspx_page_context))
        return true;
      out.write('\r');
      out.write('\n');
      return false;
    }
    public boolean invoke1( jakarta.servlet.jsp.JspWriter out ) 
      throws java.lang.Throwable
    {
      out.write("\r\n");
      out.write("        <title>About Us | eBookStore</title>\r\n");
      out.write("    ");
      return false;
    }
    public boolean invoke2( jakarta.servlet.jsp.JspWriter out ) 
      throws java.lang.Throwable
    {
      out.write("\r\n");
      out.write("        <main id=\"content\">\r\n");
      out.write("            <div class=\"mb-5 space-bottom-lg-3\">\r\n");
      out.write("                <div class=\"py-3 py-lg-7\">\r\n");
      out.write("                    <h6 class=\"font-weight-medium font-size-7 text-center my-1\">About Us</h6>\r\n");
      out.write("                </div>\r\n");
      out.write("                <img class=\"img-fluid\" src=\"assets/img/1920x650/img1.jpg\" alt=\"Image-Description\">\r\n");
      out.write("                <div class=\"container\">\r\n");
      out.write("                    <div class=\"mb-lg-8\">\r\n");
      out.write("                        <div class=\"col-lg-9 mx-auto\">\r\n");
      out.write("                            <div class=\"bg-white mt-n10 mt-md-n13 pt-5 pt-lg-7 px-3 px-md-5 pl-xl-10 pr-xl-4\">\r\n");
      out.write("                                <div class=\"mb-4 mb-lg-7 ml-xl-4\">\r\n");
      out.write("                                    <h6 class=\"font-weight medium font-size-10 mb-4 mb-lg-7\">Welcome to eBookStore</h6>\r\n");
      out.write("                                    <p class=\"font-weight-medium font-italic\">“ Many desktop publishing packages and web page\r\n");
      out.write("                                        editors now use Lorem Ipsum as their default model search for eolved over sometimes by\r\n");
      out.write("                                        accident, sometimes on purpose ”</p>\r\n");
      out.write("                                </div>\r\n");
      out.write("                                <div class=\"mb-4 pb-xl-1 ml-xl-4\">\r\n");
      out.write("                                    <h6 class=\"font-weight-medium font-size-4 mb-4\">What we really do?</h6>\r\n");
      out.write("                                    <p class=\"font-size-2\">Mauris tempus erat laoreet turpis lobortis, eu tincidunt erat\r\n");
      out.write("                                        fermentum. Aliquam non tincidunt urna. Integer tincidunt nec nisl vitae ullamcorper.\r\n");
      out.write("                                        Proin sed ultrices erat. Praesent varius ultrices massa at faucibus. Aenean\r\n");
      out.write("                                        dignissim, orci sed faucibus pharetra, dui mi dignissim tortor, sit amet condimentum mi\r\n");
      out.write("                                        ligula sit amet augue. Pellentesque vitae eros eget enim mollis placerat. Aliquam non\r\n");
      out.write("                                        tincidunt urna. Integer tincidunt nec nisl\r\n");
      out.write("                                        vitae ullamcorper. Proin sed ultrices erat. Praesent varius ultrices massa at faucibus.\r\n");
      out.write("                                        Aenean dignissim, orci sed faucibus pharetra, dui mi dignissim tortor, sit amet\r\n");
      out.write("                                        condimentum mi ligula sit amet augue. Pellentesque\r\n");
      out.write("                                        vitae eros eget enim mollis placerat.</p>\r\n");
      out.write("                                </div>\r\n");
      out.write("                                <div class=\"ml-xl-4\">\r\n");
      out.write("                                    <div class=\"row\">\r\n");
      out.write("                                        <div class=\"col-md-6\">\r\n");
      out.write("                                            <h6 class=\"font-weight-medium font-size-4\">Our Vision</h6>\r\n");
      out.write("                                            <p class=\"font-size-2\">Pellentesque sodales augue eget ultricies ultricies. Cum\r\n");
      out.write("                                                sociis natoque penatibus et magnis dis parturient montes, nascetur ridiculus\r\n");
      out.write("                                                mus. Curabitur sagittis ultrices condimentum.</p>\r\n");
      out.write("                                        </div>\r\n");
      out.write("                                        <div class=\"col-md-6\">\r\n");
      out.write("                                            <h6 class=\"font-weight-medium font-size-4\">Our Vision</h6>\r\n");
      out.write("                                            <p class=\"font-size-2\">Lorem ipsum dolor sit amet, consectetur adipiscing elit.\r\n");
      out.write("                                                Etiam quis diam erat. Duis velit lectus, posuere a blandit metus mauris,\r\n");
      out.write("                                                tristique quis sapien eu, rutrum vulputate enim.</p>\r\n");
      out.write("                                        </div>\r\n");
      out.write("                                    </div>\r\n");
      out.write("                                </div>\r\n");
      out.write("                            </div>\r\n");
      out.write("                        </div>\r\n");
      out.write("                    </div>\r\n");
      out.write("                    <div class=\"mb-5 mb-lg-7\">\r\n");
      out.write("                        <div class=\"d-md-flex align-items-center justify-content-between px-xl-10\">\r\n");
      out.write("                            <div class=\"text-center mb-3 mb-md-0\">\r\n");
      out.write("                                <div class=\"font-size-12 font-weight-medium ml-lg-2\">45M</div>\r\n");
      out.write("                                <span class=\"font-size-4\">Active Readers</span>\r\n");
      out.write("                            </div>\r\n");
      out.write("                            <div class=\"text-center mb-3 mb-md-0\">\r\n");
      out.write("                                <div class=\"font-size-12 font-weight-medium ml-2\">+6k</div>\r\n");
      out.write("                                <span class=\"font-size-4\">Total Pages</span>\r\n");
      out.write("                            </div>\r\n");
      out.write("                            <div class=\"text-center mb-3 mb-md-0\">\r\n");
      out.write("                                <div class=\"font-size-12 font-weight-medium \">30.6M</div>\r\n");
      out.write("                                <span class=\"font-size-4\">Buyers Activie</span>\r\n");
      out.write("                            </div>\r\n");
      out.write("                            <div class=\"text-center mb-0\">\r\n");
      out.write("                                <div class=\"font-size-12 font-weight-medium ml-2\">283</div>\r\n");
      out.write("                                <span class=\"font-size-4\">Cup Of Coffe</span>\r\n");
      out.write("                            </div>\r\n");
      out.write("                        </div>\r\n");
      out.write("                    </div>\r\n");
      out.write("                    <div class=\"mb-5 mb-lg-10\">\r\n");
      out.write("                        <h6 class=\"font-weight-medium font-size-7 mb-5 mb-lg-6\">Why We</h6>\r\n");
      out.write("                        <ul class=\"list-unstyled my-0 list-features row d-md-flex\">\r\n");
      out.write("                            <li class=\"list-feature mb-5 mb-lg-0 col-md-6 col-lg-3\">\r\n");
      out.write("                                <div class=\"media flex-column align-items-center align-items-md-start pr-xl-3\">\r\n");
      out.write("                                    <div class=\"feature__icon font-size-14 text-primary text-lh-xs mb-3\">\r\n");
      out.write("                                        <i class=\"glyph-icon flaticon-delivery\"></i>\r\n");
      out.write("                                    </div>\r\n");
      out.write("                                    <div class=\"media-body text-center text-md-left\">\r\n");
      out.write("                                        <h4 class=\"feature__title font-size-3 text-dark\">Free Delivery</h4>\r\n");
      out.write("                                        <p class=\"feature__subtitle m-0 text-dark\">Duis aute irure dolor in reprehenderit in\r\n");
      out.write("                                            voluptate velit esse cillum dolore eu.</p>\r\n");
      out.write("                                    </div>\r\n");
      out.write("                                </div>\r\n");
      out.write("                            </li>\r\n");
      out.write("                            <li class=\"list-feature  mb-5 mb-lg-0 col-md-6 col-lg-3\">\r\n");
      out.write("                                <div class=\"media flex-column align-items-center align-items-md-start pr-xl-3\">\r\n");
      out.write("                                    <div class=\"feature__icon font-size-14 text-primary text-lh-xs mb-3\">\r\n");
      out.write("                                        <i class=\"glyph-icon flaticon-credit\"></i>\r\n");
      out.write("                                    </div>\r\n");
      out.write("                                    <div class=\"media-body text-center text-md-left\">\r\n");
      out.write("                                        <h4 class=\"feature__title font-size-3 text-dark\">Secure Payment</h4>\r\n");
      out.write("                                        <p class=\"feature__subtitle m-0 text-dark\">Duis aute irure dolor in reprehenderit in\r\n");
      out.write("                                            voluptate velit esse cillum dolore eu.</p>\r\n");
      out.write("                                    </div>\r\n");
      out.write("                                </div>\r\n");
      out.write("                            </li>\r\n");
      out.write("                            <li class=\"list-feature  mb-5 mb-md-0 col-md-6 col-lg-3\">\r\n");
      out.write("                                <div class=\"media flex-column align-items-center align-items-md-start pr-xl-3\">\r\n");
      out.write("                                    <div class=\"feature__icon font-size-14 text-primary text-lh-xs mb-3\">\r\n");
      out.write("                                        <i class=\"glyph-icon flaticon-warranty\"></i>\r\n");
      out.write("                                    </div>\r\n");
      out.write("                                    <div class=\"media-body text-center text-md-left\">\r\n");
      out.write("                                        <h4 class=\"feature__title font-size-3 text-dark\">Money Back Guarantee</h4>\r\n");
      out.write("                                        <p class=\"feature__subtitle m-0 text-dark\">Duis aute irure dolor in reprehenderit in\r\n");
      out.write("                                            voluptate velit esse cillum dolore eu.</p>\r\n");
      out.write("                                    </div>\r\n");
      out.write("                                </div>\r\n");
      out.write("                            </li>\r\n");
      out.write("                            <li class=\"list-feature  mb-5 mb-md-0 col-md-6 col-lg-3\">\r\n");
      out.write("                                <div class=\"media flex-column align-items-center align-items-md-start pr-xl-3\">\r\n");
      out.write("                                    <div class=\"feature__icon font-size-14 text-primary text-lh-xs mb-3\">\r\n");
      out.write("                                        <i class=\"glyph-icon flaticon-help\"></i>\r\n");
      out.write("                                    </div>\r\n");
      out.write("                                    <div class=\"media-body text-center text-md-left\">\r\n");
      out.write("                                        <h4 class=\"feature__title font-size-3 text-dark\">24/7 Support</h4>\r\n");
      out.write("                                        <p class=\"feature__subtitle m-0 text-dark\">Duis aute irure dolor in reprehenderit in\r\n");
      out.write("                                            voluptate velit esse cillum dolore eu.</p>\r\n");
      out.write("                                    </div>\r\n");
      out.write("                                </div>\r\n");
      out.write("                            </li>\r\n");
      out.write("                        </ul>\r\n");
      out.write("                    </div>\r\n");
      out.write("                    <div class=\"mb-10 pb-md-6 pb-lg-10\">\r\n");
      out.write("                        <h6 class=\"font-weight-medium font-size-7 mb-5\">Our Team</h6>\r\n");
      out.write("                        <div class=\"js-slick-carousel u-slick\"\r\n");
      out.write("                             data-pagi-classes=\"text-center u-slick__pagination mt-md-8 mt-4 position-absolute right-0 left-0\"\r\n");
      out.write("                             data-slides-show=\"5\" data-responsive=\"[{\r\n");
      out.write("                           &quot;breakpoint&quot;: 992,\r\n");
      out.write("                           &quot;settings&quot;: {\r\n");
      out.write("                             &quot;slidesToShow&quot;: 2\r\n");
      out.write("                           }\r\n");
      out.write("                        }, {\r\n");
      out.write("                           &quot;breakpoint&quot;: 768,\r\n");
      out.write("                           &quot;settings&quot;: {\r\n");
      out.write("                             &quot;slidesToShow&quot;: 1\r\n");
      out.write("                           }\r\n");
      out.write("                        }, {\r\n");
      out.write("                           &quot;breakpoint&quot;: 554,\r\n");
      out.write("                           &quot;settings&quot;: {\r\n");
      out.write("                             &quot;slidesToShow&quot;: 1\r\n");
      out.write("                           }\r\n");
      out.write("                        }]\">\r\n");
      out.write("                            <div class=\"product__inner overflow-hidden\">\r\n");
      out.write("                                <div class=\"woocommerce-LoopProduct-link woocommerce-loop-product__link d-block position-relative\">\r\n");
      out.write("                                    <div class=\"woocommerce-loop-product__thumbnail border pt-5 mb-3\">\r\n");
      out.write("                                        <a href=\"#\" class=\"d-block\"><img src=\"assets/img/329x330/img2.png\"\r\n");
      out.write("                                                                         class=\"img-fluid mx-auto d-block attachment-shop_catalog size-shop_catalog wp-post-image\"\r\n");
      out.write("                                                                         alt=\"image-description\"></a>\r\n");
      out.write("                                    </div>\r\n");
      out.write("                                    <div class=\"woocommerce-loop-product__body product__body\">\r\n");
      out.write("                                        <h6 class=\"font-weight-regular mb-1\">Anna Baranov</h6>\r\n");
      out.write("                                        <span class=\"font-size-2 text-secondary-gray-700\">Client Care</span>\r\n");
      out.write("                                    </div>\r\n");
      out.write("                                </div>\r\n");
      out.write("                            </div>\r\n");
      out.write("                            <div class=\"product__inner overflow-hidden\">\r\n");
      out.write("                                <div class=\"woocommerce-LoopProduct-link woocommerce-loop-product__link d-block position-relative\">\r\n");
      out.write("                                    <div class=\"woocommerce-loop-product__thumbnail border border-left-0 pt-5 mb-3\">\r\n");
      out.write("                                        <a href=\"#\" class=\"d-block\"><img src=\"assets/img/329x330/img3.png\"\r\n");
      out.write("                                                                         class=\"img-fluid mx-auto d-block attachment-shop_catalog size-shop_catalog wp-post-image\"\r\n");
      out.write("                                                                         alt=\"image-description\"></a>\r\n");
      out.write("                                    </div>\r\n");
      out.write("                                    <div class=\"woocommerce-loop-product__body product__body\">\r\n");
      out.write("                                        <h6 class=\"font-weight-regular mb-1\">Thomas Snow</h6>\r\n");
      out.write("                                        <span class=\"font-size-2 text-secondary-gray-700\">CEO/Founder</span>\r\n");
      out.write("                                    </div>\r\n");
      out.write("                                </div>\r\n");
      out.write("                            </div>\r\n");
      out.write("                            <div class=\"product__inner overflow-hidden\">\r\n");
      out.write("                                <div class=\"woocommerce-LoopProduct-link woocommerce-loop-product__link d-block position-relative\">\r\n");
      out.write("                                    <div class=\"woocommerce-loop-product__thumbnail border border-left-0 pt-5 mb-3\">\r\n");
      out.write("                                        <a href=\"#\" class=\"d-block\"><img src=\"assets/img/329x330/img4.png\"\r\n");
      out.write("                                                                         class=\"img-fluid mx-auto d-block attachment-shop_catalog size-shop_catalog wp-post-image\"\r\n");
      out.write("                                                                         alt=\"image-description\"></a>\r\n");
      out.write("                                    </div>\r\n");
      out.write("                                    <div class=\"woocommerce-loop-product__body product__body\">\r\n");
      out.write("                                        <h6 class=\"font-weight-regular mb-1\">Andre Kowalsy</h6>\r\n");
      out.write("                                        <span class=\"font-size-2 text-secondary-gray-700\">Support Boss</span>\r\n");
      out.write("                                    </div>\r\n");
      out.write("                                </div>\r\n");
      out.write("                            </div>\r\n");
      out.write("                            <div class=\"product__inner overflow-hidden\">\r\n");
      out.write("                                <div class=\"woocommerce-LoopProduct-link woocommerce-loop-product__link d-block position-relative\">\r\n");
      out.write("                                    <div class=\"woocommerce-loop-product__thumbnail border border-left-0 pt-5 mb-3\">\r\n");
      out.write("                                        <a href=\"#\" class=\"d-block\"><img src=\"assets/img/329x330/img5.png\"\r\n");
      out.write("                                                                         class=\"img-fluid mx-auto d-block attachment-shop_catalog size-shop_catalog wp-post-image\"\r\n");
      out.write("                                                                         alt=\"image-description\"></a>\r\n");
      out.write("                                    </div>\r\n");
      out.write("                                    <div class=\"woocommerce-loop-product__body product__body\">\r\n");
      out.write("                                        <h6 class=\"font-weight-regular mb-1\">Pamela Doe</h6>\r\n");
      out.write("                                        <span class=\"font-size-2 text-secondary-gray-700\">Delivery Driver</span>\r\n");
      out.write("                                    </div>\r\n");
      out.write("                                </div>\r\n");
      out.write("                            </div>\r\n");
      out.write("                            <div class=\"product__inner overflow-hidden\">\r\n");
      out.write("                                <div class=\"woocommerce-LoopProduct-link woocommerce-loop-product__link d-block position-relative\">\r\n");
      out.write("                                    <div class=\"woocommerce-loop-product__thumbnail border border-left-0 pt-5 mb-3\">\r\n");
      out.write("                                        <a href=\"#\" class=\"d-block\"><img src=\"assets/img/329x330/img2.png\"\r\n");
      out.write("                                                                         class=\"img-fluid mx-auto d-block attachment-shop_catalog size-shop_catalog wp-post-image\"\r\n");
      out.write("                                                                         alt=\"image-description\"></a>\r\n");
      out.write("                                    </div>\r\n");
      out.write("                                    <div class=\"woocommerce-loop-product__body product__body\">\r\n");
      out.write("                                        <h6 class=\"font-weight-regular mb-1\">Susan McCain</h6>\r\n");
      out.write("                                        <span class=\"font-size-2 text-secondary-gray-700\">Packaging Girl</span>\r\n");
      out.write("                                    </div>\r\n");
      out.write("                                </div>\r\n");
      out.write("                            </div>\r\n");
      out.write("                            <div class=\"product__inner overflow-hidden\">\r\n");
      out.write("                                <div class=\"woocommerce-LoopProduct-link woocommerce-loop-product__link d-block position-relative\">\r\n");
      out.write("                                    <div class=\"woocommerce-loop-product__thumbnail border border-left-0 pt-5 mb-3\">\r\n");
      out.write("                                        <a href=\"#\" class=\"d-block\"><img src=\"assets/img/329x330/img3.png\"\r\n");
      out.write("                                                                         class=\"img-fluid mx-auto d-block attachment-shop_catalog size-shop_catalog wp-post-image\"\r\n");
      out.write("                                                                         alt=\"image-description\"></a>\r\n");
      out.write("                                    </div>\r\n");
      out.write("                                    <div class=\"woocommerce-loop-product__body product__body\">\r\n");
      out.write("                                        <h6 class=\"font-weight-regular mb-1\">Andre Kowalsy</h6>\r\n");
      out.write("                                        <span class=\"font-size-2 text-secondary-gray-700\">Support Boss</span>\r\n");
      out.write("                                    </div>\r\n");
      out.write("                                </div>\r\n");
      out.write("                            </div>\r\n");
      out.write("                            <div class=\"product__inner overflow-hidden\">\r\n");
      out.write("                                <div class=\"woocommerce-LoopProduct-link woocommerce-loop-product__link d-block position-relative\">\r\n");
      out.write("                                    <div class=\"woocommerce-loop-product__thumbnail border border-left-0 pt-5 mb-3\">\r\n");
      out.write("                                        <a href=\"#\" class=\"d-block\"><img src=\"assets/img/329x330/img4.png\"\r\n");
      out.write("                                                                         class=\"img-fluid mx-auto d-block attachment-shop_catalog size-shop_catalog wp-post-image\"\r\n");
      out.write("                                                                         alt=\"image-description\"></a>\r\n");
      out.write("                                    </div>\r\n");
      out.write("                                    <div class=\"woocommerce-loop-product__body product__body\">\r\n");
      out.write("                                        <h6 class=\"font-weight-regular mb-1\">Pamela Doe</h6>\r\n");
      out.write("                                        <span class=\"font-size-2 text-secondary-gray-700\">Delivery Driver</span>\r\n");
      out.write("                                    </div>\r\n");
      out.write("                                </div>\r\n");
      out.write("                            </div>\r\n");
      out.write("                            <div class=\"product__inner overflow-hidden\">\r\n");
      out.write("                                <div class=\"woocommerce-LoopProduct-link woocommerce-loop-product__link d-block position-relative\">\r\n");
      out.write("                                    <div class=\"woocommerce-loop-product__thumbnail border border-left-0 pt-5 mb-3\">\r\n");
      out.write("                                        <a href=\"#\" class=\"d-block\"><img src=\"assets/img/329x330/img2.png\"\r\n");
      out.write("                                                                         class=\"img-fluid mx-auto d-block attachment-shop_catalog size-shop_catalog wp-post-image\"\r\n");
      out.write("                                                                         alt=\"image-description\"></a>\r\n");
      out.write("                                    </div>\r\n");
      out.write("                                    <div class=\"woocommerce-loop-product__body product__body\">\r\n");
      out.write("                                        <h6 class=\"font-weight-regular mb-1\">Thomas Snow</h6>\r\n");
      out.write("                                        <span class=\"font-size-2 text-secondary-gray-700\">CEO/Founder</span>\r\n");
      out.write("                                    </div>\r\n");
      out.write("                                </div>\r\n");
      out.write("                            </div>\r\n");
      out.write("                        </div>\r\n");
      out.write("                    </div>\r\n");
      out.write("                    \r\n");
      out.write("                </div>\r\n");
      out.write("            </div>\r\n");
      out.write("        </main>\r\n");
      out.write("    ");
      return false;
    }
    public void invoke( java.io.Writer writer )
      throws jakarta.servlet.jsp.JspException
    {
      jakarta.servlet.jsp.JspWriter out = null;
      if( writer != null ) {
        out = this.jspContext.pushBody(writer);
      } else {
        out = this.jspContext.getOut();
      }
      try {
        Object _jspx_saved_JspContext = this.jspContext.getELContext().getContext(jakarta.servlet.jsp.JspContext.class);
        this.jspContext.getELContext().putContext(jakarta.servlet.jsp.JspContext.class,this.jspContext);
        switch( this.discriminator ) {
          case 0:
            invoke0( out );
            break;
          case 1:
            invoke1( out );
            break;
          case 2:
            invoke2( out );
            break;
        }
        jspContext.getELContext().putContext(jakarta.servlet.jsp.JspContext.class,_jspx_saved_JspContext);
      }
      catch( java.lang.Throwable e ) {
        if (e instanceof jakarta.servlet.jsp.SkipPageException)
            throw (jakarta.servlet.jsp.SkipPageException) e;
        throw new jakarta.servlet.jsp.JspException( e );
      }
      finally {
        if( writer != null ) {
          this.jspContext.popBody();
        }
      }
    }
  }
}
