/*
 * Generated by the Jasper component of Apache Tomcat
 * Version: Apache Tomcat/10.1.7
 * Generated at: 2023-08-29 11:24:27 UTC
 * Note: The last modified time of this file was set to
 *       the last modified time of the source file after
 *       generation to assist with modification tracking.
 */
package org.apache.jsp.WEB_002dINF.views.frontend;

import jakarta.servlet.*;
import jakarta.servlet.http.*;
import jakarta.servlet.jsp.*;

public final class authorSingle_jsp extends org.apache.jasper.runtime.HttpJspBase
    implements org.apache.jasper.runtime.JspSourceDependent,
                 org.apache.jasper.runtime.JspSourceImports,
                 org.apache.jasper.runtime.JspSourceDirectives {

  private static final jakarta.servlet.jsp.JspFactory _jspxFactory =
          jakarta.servlet.jsp.JspFactory.getDefaultFactory();

  private static java.util.Map<java.lang.String,java.lang.Long> _jspx_dependants;

  static {
    _jspx_dependants = new java.util.HashMap<java.lang.String,java.lang.Long>(2);
    _jspx_dependants.put("file:/C:/Users/Jasir/.m2/repository/lk/callidora/jsp/jsp-template-inheritance/1.0.1/jsp-template-inheritance-1.0.1.jar", Long.valueOf(1692244300354L));
    _jspx_dependants.put("jar:file:/C:/Users/Jasir/.m2/repository/lk/callidora/jsp/jsp-template-inheritance/1.0.1/jsp-template-inheritance-1.0.1.jar!/META-INF/jsp-inheritance.tld", Long.valueOf(1692219220000L));
  }

  private static final java.util.Set<java.lang.String> _jspx_imports_packages;

  private static final java.util.Set<java.lang.String> _jspx_imports_classes;

  static {
    _jspx_imports_packages = new java.util.HashSet<>();
    _jspx_imports_packages.add("jakarta.servlet");
    _jspx_imports_packages.add("jakarta.servlet.http");
    _jspx_imports_packages.add("jakarta.servlet.jsp");
    _jspx_imports_classes = null;
  }

  private volatile jakarta.el.ExpressionFactory _el_expressionfactory;
  private volatile org.apache.tomcat.InstanceManager _jsp_instancemanager;

  public java.util.Map<java.lang.String,java.lang.Long> getDependants() {
    return _jspx_dependants;
  }

  public java.util.Set<java.lang.String> getPackageImports() {
    return _jspx_imports_packages;
  }

  public java.util.Set<java.lang.String> getClassImports() {
    return _jspx_imports_classes;
  }

  public boolean getErrorOnELNotFound() {
    return false;
  }

  public jakarta.el.ExpressionFactory _jsp_getExpressionFactory() {
    if (_el_expressionfactory == null) {
      synchronized (this) {
        if (_el_expressionfactory == null) {
          _el_expressionfactory = _jspxFactory.getJspApplicationContext(getServletConfig().getServletContext()).getExpressionFactory();
        }
      }
    }
    return _el_expressionfactory;
  }

  public org.apache.tomcat.InstanceManager _jsp_getInstanceManager() {
    if (_jsp_instancemanager == null) {
      synchronized (this) {
        if (_jsp_instancemanager == null) {
          _jsp_instancemanager = org.apache.jasper.runtime.InstanceManagerFactory.getInstanceManager(getServletConfig());
        }
      }
    }
    return _jsp_instancemanager;
  }

  public void _jspInit() {
  }

  public void _jspDestroy() {
  }

  public void _jspService(final jakarta.servlet.http.HttpServletRequest request, final jakarta.servlet.http.HttpServletResponse response)
      throws java.io.IOException, jakarta.servlet.ServletException {

    if (!jakarta.servlet.DispatcherType.ERROR.equals(request.getDispatcherType())) {
      final java.lang.String _jspx_method = request.getMethod();
      if ("OPTIONS".equals(_jspx_method)) {
        response.setHeader("Allow","GET, HEAD, POST, OPTIONS");
        return;
      }
      if (!"GET".equals(_jspx_method) && !"POST".equals(_jspx_method) && !"HEAD".equals(_jspx_method)) {
        response.setHeader("Allow","GET, HEAD, POST, OPTIONS");
        response.sendError(HttpServletResponse.SC_METHOD_NOT_ALLOWED, "JSPs only permit GET, POST or HEAD. Jasper also permits OPTIONS");
        return;
      }
    }

    final jakarta.servlet.jsp.PageContext pageContext;
    jakarta.servlet.http.HttpSession session = null;
    final jakarta.servlet.ServletContext application;
    final jakarta.servlet.ServletConfig config;
    jakarta.servlet.jsp.JspWriter out = null;
    final java.lang.Object page = this;
    jakarta.servlet.jsp.JspWriter _jspx_out = null;
    jakarta.servlet.jsp.PageContext _jspx_page_context = null;


    try {
      response.setContentType("text/html;charset=UTF-8");
      pageContext = _jspxFactory.getPageContext(this, request, response,
      			null, true, 8192, true);
      _jspx_page_context = pageContext;
      application = pageContext.getServletContext();
      config = pageContext.getServletConfig();
      session = pageContext.getSession();
      out = pageContext.getOut();
      _jspx_out = out;

      out.write("\r\n");
      out.write("\r\n");
      out.write("\r\n");
      if (_jspx_meth_layout_005fextends_005f0(_jspx_page_context))
        return;
      out.write('\r');
      out.write('\n');
    } catch (java.lang.Throwable t) {
      if (!(t instanceof jakarta.servlet.jsp.SkipPageException)){
        out = _jspx_out;
        if (out != null && out.getBufferSize() != 0)
          try {
            if (response.isCommitted()) {
              out.flush();
            } else {
              out.clearBuffer();
            }
          } catch (java.io.IOException e) {}
        if (_jspx_page_context != null) _jspx_page_context.handlePageException(t);
        else throw new ServletException(t);
      }
    } finally {
      _jspxFactory.releasePageContext(_jspx_page_context);
    }
  }

  private boolean _jspx_meth_layout_005fextends_005f0(jakarta.servlet.jsp.PageContext _jspx_page_context)
          throws java.lang.Throwable {
    jakarta.servlet.jsp.PageContext pageContext = _jspx_page_context;
    jakarta.servlet.jsp.JspWriter out = _jspx_page_context.getOut();
    //  layout:extends
    lk.callidora.jsp.inheritance.ExtendsTag _jspx_th_layout_005fextends_005f0 = new lk.callidora.jsp.inheritance.ExtendsTag();
    _jsp_getInstanceManager().newInstance(_jspx_th_layout_005fextends_005f0);
    try {
      _jspx_th_layout_005fextends_005f0.setJspContext(_jspx_page_context);
      // /WEB-INF/views/frontend/authorSingle.jsp(4,0) name = name type = null reqTime = true required = true fragment = false deferredValue = false expectedTypeName = null deferredMethod = false methodSignature = null
      _jspx_th_layout_005fextends_005f0.setName("base");
      _jspx_th_layout_005fextends_005f0.setJspBody(new Helper( 0, _jspx_page_context, _jspx_th_layout_005fextends_005f0, null));
      _jspx_th_layout_005fextends_005f0.doTag();
    } finally {
      _jsp_getInstanceManager().destroyInstance(_jspx_th_layout_005fextends_005f0);
    }
    return false;
  }

  private boolean _jspx_meth_layout_005fput_005f0(jakarta.servlet.jsp.tagext.JspTag _jspx_parent, jakarta.servlet.jsp.PageContext _jspx_page_context)
          throws java.lang.Throwable {
    jakarta.servlet.jsp.PageContext pageContext = _jspx_page_context;
    jakarta.servlet.jsp.JspWriter out = _jspx_page_context.getOut();
    //  layout:put
    lk.callidora.jsp.inheritance.PutTag _jspx_th_layout_005fput_005f0 = new lk.callidora.jsp.inheritance.PutTag();
    _jsp_getInstanceManager().newInstance(_jspx_th_layout_005fput_005f0);
    try {
      _jspx_th_layout_005fput_005f0.setJspContext(_jspx_page_context);
      _jspx_th_layout_005fput_005f0.setParent(_jspx_parent);
      // /WEB-INF/views/frontend/authorSingle.jsp(5,4) name = block type = null reqTime = true required = true fragment = false deferredValue = false expectedTypeName = null deferredMethod = false methodSignature = null
      _jspx_th_layout_005fput_005f0.setBlock("title");
      _jspx_th_layout_005fput_005f0.setJspBody(new Helper( 1, _jspx_page_context, _jspx_th_layout_005fput_005f0, null));
      _jspx_th_layout_005fput_005f0.doTag();
    } finally {
      _jsp_getInstanceManager().destroyInstance(_jspx_th_layout_005fput_005f0);
    }
    return false;
  }

  private boolean _jspx_meth_layout_005fput_005f1(jakarta.servlet.jsp.tagext.JspTag _jspx_parent, jakarta.servlet.jsp.PageContext _jspx_page_context)
          throws java.lang.Throwable {
    jakarta.servlet.jsp.PageContext pageContext = _jspx_page_context;
    jakarta.servlet.jsp.JspWriter out = _jspx_page_context.getOut();
    //  layout:put
    lk.callidora.jsp.inheritance.PutTag _jspx_th_layout_005fput_005f1 = new lk.callidora.jsp.inheritance.PutTag();
    _jsp_getInstanceManager().newInstance(_jspx_th_layout_005fput_005f1);
    try {
      _jspx_th_layout_005fput_005f1.setJspContext(_jspx_page_context);
      _jspx_th_layout_005fput_005f1.setParent(_jspx_parent);
      // /WEB-INF/views/frontend/authorSingle.jsp(8,4) name = block type = null reqTime = true required = true fragment = false deferredValue = false expectedTypeName = null deferredMethod = false methodSignature = null
      _jspx_th_layout_005fput_005f1.setBlock("contents");
      _jspx_th_layout_005fput_005f1.setJspBody(new Helper( 2, _jspx_page_context, _jspx_th_layout_005fput_005f1, null));
      _jspx_th_layout_005fput_005f1.doTag();
    } finally {
      _jsp_getInstanceManager().destroyInstance(_jspx_th_layout_005fput_005f1);
    }
    return false;
  }

  private class Helper
      extends org.apache.jasper.runtime.JspFragmentHelper
  {
    private jakarta.servlet.jsp.tagext.JspTag _jspx_parent;
    private int[] _jspx_push_body_count;

    public Helper( int discriminator, jakarta.servlet.jsp.JspContext jspContext, jakarta.servlet.jsp.tagext.JspTag _jspx_parent, int[] _jspx_push_body_count ) {
      super( discriminator, jspContext, _jspx_parent );
      this._jspx_parent = _jspx_parent;
      this._jspx_push_body_count = _jspx_push_body_count;
    }
    public boolean invoke0( jakarta.servlet.jsp.JspWriter out ) 
      throws java.lang.Throwable
    {
      out.write("\r\n");
      out.write("    ");
      if (_jspx_meth_layout_005fput_005f0(_jspx_parent, _jspx_page_context))
        return true;
      out.write("\r\n");
      out.write("    ");
      if (_jspx_meth_layout_005fput_005f1(_jspx_parent, _jspx_page_context))
        return true;
      out.write('\r');
      out.write('\n');
      return false;
    }
    public boolean invoke1( jakarta.servlet.jsp.JspWriter out ) 
      throws java.lang.Throwable
    {
      out.write("\r\n");
      out.write("        <title>Author | eBookStore</title>\r\n");
      out.write("    ");
      return false;
    }
    public boolean invoke2( jakarta.servlet.jsp.JspWriter out ) 
      throws java.lang.Throwable
    {
      out.write("\r\n");
      out.write("        <main id=\"content\">\r\n");
      out.write("            <div class=\"space-bottom-2 space-bottom-lg-3\">\r\n");
      out.write("                <div class=\"pb-lg-1\">\r\n");
      out.write("                    <div class=\"page-header border-bottom\">\r\n");
      out.write("                        <div class=\"container\">\r\n");
      out.write("                            <div class=\"d-md-flex justify-content-between align-items-center py-4\">\r\n");
      out.write("                                <h1 class=\"page-title font-size-3 font-weight-medium m-0 text-lh-lg\">Authors</h1>\r\n");
      out.write("                                <nav class=\"woocommerce-breadcrumb font-size-2\">\r\n");
      out.write("                                    <a href=\"https://demo2.madrasthemes.com/bookworm-html/redesigned-octo-fiesta/html-demo/home/index.html\"\r\n");
      out.write("                                       class=\"h-primary\">Home</a>\r\n");
      out.write("                                    <span class=\"breadcrumb-separator mx-1\"><i class=\"fas fa-angle-right\"></i></span>\r\n");
      out.write("                                    <span>Authors Single</span>\r\n");
      out.write("                                </nav>\r\n");
      out.write("                            </div>\r\n");
      out.write("                        </div>\r\n");
      out.write("                    </div>\r\n");
      out.write("                    <section class=\"space-bottom-2 space-bottom-lg-3\">\r\n");
      out.write("                        <div class=\"bg-gray-200 space-bottom-2 space-bottom-md-0\">\r\n");
      out.write("                            <div class=\"container space-top-2 space-top-wd-3 px-3\">\r\n");
      out.write("                                <div class=\"row\">\r\n");
      out.write("                                    <div class=\"col-lg-4 col-wd-3 d-flex\">\r\n");
      out.write("                                        <img class=\"img-fluid mb-5 mb-lg-0 mt-auto\" src=\"assets/img/400x759/img1.png\"\r\n");
      out.write("                                             alt=\"Image-Description\">\r\n");
      out.write("                                    </div>\r\n");
      out.write("                                    <div class=\"col-lg-8 col-wd-9\">\r\n");
      out.write("                                        <div class=\"mb-8\">\r\n");
      out.write("                                            <span class=\"text-gray-400 font-size-2\">AUTHOR OF THE MONTH</span>\r\n");
      out.write("                                            <h6 class=\"font-size-7 ont-weight-medium mt-2 mb-3 pb-1\">\r\n");
      out.write("                                                Jessica Simpson\r\n");
      out.write("                                            </h6>\r\n");
      out.write("                                            <p class=\"mb-0\">Lorem ipsum dolor sit amet, consectetur adipiscing elit, sed do\r\n");
      out.write("                                                eiusmod tempor incididunt ut labore et dolore magna aliqua. Ut enim ad minim\r\n");
      out.write("                                                veniam, quis nostrud exercitation ullamco laboris nisi ut aliquip ex ea\r\n");
      out.write("                                                commodo consequat. Duis aute irure dolor in reprehenderit in voluptate velit\r\n");
      out.write("                                                esse cillum dolore eu fugiat nulla pariatur. </p>\r\n");
      out.write("                                        </div>\r\n");
      out.write("                                        <ul class=\"products list-unstyled row no-gutters row-cols-1 row-cols-md-2 row-cols-lg-3 row-cols-wd-4 my-0 mb-md-8 mb-wd-12\">\r\n");
      out.write("                                            <li class=\"product product__no-border col border-0 mb-2 mb-lg-0\">\r\n");
      out.write("                                                <div class=\"product__inner overflow-hidden p-3 p-md-4d875 mx-1 bg-white\">\r\n");
      out.write("                                                    <div class=\"woocommerce-LoopProduct-link woocommerce-loop-product__link d-block position-relative\">\r\n");
      out.write("                                                        <div class=\"woocommerce-loop-product__thumbnail\">\r\n");
      out.write("                                                            <a href=\"..shop/single-product-v5.html\" class=\"d-block\"><img\r\n");
      out.write("                                                                    src=\"assets/img/120x180/img1.jpg\"\r\n");
      out.write("                                                                    class=\"img-fluid d-block mx-auto attachment-shop_catalog size-shop_catalog wp-post-image\"\r\n");
      out.write("                                                                    alt=\"image-description\"></a>\r\n");
      out.write("                                                        </div>\r\n");
      out.write("                                                        <div class=\"woocommerce-loop-product__body product__body pt-3 bg-white\">\r\n");
      out.write("                                                            <div class=\"text-uppercase font-size-1 mb-1 text-truncate\"><a\r\n");
      out.write("                                                                    href=\"..shop/single-product-v5.html\">Paperback</a></div>\r\n");
      out.write("                                                            <h2 class=\"woocommerce-loop-product__title product__title h6 text-lh-md mb-1 text-height-2 crop-text-2 h-dark\">\r\n");
      out.write("                                                                <a href=\"..shop/single-product-v5.html\">Think Like a Monk: Train\r\n");
      out.write("                                                                    Your Mind for Peace and Purpose Everyday</a></h2>\r\n");
      out.write("                                                            <div class=\"font-size-2  mb-1 text-truncate\"><a\r\n");
      out.write("                                                                    href=\"authors-single.html\" class=\"text-gray-700\">Jay\r\n");
      out.write("                                                                Shetty</a></div>\r\n");
      out.write("                                                            <div class=\"price d-flex align-items-center font-weight-medium font-size-3\">\r\n");
      out.write("                                                        <span class=\"woocommerce-Price-amount amount\"><span\r\n");
      out.write("                                                                class=\"woocommerce-Price-currencySymbol\">$</span>29</span>\r\n");
      out.write("                                                            </div>\r\n");
      out.write("                                                        </div>\r\n");
      out.write("                                                        <div class=\"product__hover d-flex align-items-center\">\r\n");
      out.write("                                                            <a href=\"https://demo2.madrasthemes.com/bookworm-html/redesigned-octo-fiesta/html-demo/shop/single-product-v5.html\"\r\n");
      out.write("                                                               class=\"text-uppercase text-dark h-dark font-weight-medium mr-auto\"\r\n");
      out.write("                                                               tabindex=\"0\">\r\n");
      out.write("                                                                <span class=\"product__add-to-cart\">ADD TO CART</span>\r\n");
      out.write("                                                                <span class=\"product__add-to-cart-icon font-size-4\"><i\r\n");
      out.write("                                                                        class=\"flaticon-icon-126515\"></i></span>\r\n");
      out.write("                                                            </a>\r\n");
      out.write("                                                            <a href=\"https://demo2.madrasthemes.com/bookworm-html/redesigned-octo-fiesta/html-demo/shop/single-product-v5.html\"\r\n");
      out.write("                                                               class=\"mr-1 h-p-bg\" tabindex=\"0\">\r\n");
      out.write("                                                                <i class=\"flaticon-switch\"></i>\r\n");
      out.write("                                                            </a>\r\n");
      out.write("                                                            <a href=\"https://demo2.madrasthemes.com/bookworm-html/redesigned-octo-fiesta/html-demo/shop/single-product-v5.html\"\r\n");
      out.write("                                                               class=\"h-p-bg\" tabindex=\"0\">\r\n");
      out.write("                                                                <i class=\"flaticon-heart\"></i>\r\n");
      out.write("                                                            </a>\r\n");
      out.write("                                                        </div>\r\n");
      out.write("                                                    </div>\r\n");
      out.write("                                                </div>\r\n");
      out.write("                                            </li>\r\n");
      out.write("                                            <li class=\"product product__no-border col border-0 mb-2 mb-lg-0\">\r\n");
      out.write("                                                <div class=\"product__inner overflow-hidden p-3 p-md-4d875 mx-1 bg-white\">\r\n");
      out.write("                                                    <div class=\"woocommerce-LoopProduct-link woocommerce-loop-product__link d-block position-relative\">\r\n");
      out.write("                                                        <div class=\"woocommerce-loop-product__thumbnail\">\r\n");
      out.write("                                                            <a href=\"..shop/single-product-v5.html\" class=\"d-block\"><img\r\n");
      out.write("                                                                    src=\"assets/img/120x180/img2.jpg\"\r\n");
      out.write("                                                                    class=\"img-fluid d-block mx-auto attachment-shop_catalog size-shop_catalog wp-post-image\"\r\n");
      out.write("                                                                    alt=\"image-description\"></a>\r\n");
      out.write("                                                        </div>\r\n");
      out.write("                                                        <div class=\"woocommerce-loop-product__body product__body pt-3 bg-white\">\r\n");
      out.write("                                                            <div class=\"text-uppercase font-size-1 mb-1 text-truncate\"><a\r\n");
      out.write("                                                                    href=\"..shop/single-product-v5.html\">Paperback</a></div>\r\n");
      out.write("                                                            <h2 class=\"woocommerce-loop-product__title product__title h6 text-lh-md mb-1 text-height-2 crop-text-2 h-dark\">\r\n");
      out.write("                                                                <a href=\"..shop/single-product-v5.html\">Think Like a Monk: Train\r\n");
      out.write("                                                                    Your Mind for Peace and Purpose Everyday</a></h2>\r\n");
      out.write("                                                            <div class=\"font-size-2  mb-1 text-truncate\"><a\r\n");
      out.write("                                                                    href=\"authors-single.html\" class=\"text-gray-700\">Jay\r\n");
      out.write("                                                                Shetty</a></div>\r\n");
      out.write("                                                            <div class=\"price d-flex align-items-center font-weight-medium font-size-3\">\r\n");
      out.write("                                                        <span class=\"woocommerce-Price-amount amount\"><span\r\n");
      out.write("                                                                class=\"woocommerce-Price-currencySymbol\">$</span>29</span>\r\n");
      out.write("                                                            </div>\r\n");
      out.write("                                                        </div>\r\n");
      out.write("                                                        <div class=\"product__hover d-flex align-items-center\">\r\n");
      out.write("                                                            <a href=\"https://demo2.madrasthemes.com/bookworm-html/redesigned-octo-fiesta/html-demo/shop/single-product-v5.html\"\r\n");
      out.write("                                                               class=\"text-uppercase text-dark h-dark font-weight-medium mr-auto\"\r\n");
      out.write("                                                               tabindex=\"0\">\r\n");
      out.write("                                                                <span class=\"product__add-to-cart\">ADD TO CART</span>\r\n");
      out.write("                                                                <span class=\"product__add-to-cart-icon font-size-4\"><i\r\n");
      out.write("                                                                        class=\"flaticon-icon-126515\"></i></span>\r\n");
      out.write("                                                            </a>\r\n");
      out.write("                                                            <a href=\"https://demo2.madrasthemes.com/bookworm-html/redesigned-octo-fiesta/html-demo/shop/single-product-v5.html\"\r\n");
      out.write("                                                               class=\"mr-1 h-p-bg\" tabindex=\"0\">\r\n");
      out.write("                                                                <i class=\"flaticon-switch\"></i>\r\n");
      out.write("                                                            </a>\r\n");
      out.write("                                                            <a href=\"https://demo2.madrasthemes.com/bookworm-html/redesigned-octo-fiesta/html-demo/shop/single-product-v5.html\"\r\n");
      out.write("                                                               class=\"h-p-bg\" tabindex=\"0\">\r\n");
      out.write("                                                                <i class=\"flaticon-heart\"></i>\r\n");
      out.write("                                                            </a>\r\n");
      out.write("                                                        </div>\r\n");
      out.write("                                                    </div>\r\n");
      out.write("                                                </div>\r\n");
      out.write("                                            </li>\r\n");
      out.write("                                            <li class=\"product product__no-border col border-0 mb-2 mb-lg-0\">\r\n");
      out.write("                                                <div class=\"product__inner overflow-hidden p-3 p-md-4d875 mx-1 bg-white\">\r\n");
      out.write("                                                    <div class=\"woocommerce-LoopProduct-link woocommerce-loop-product__link d-block position-relative\">\r\n");
      out.write("                                                        <div class=\"woocommerce-loop-product__thumbnail\">\r\n");
      out.write("                                                            <a href=\"..shop/single-product-v5.html\" class=\"d-block\"><img\r\n");
      out.write("                                                                    src=\"assets/img/120x180/img3.jpg\"\r\n");
      out.write("                                                                    class=\"img-fluid d-block mx-auto attachment-shop_catalog size-shop_catalog wp-post-image\"\r\n");
      out.write("                                                                    alt=\"image-description\"></a>\r\n");
      out.write("                                                        </div>\r\n");
      out.write("                                                        <div class=\"woocommerce-loop-product__body product__body pt-3 bg-white\">\r\n");
      out.write("                                                            <div class=\"text-uppercase font-size-1 mb-1 text-truncate\"><a\r\n");
      out.write("                                                                    href=\"..shop/single-product-v5.html\">Paperback</a></div>\r\n");
      out.write("                                                            <h2 class=\"woocommerce-loop-product__title product__title h6 text-lh-md mb-1 text-height-2 crop-text-2 h-dark\">\r\n");
      out.write("                                                                <a href=\"..shop/single-product-v5.html\">Think Like a Monk: Train\r\n");
      out.write("                                                                    Your Mind for Peace and Purpose Everyday</a></h2>\r\n");
      out.write("                                                            <div class=\"font-size-2  mb-1 text-truncate\"><a\r\n");
      out.write("                                                                    href=\"authors-single.html\" class=\"text-gray-700\">Jay\r\n");
      out.write("                                                                Shetty</a></div>\r\n");
      out.write("                                                            <div class=\"price d-flex align-items-center font-weight-medium font-size-3\">\r\n");
      out.write("                                                        <span class=\"woocommerce-Price-amount amount\"><span\r\n");
      out.write("                                                                class=\"woocommerce-Price-currencySymbol\">$</span>29</span>\r\n");
      out.write("                                                            </div>\r\n");
      out.write("                                                        </div>\r\n");
      out.write("                                                        <div class=\"product__hover d-flex align-items-center\">\r\n");
      out.write("                                                            <a href=\"https://demo2.madrasthemes.com/bookworm-html/redesigned-octo-fiesta/html-demo/shop/single-product-v5.html\"\r\n");
      out.write("                                                               class=\"text-uppercase text-dark h-dark font-weight-medium mr-auto\"\r\n");
      out.write("                                                               tabindex=\"0\">\r\n");
      out.write("                                                                <span class=\"product__add-to-cart\">ADD TO CART</span>\r\n");
      out.write("                                                                <span class=\"product__add-to-cart-icon font-size-4\"><i\r\n");
      out.write("                                                                        class=\"flaticon-icon-126515\"></i></span>\r\n");
      out.write("                                                            </a>\r\n");
      out.write("                                                            <a href=\"https://demo2.madrasthemes.com/bookworm-html/redesigned-octo-fiesta/html-demo/shop/single-product-v5.html\"\r\n");
      out.write("                                                               class=\"mr-1 h-p-bg\" tabindex=\"0\">\r\n");
      out.write("                                                                <i class=\"flaticon-switch\"></i>\r\n");
      out.write("                                                            </a>\r\n");
      out.write("                                                            <a href=\"https://demo2.madrasthemes.com/bookworm-html/redesigned-octo-fiesta/html-demo/shop/single-product-v5.html\"\r\n");
      out.write("                                                               class=\"h-p-bg\" tabindex=\"0\">\r\n");
      out.write("                                                                <i class=\"flaticon-heart\"></i>\r\n");
      out.write("                                                            </a>\r\n");
      out.write("                                                        </div>\r\n");
      out.write("                                                    </div>\r\n");
      out.write("                                                </div>\r\n");
      out.write("                                            </li>\r\n");
      out.write("                                            <li class=\"d-md-none d-wd-block product product__no-border col border-0 mb-2 mb-lg-0\">\r\n");
      out.write("                                                <div class=\"product__inner overflow-hidden p-3 p-md-4d875 mx-1 bg-white\">\r\n");
      out.write("                                                    <div class=\"woocommerce-LoopProduct-link woocommerce-loop-product__link d-block position-relative\">\r\n");
      out.write("                                                        <div class=\"woocommerce-loop-product__thumbnail\">\r\n");
      out.write("                                                            <a href=\"..shop/single-product-v5.html\" class=\"d-block\"><img\r\n");
      out.write("                                                                    src=\"assets/img/120x180/img4.jpg\"\r\n");
      out.write("                                                                    class=\"img-fluid d-block mx-auto attachment-shop_catalog size-shop_catalog wp-post-image\"\r\n");
      out.write("                                                                    alt=\"image-description\"></a>\r\n");
      out.write("                                                        </div>\r\n");
      out.write("                                                        <div class=\"woocommerce-loop-product__body product__body pt-3 bg-white\">\r\n");
      out.write("                                                            <div class=\"text-uppercase font-size-1 mb-1 text-truncate\"><a\r\n");
      out.write("                                                                    href=\"..shop/single-product-v5.html\">Paperback</a></div>\r\n");
      out.write("                                                            <h2 class=\"woocommerce-loop-product__title product__title h6 text-lh-md mb-1 text-height-2 crop-text-2 h-dark\">\r\n");
      out.write("                                                                <a href=\"..shop/single-product-v5.html\">Think Like a Monk: Train\r\n");
      out.write("                                                                    Your Mind for Peace and Purpose Everyday</a></h2>\r\n");
      out.write("                                                            <div class=\"font-size-2  mb-1 text-truncate\"><a\r\n");
      out.write("                                                                    href=\"authors-single.html\" class=\"text-gray-700\">Jay\r\n");
      out.write("                                                                Shetty</a></div>\r\n");
      out.write("                                                            <div class=\"price d-flex align-items-center font-weight-medium font-size-3\">\r\n");
      out.write("                                                        <span class=\"woocommerce-Price-amount amount\"><span\r\n");
      out.write("                                                                class=\"woocommerce-Price-currencySymbol\">$</span>29</span>\r\n");
      out.write("                                                            </div>\r\n");
      out.write("                                                        </div>\r\n");
      out.write("                                                        <div class=\"product__hover d-flex align-items-center\">\r\n");
      out.write("                                                            <a href=\"https://demo2.madrasthemes.com/bookworm-html/redesigned-octo-fiesta/html-demo/shop/single-product-v5.html\"\r\n");
      out.write("                                                               class=\"text-uppercase text-dark h-dark font-weight-medium mr-auto\"\r\n");
      out.write("                                                               tabindex=\"0\">\r\n");
      out.write("                                                                <span class=\"product__add-to-cart\">ADD TO CART</span>\r\n");
      out.write("                                                                <span class=\"product__add-to-cart-icon font-size-4\"><i\r\n");
      out.write("                                                                        class=\"flaticon-icon-126515\"></i></span>\r\n");
      out.write("                                                            </a>\r\n");
      out.write("                                                            <a href=\"https://demo2.madrasthemes.com/bookworm-html/redesigned-octo-fiesta/html-demo/shop/single-product-v5.html\"\r\n");
      out.write("                                                               class=\"mr-1 h-p-bg\" tabindex=\"0\">\r\n");
      out.write("                                                                <i class=\"flaticon-switch\"></i>\r\n");
      out.write("                                                            </a>\r\n");
      out.write("                                                            <a href=\"https://demo2.madrasthemes.com/bookworm-html/redesigned-octo-fiesta/html-demo/shop/single-product-v5.html\"\r\n");
      out.write("                                                               class=\"h-p-bg\" tabindex=\"0\">\r\n");
      out.write("                                                                <i class=\"flaticon-heart\"></i>\r\n");
      out.write("                                                            </a>\r\n");
      out.write("                                                        </div>\r\n");
      out.write("                                                    </div>\r\n");
      out.write("                                                </div>\r\n");
      out.write("                                            </li>\r\n");
      out.write("                                        </ul>\r\n");
      out.write("                                    </div>\r\n");
      out.write("                                </div>\r\n");
      out.write("                            </div>\r\n");
      out.write("                        </div>\r\n");
      out.write("                    </section>\r\n");
      out.write("                    <div class=\"container\">\r\n");
      out.write("                        <header class=\"mb-5\">\r\n");
      out.write("                            <h2 class=\"font-size-7 mb-0\">Author's Books</h2>\r\n");
      out.write("                        </header>\r\n");
      out.write("                        <ul class=\"js-slick-carousel products list-unstyled my-0 border-right border-top border-left\"\r\n");
      out.write("                            data-arrows-classes=\"d-none d-lg-block u-slick__arrow u-slick__arrow-centered--y\"\r\n");
      out.write("                            data-arrow-left-classes=\"fas flaticon-back u-slick__arrow-inner u-slick__arrow-inner--left ml-lg-n10\"\r\n");
      out.write("                            data-arrow-right-classes=\"fas flaticon-next u-slick__arrow-inner u-slick__arrow-inner--right mr-lg-n10\"\r\n");
      out.write("                            data-slides-show=\"4\" data-responsive=\"[{\r\n");
      out.write("                           &quot;breakpoint&quot;: 992,\r\n");
      out.write("                           &quot;settings&quot;: {\r\n");
      out.write("                             &quot;slidesToShow&quot;: 2\r\n");
      out.write("                           }\r\n");
      out.write("                        }, {\r\n");
      out.write("                           &quot;breakpoint&quot;: 768,\r\n");
      out.write("                           &quot;settings&quot;: {\r\n");
      out.write("                             &quot;slidesToShow&quot;: 1\r\n");
      out.write("                           }\r\n");
      out.write("                        }, {\r\n");
      out.write("                           &quot;breakpoint&quot;: 554,\r\n");
      out.write("                           &quot;settings&quot;: {\r\n");
      out.write("                             &quot;slidesToShow&quot;: 1\r\n");
      out.write("                           }\r\n");
      out.write("                        }]\">\r\n");
      out.write("                            <li class=\"product\">\r\n");
      out.write("                                <div class=\"product__inner overflow-hidden p-4d875\">\r\n");
      out.write("                                    <div class=\"woocommerce-LoopProduct-link woocommerce-loop-product__link d-block position-relative\">\r\n");
      out.write("                                        <div class=\"woocommerce-loop-product__thumbnail\">\r\n");
      out.write("                                            <a href=\"https://demo2.madrasthemes.com/bookworm-html/redesigned-octo-fiesta/html-demo/shop/single-product-v5.html\"\r\n");
      out.write("                                               class=\"d-block\"><img src=\"assets/img/150x226/img1.jpg\"\r\n");
      out.write("                                                                    class=\"d-block mx-auto attachment-shop_catalog size-shop_catalog wp-post-image img-fluid\"\r\n");
      out.write("                                                                    alt=\"image-description\"></a>\r\n");
      out.write("                                        </div>\r\n");
      out.write("                                        <div class=\"woocommerce-loop-product__body product__body pt-3 bg-white\">\r\n");
      out.write("                                            <div class=\"text-uppercase font-size-1 mb-1 text-truncate\"><a\r\n");
      out.write("                                                    href=\"https://demo2.madrasthemes.com/bookworm-html/redesigned-octo-fiesta/html-demo/shop/single-product-v5.html\">Paperback</a>\r\n");
      out.write("                                            </div>\r\n");
      out.write("                                            <h2 class=\"woocommerce-loop-product__title product__title h6 text-lh-md mb-1 text-height-2 crop-text-2 h-dark\">\r\n");
      out.write("                                                <a href=\"https://demo2.madrasthemes.com/bookworm-html/redesigned-octo-fiesta/html-demo/shop/single-product-v5.html\">Think\r\n");
      out.write("                                                    Like a Monk: Train Your Mind for Peace and Purpose Everyday</a></h2>\r\n");
      out.write("                                            <div class=\"font-size-2  mb-1 text-truncate\"><a href=\"authors-single.html\"\r\n");
      out.write("                                                                                            class=\"text-gray-700\">Jay Shetty</a>\r\n");
      out.write("                                            </div>\r\n");
      out.write("                                            <div class=\"price d-flex align-items-center font-weight-medium font-size-3\">\r\n");
      out.write("                                        <span class=\"woocommerce-Price-amount amount\"><span\r\n");
      out.write("                                                class=\"woocommerce-Price-currencySymbol\">$</span>29</span>\r\n");
      out.write("                                            </div>\r\n");
      out.write("                                            <div class=\"product__rating d-flex align-items-center font-size-2\">\r\n");
      out.write("                                                <div class=\"text-yellow-darker mr-2\">\r\n");
      out.write("                                                    <small class=\"fas fa-star\"></small>\r\n");
      out.write("                                                    <small class=\"fas fa-star\"></small>\r\n");
      out.write("                                                    <small class=\"fas fa-star\"></small>\r\n");
      out.write("                                                    <small class=\"far fa-star\"></small>\r\n");
      out.write("                                                    <small class=\"far fa-star\"></small>\r\n");
      out.write("                                                </div>\r\n");
      out.write("                                                <div class>(3,714)</div>\r\n");
      out.write("                                            </div>\r\n");
      out.write("                                        </div>\r\n");
      out.write("                                        <div class=\"product__hover d-flex align-items-center\">\r\n");
      out.write("                                            <a href=\"https://demo2.madrasthemes.com/bookworm-html/redesigned-octo-fiesta/html-demo/shop/single-product-v5.html\"\r\n");
      out.write("                                               class=\"text-uppercase text-dark h-dark font-weight-medium mr-auto\">\r\n");
      out.write("                                                <span class=\"product__add-to-cart\">ADD TO CART</span>\r\n");
      out.write("                                                <span class=\"product__add-to-cart-icon font-size-4\"><i\r\n");
      out.write("                                                        class=\"flaticon-icon-126515\"></i></span>\r\n");
      out.write("                                            </a>\r\n");
      out.write("                                            <a href=\"https://demo2.madrasthemes.com/bookworm-html/redesigned-octo-fiesta/html-demo/shop/single-product-v5.html\"\r\n");
      out.write("                                               class=\"mr-1 h-p-bg border-0 btn btn-outline-primary\">\r\n");
      out.write("                                                <i class=\"flaticon-switch\"></i>\r\n");
      out.write("                                            </a>\r\n");
      out.write("                                            <a href=\"https://demo2.madrasthemes.com/bookworm-html/redesigned-octo-fiesta/html-demo/shop/single-product-v5.html\"\r\n");
      out.write("                                               class=\"h-p-bg border-0 btn btn-outline-primary\">\r\n");
      out.write("                                                <i class=\"flaticon-heart\"></i>\r\n");
      out.write("                                            </a>\r\n");
      out.write("                                        </div>\r\n");
      out.write("                                    </div>\r\n");
      out.write("                                </div>\r\n");
      out.write("                            </li>\r\n");
      out.write("                            <li class=\"product\">\r\n");
      out.write("                                <div class=\"product__inner overflow-hidden p-4d875\">\r\n");
      out.write("                                    <div class=\"woocommerce-LoopProduct-link woocommerce-loop-product__link d-block position-relative\">\r\n");
      out.write("                                        <div class=\"woocommerce-loop-product__thumbnail\">\r\n");
      out.write("                                            <a href=\"https://demo2.madrasthemes.com/bookworm-html/redesigned-octo-fiesta/html-demo/shop/single-product-v5.html\"\r\n");
      out.write("                                               class=\"d-block\"><img src=\"assets/img/150x226/img2.jpg\"\r\n");
      out.write("                                                                    class=\"d-block mx-auto attachment-shop_catalog size-shop_catalog wp-post-image img-fluid\"\r\n");
      out.write("                                                                    alt=\"image-description\"></a>\r\n");
      out.write("                                        </div>\r\n");
      out.write("                                        <div class=\"woocommerce-loop-product__body product__body pt-3 bg-white\">\r\n");
      out.write("                                            <div class=\"text-uppercase font-size-1 mb-1 text-truncate\"><a\r\n");
      out.write("                                                    href=\"https://demo2.madrasthemes.com/bookworm-html/redesigned-octo-fiesta/html-demo/shop/single-product-v5.html\">Kindle\r\n");
      out.write("                                                Edition</a></div>\r\n");
      out.write("                                            <h2 class=\"woocommerce-loop-product__title product__title h6 text-lh-md mb-1 text-height-2 crop-text-2 h-dark\">\r\n");
      out.write("                                                <a href=\"https://demo2.madrasthemes.com/bookworm-html/redesigned-octo-fiesta/html-demo/shop/single-product-v5.html\">The\r\n");
      out.write("                                                    Overdue Life of Amy Byler</a></h2>\r\n");
      out.write("                                            <div class=\"font-size-2  mb-1 text-truncate\"><a href=\"authors-single.html\"\r\n");
      out.write("                                                                                            class=\"text-gray-700\">Kelly\r\n");
      out.write("                                                Harms</a></div>\r\n");
      out.write("                                            <div class=\"price d-flex align-items-center font-weight-medium font-size-3\">\r\n");
      out.write("                                        <span class=\"woocommerce-Price-amount amount\"><span\r\n");
      out.write("                                                class=\"woocommerce-Price-currencySymbol\">$</span>29</span>\r\n");
      out.write("                                            </div>\r\n");
      out.write("                                            <div class=\"product__rating d-flex align-items-center font-size-2\">\r\n");
      out.write("                                                <div class=\"text-yellow-darker mr-2\">\r\n");
      out.write("                                                    <small class=\"fas fa-star\"></small>\r\n");
      out.write("                                                    <small class=\"fas fa-star\"></small>\r\n");
      out.write("                                                    <small class=\"fas fa-star\"></small>\r\n");
      out.write("                                                    <small class=\"far fa-star\"></small>\r\n");
      out.write("                                                    <small class=\"far fa-star\"></small>\r\n");
      out.write("                                                </div>\r\n");
      out.write("                                                <div class>(3,714)</div>\r\n");
      out.write("                                            </div>\r\n");
      out.write("                                        </div>\r\n");
      out.write("                                        <div class=\"product__hover d-flex align-items-center\">\r\n");
      out.write("                                            <a href=\"https://demo2.madrasthemes.com/bookworm-html/redesigned-octo-fiesta/html-demo/shop/single-product-v5.html\"\r\n");
      out.write("                                               class=\"text-uppercase text-dark h-dark font-weight-medium mr-auto\">\r\n");
      out.write("                                                <span class=\"product__add-to-cart\">ADD TO CART</span>\r\n");
      out.write("                                                <span class=\"product__add-to-cart-icon font-size-4\"><i\r\n");
      out.write("                                                        class=\"flaticon-icon-126515\"></i></span>\r\n");
      out.write("                                            </a>\r\n");
      out.write("                                            <a href=\"https://demo2.madrasthemes.com/bookworm-html/redesigned-octo-fiesta/html-demo/shop/single-product-v5.html\"\r\n");
      out.write("                                               class=\"mr-1 h-p-bg border-0 btn btn-outline-primary\">\r\n");
      out.write("                                                <i class=\"flaticon-switch\"></i>\r\n");
      out.write("                                            </a>\r\n");
      out.write("                                            <a href=\"https://demo2.madrasthemes.com/bookworm-html/redesigned-octo-fiesta/html-demo/shop/single-product-v5.html\"\r\n");
      out.write("                                               class=\"h-p-bg border-0 btn btn-outline-primary\">\r\n");
      out.write("                                                <i class=\"flaticon-heart\"></i>\r\n");
      out.write("                                            </a>\r\n");
      out.write("                                        </div>\r\n");
      out.write("                                    </div>\r\n");
      out.write("                                </div>\r\n");
      out.write("                            </li>\r\n");
      out.write("                            <li class=\"product\">\r\n");
      out.write("                                <div class=\"product__inner overflow-hidden p-4d875\">\r\n");
      out.write("                                    <div class=\"woocommerce-LoopProduct-link woocommerce-loop-product__link d-block position-relative\">\r\n");
      out.write("                                        <div class=\"woocommerce-loop-product__thumbnail\">\r\n");
      out.write("                                            <a href=\"https://demo2.madrasthemes.com/bookworm-html/redesigned-octo-fiesta/html-demo/shop/single-product-v5.html\"\r\n");
      out.write("                                               class=\"d-block\"><img src=\"assets/img/150x226/img3.jpg\"\r\n");
      out.write("                                                                    class=\"d-block mx-auto attachment-shop_catalog size-shop_catalog wp-post-image img-fluid\"\r\n");
      out.write("                                                                    alt=\"image-description\"></a>\r\n");
      out.write("                                        </div>\r\n");
      out.write("                                        <div class=\"woocommerce-loop-product__body product__body pt-3 bg-white\">\r\n");
      out.write("                                            <div class=\"text-uppercase font-size-1 mb-1 text-truncate\"><a\r\n");
      out.write("                                                    href=\"https://demo2.madrasthemes.com/bookworm-html/redesigned-octo-fiesta/html-demo/shop/single-product-v5.html\">Paperback</a>\r\n");
      out.write("                                            </div>\r\n");
      out.write("                                            <h2 class=\"woocommerce-loop-product__title product__title h6 text-lh-md mb-1 text-height-2 crop-text-2 h-dark\">\r\n");
      out.write("                                                <a href=\"https://demo2.madrasthemes.com/bookworm-html/redesigned-octo-fiesta/html-demo/shop/single-product-v5.html\">Think\r\n");
      out.write("                                                    Like a Monk: Train Your Mind for Peace and Purpose Everyday</a></h2>\r\n");
      out.write("                                            <div class=\"font-size-2  mb-1 text-truncate\"><a href=\"authors-single.html\"\r\n");
      out.write("                                                                                            class=\"text-gray-700\">Jay Shetty</a>\r\n");
      out.write("                                            </div>\r\n");
      out.write("                                            <div class=\"price d-flex align-items-center font-weight-medium font-size-3\">\r\n");
      out.write("                                        <span class=\"woocommerce-Price-amount amount\"><span\r\n");
      out.write("                                                class=\"woocommerce-Price-currencySymbol\">$</span>29</span>\r\n");
      out.write("                                            </div>\r\n");
      out.write("                                            <div class=\"product__rating d-flex align-items-center font-size-2\">\r\n");
      out.write("                                                <div class=\"text-yellow-darker mr-2\">\r\n");
      out.write("                                                    <small class=\"fas fa-star\"></small>\r\n");
      out.write("                                                    <small class=\"fas fa-star\"></small>\r\n");
      out.write("                                                    <small class=\"fas fa-star\"></small>\r\n");
      out.write("                                                    <small class=\"far fa-star\"></small>\r\n");
      out.write("                                                    <small class=\"far fa-star\"></small>\r\n");
      out.write("                                                </div>\r\n");
      out.write("                                                <div class>(3,714)</div>\r\n");
      out.write("                                            </div>\r\n");
      out.write("                                        </div>\r\n");
      out.write("                                        <div class=\"product__hover d-flex align-items-center\">\r\n");
      out.write("                                            <a href=\"https://demo2.madrasthemes.com/bookworm-html/redesigned-octo-fiesta/html-demo/shop/single-product-v5.html\"\r\n");
      out.write("                                               class=\"text-uppercase text-dark h-dark font-weight-medium mr-auto\">\r\n");
      out.write("                                                <span class=\"product__add-to-cart\">ADD TO CART</span>\r\n");
      out.write("                                                <span class=\"product__add-to-cart-icon font-size-4\"><i\r\n");
      out.write("                                                        class=\"flaticon-icon-126515\"></i></span>\r\n");
      out.write("                                            </a>\r\n");
      out.write("                                            <a href=\"https://demo2.madrasthemes.com/bookworm-html/redesigned-octo-fiesta/html-demo/shop/single-product-v5.html\"\r\n");
      out.write("                                               class=\"mr-1 h-p-bg border-0 btn btn-outline-primary\">\r\n");
      out.write("                                                <i class=\"flaticon-switch\"></i>\r\n");
      out.write("                                            </a>\r\n");
      out.write("                                            <a href=\"https://demo2.madrasthemes.com/bookworm-html/redesigned-octo-fiesta/html-demo/shop/single-product-v5.html\"\r\n");
      out.write("                                               class=\"h-p-bg border-0 btn btn-outline-primary\">\r\n");
      out.write("                                                <i class=\"flaticon-heart\"></i>\r\n");
      out.write("                                            </a>\r\n");
      out.write("                                        </div>\r\n");
      out.write("                                    </div>\r\n");
      out.write("                                </div>\r\n");
      out.write("                            </li>\r\n");
      out.write("                            <li class=\"product\">\r\n");
      out.write("                                <div class=\"product__inner overflow-hidden p-4d875\">\r\n");
      out.write("                                    <div class=\"woocommerce-LoopProduct-link woocommerce-loop-product__link d-block position-relative\">\r\n");
      out.write("                                        <div class=\"woocommerce-loop-product__thumbnail\">\r\n");
      out.write("                                            <a href=\"https://demo2.madrasthemes.com/bookworm-html/redesigned-octo-fiesta/html-demo/shop/single-product-v5.html\"\r\n");
      out.write("                                               class=\"d-block\"><img src=\"assets/img/150x226/img4.jpg\"\r\n");
      out.write("                                                                    class=\"d-block mx-auto attachment-shop_catalog size-shop_catalog wp-post-image img-fluid\"\r\n");
      out.write("                                                                    alt=\"image-description\"></a>\r\n");
      out.write("                                        </div>\r\n");
      out.write("                                        <div class=\"woocommerce-loop-product__body product__body pt-3 bg-white\">\r\n");
      out.write("                                            <div class=\"text-uppercase font-size-1 mb-1 text-truncate\"><a\r\n");
      out.write("                                                    href=\"https://demo2.madrasthemes.com/bookworm-html/redesigned-octo-fiesta/html-demo/shop/single-product-v5.html\">Kindle\r\n");
      out.write("                                                Edition</a></div>\r\n");
      out.write("                                            <h2 class=\"woocommerce-loop-product__title product__title h6 text-lh-md mb-1 text-height-2 crop-text-2 h-dark\">\r\n");
      out.write("                                                <a href=\"https://demo2.madrasthemes.com/bookworm-html/redesigned-octo-fiesta/html-demo/shop/single-product-v5.html\">The\r\n");
      out.write("                                                    Overdue Life of Amy Byler</a></h2>\r\n");
      out.write("                                            <div class=\"font-size-2  mb-1 text-truncate\"><a href=\"authors-single.html\"\r\n");
      out.write("                                                                                            class=\"text-gray-700\">Kelly\r\n");
      out.write("                                                Harms</a></div>\r\n");
      out.write("                                            <div class=\"price d-flex align-items-center font-weight-medium font-size-3\">\r\n");
      out.write("                                        <span class=\"woocommerce-Price-amount amount\"><span\r\n");
      out.write("                                                class=\"woocommerce-Price-currencySymbol\">$</span>29</span>\r\n");
      out.write("                                            </div>\r\n");
      out.write("                                            <div class=\"product__rating d-flex align-items-center font-size-2\">\r\n");
      out.write("                                                <div class=\"text-yellow-darker mr-2\">\r\n");
      out.write("                                                    <small class=\"fas fa-star\"></small>\r\n");
      out.write("                                                    <small class=\"fas fa-star\"></small>\r\n");
      out.write("                                                    <small class=\"fas fa-star\"></small>\r\n");
      out.write("                                                    <small class=\"far fa-star\"></small>\r\n");
      out.write("                                                    <small class=\"far fa-star\"></small>\r\n");
      out.write("                                                </div>\r\n");
      out.write("                                                <div class>(3,714)</div>\r\n");
      out.write("                                            </div>\r\n");
      out.write("                                        </div>\r\n");
      out.write("                                        <div class=\"product__hover d-flex align-items-center\">\r\n");
      out.write("                                            <a href=\"https://demo2.madrasthemes.com/bookworm-html/redesigned-octo-fiesta/html-demo/shop/single-product-v5.html\"\r\n");
      out.write("                                               class=\"text-uppercase text-dark h-dark font-weight-medium mr-auto\">\r\n");
      out.write("                                                <span class=\"product__add-to-cart\">ADD TO CART</span>\r\n");
      out.write("                                                <span class=\"product__add-to-cart-icon font-size-4\"><i\r\n");
      out.write("                                                        class=\"flaticon-icon-126515\"></i></span>\r\n");
      out.write("                                            </a>\r\n");
      out.write("                                            <a href=\"https://demo2.madrasthemes.com/bookworm-html/redesigned-octo-fiesta/html-demo/shop/single-product-v5.html\"\r\n");
      out.write("                                               class=\"mr-1 h-p-bg border-0 btn btn-outline-primary\">\r\n");
      out.write("                                                <i class=\"flaticon-switch\"></i>\r\n");
      out.write("                                            </a>\r\n");
      out.write("                                            <a href=\"https://demo2.madrasthemes.com/bookworm-html/redesigned-octo-fiesta/html-demo/shop/single-product-v5.html\"\r\n");
      out.write("                                               class=\"h-p-bg border-0 btn btn-outline-primary\">\r\n");
      out.write("                                                <i class=\"flaticon-heart\"></i>\r\n");
      out.write("                                            </a>\r\n");
      out.write("                                        </div>\r\n");
      out.write("                                    </div>\r\n");
      out.write("                                </div>\r\n");
      out.write("                            </li>\r\n");
      out.write("                            <li class=\"product\">\r\n");
      out.write("                                <div class=\"product__inner overflow-hidden p-4d875\">\r\n");
      out.write("                                    <div class=\"woocommerce-LoopProduct-link woocommerce-loop-product__link d-block position-relative\">\r\n");
      out.write("                                        <div class=\"woocommerce-loop-product__thumbnail\">\r\n");
      out.write("                                            <a href=\"https://demo2.madrasthemes.com/bookworm-html/redesigned-octo-fiesta/html-demo/shop/single-product-v5.html\"\r\n");
      out.write("                                               class=\"d-block\"><img src=\"assets/img/150x226/img5.jpg\"\r\n");
      out.write("                                                                    class=\"d-block mx-auto attachment-shop_catalog size-shop_catalog wp-post-image img-fluid\"\r\n");
      out.write("                                                                    alt=\"image-description\"></a>\r\n");
      out.write("                                        </div>\r\n");
      out.write("                                        <div class=\"woocommerce-loop-product__body product__body pt-3 bg-white\">\r\n");
      out.write("                                            <div class=\"text-uppercase font-size-1 mb-1 text-truncate\"><a\r\n");
      out.write("                                                    href=\"https://demo2.madrasthemes.com/bookworm-html/redesigned-octo-fiesta/html-demo/shop/single-product-v5.html\">Paperback</a>\r\n");
      out.write("                                            </div>\r\n");
      out.write("                                            <h2 class=\"woocommerce-loop-product__title product__title h6 text-lh-md mb-1 text-height-2 crop-text-2 h-dark\">\r\n");
      out.write("                                                <a href=\"https://demo2.madrasthemes.com/bookworm-html/redesigned-octo-fiesta/html-demo/shop/single-product-v5.html\">Think\r\n");
      out.write("                                                    Like a Monk: Train Your Mind for Peace and Purpose Everyday</a></h2>\r\n");
      out.write("                                            <div class=\"font-size-2  mb-1 text-truncate\"><a href=\"authors-single.html\"\r\n");
      out.write("                                                                                            class=\"text-gray-700\">Jay Shetty</a>\r\n");
      out.write("                                            </div>\r\n");
      out.write("                                            <div class=\"price d-flex align-items-center font-weight-medium font-size-3\">\r\n");
      out.write("                                        <span class=\"woocommerce-Price-amount amount\"><span\r\n");
      out.write("                                                class=\"woocommerce-Price-currencySymbol\">$</span>29</span>\r\n");
      out.write("                                            </div>\r\n");
      out.write("                                            <div class=\"product__rating d-flex align-items-center font-size-2\">\r\n");
      out.write("                                                <div class=\"text-yellow-darker mr-2\">\r\n");
      out.write("                                                    <small class=\"fas fa-star\"></small>\r\n");
      out.write("                                                    <small class=\"fas fa-star\"></small>\r\n");
      out.write("                                                    <small class=\"fas fa-star\"></small>\r\n");
      out.write("                                                    <small class=\"far fa-star\"></small>\r\n");
      out.write("                                                    <small class=\"far fa-star\"></small>\r\n");
      out.write("                                                </div>\r\n");
      out.write("                                                <div class>(3,714)</div>\r\n");
      out.write("                                            </div>\r\n");
      out.write("                                        </div>\r\n");
      out.write("                                        <div class=\"product__hover d-flex align-items-center\">\r\n");
      out.write("                                            <a href=\"https://demo2.madrasthemes.com/bookworm-html/redesigned-octo-fiesta/html-demo/shop/single-product-v5.html\"\r\n");
      out.write("                                               class=\"text-uppercase text-dark h-dark font-weight-medium mr-auto\">\r\n");
      out.write("                                                <span class=\"product__add-to-cart\">ADD TO CART</span>\r\n");
      out.write("                                                <span class=\"product__add-to-cart-icon font-size-4\"><i\r\n");
      out.write("                                                        class=\"flaticon-icon-126515\"></i></span>\r\n");
      out.write("                                            </a>\r\n");
      out.write("                                            <a href=\"https://demo2.madrasthemes.com/bookworm-html/redesigned-octo-fiesta/html-demo/shop/single-product-v5.html\"\r\n");
      out.write("                                               class=\"mr-1 h-p-bg border-0 btn btn-outline-primary\">\r\n");
      out.write("                                                <i class=\"flaticon-switch\"></i>\r\n");
      out.write("                                            </a>\r\n");
      out.write("                                            <a href=\"https://demo2.madrasthemes.com/bookworm-html/redesigned-octo-fiesta/html-demo/shop/single-product-v5.html\"\r\n");
      out.write("                                               class=\"h-p-bg border-0 btn btn-outline-primary\">\r\n");
      out.write("                                                <i class=\"flaticon-heart\"></i>\r\n");
      out.write("                                            </a>\r\n");
      out.write("                                        </div>\r\n");
      out.write("                                    </div>\r\n");
      out.write("                                </div>\r\n");
      out.write("                            </li>\r\n");
      out.write("                            <li class=\"product\">\r\n");
      out.write("                                <div class=\"product__inner overflow-hidden p-4d875\">\r\n");
      out.write("                                    <div class=\"woocommerce-LoopProduct-link woocommerce-loop-product__link d-block position-relative\">\r\n");
      out.write("                                        <div class=\"woocommerce-loop-product__thumbnail\">\r\n");
      out.write("                                            <a href=\"https://demo2.madrasthemes.com/bookworm-html/redesigned-octo-fiesta/html-demo/shop/single-product-v5.html\"\r\n");
      out.write("                                               class=\"d-block\"><img src=\"assets/img/150x226/img6.jpg\"\r\n");
      out.write("                                                                    class=\"d-block mx-auto attachment-shop_catalog size-shop_catalog wp-post-image img-fluid\"\r\n");
      out.write("                                                                    alt=\"image-description\"></a>\r\n");
      out.write("                                        </div>\r\n");
      out.write("                                        <div class=\"woocommerce-loop-product__body product__body pt-3 bg-white\">\r\n");
      out.write("                                            <div class=\"text-uppercase font-size-1 mb-1 text-truncate\"><a\r\n");
      out.write("                                                    href=\"https://demo2.madrasthemes.com/bookworm-html/redesigned-octo-fiesta/html-demo/shop/single-product-v5.html\">Kindle\r\n");
      out.write("                                                Edition</a></div>\r\n");
      out.write("                                            <h2 class=\"woocommerce-loop-product__title product__title h6 text-lh-md mb-1 text-height-2 crop-text-2 h-dark\">\r\n");
      out.write("                                                <a href=\"https://demo2.madrasthemes.com/bookworm-html/redesigned-octo-fiesta/html-demo/shop/single-product-v5.html\">The\r\n");
      out.write("                                                    Overdue Life of Amy Byler</a></h2>\r\n");
      out.write("                                            <div class=\"font-size-2  mb-1 text-truncate\"><a href=\"authors-single.html\"\r\n");
      out.write("                                                                                            class=\"text-gray-700\">Kelly\r\n");
      out.write("                                                Harms</a></div>\r\n");
      out.write("                                            <div class=\"price d-flex align-items-center font-weight-medium font-size-3\">\r\n");
      out.write("                                        <span class=\"woocommerce-Price-amount amount\"><span\r\n");
      out.write("                                                class=\"woocommerce-Price-currencySymbol\">$</span>29</span>\r\n");
      out.write("                                            </div>\r\n");
      out.write("                                            <div class=\"product__rating d-flex align-items-center font-size-2\">\r\n");
      out.write("                                                <div class=\"text-yellow-darker mr-2\">\r\n");
      out.write("                                                    <small class=\"fas fa-star\"></small>\r\n");
      out.write("                                                    <small class=\"fas fa-star\"></small>\r\n");
      out.write("                                                    <small class=\"fas fa-star\"></small>\r\n");
      out.write("                                                    <small class=\"far fa-star\"></small>\r\n");
      out.write("                                                    <small class=\"far fa-star\"></small>\r\n");
      out.write("                                                </div>\r\n");
      out.write("                                                <div class>(3,714)</div>\r\n");
      out.write("                                            </div>\r\n");
      out.write("                                        </div>\r\n");
      out.write("                                        <div class=\"product__hover d-flex align-items-center\">\r\n");
      out.write("                                            <a href=\"https://demo2.madrasthemes.com/bookworm-html/redesigned-octo-fiesta/html-demo/shop/single-product-v5.html\"\r\n");
      out.write("                                               class=\"text-uppercase text-dark h-dark font-weight-medium mr-auto\">\r\n");
      out.write("                                                <span class=\"product__add-to-cart\">ADD TO CART</span>\r\n");
      out.write("                                                <span class=\"product__add-to-cart-icon font-size-4\"><i\r\n");
      out.write("                                                        class=\"flaticon-icon-126515\"></i></span>\r\n");
      out.write("                                            </a>\r\n");
      out.write("                                            <a href=\"https://demo2.madrasthemes.com/bookworm-html/redesigned-octo-fiesta/html-demo/shop/single-product-v5.html\"\r\n");
      out.write("                                               class=\"mr-1 h-p-bg border-0 btn btn-outline-primary\">\r\n");
      out.write("                                                <i class=\"flaticon-switch\"></i>\r\n");
      out.write("                                            </a>\r\n");
      out.write("                                            <a href=\"https://demo2.madrasthemes.com/bookworm-html/redesigned-octo-fiesta/html-demo/shop/single-product-v5.html\"\r\n");
      out.write("                                               class=\"h-p-bg border-0 btn btn-outline-primary\">\r\n");
      out.write("                                                <i class=\"flaticon-heart\"></i>\r\n");
      out.write("                                            </a>\r\n");
      out.write("                                        </div>\r\n");
      out.write("                                    </div>\r\n");
      out.write("                                </div>\r\n");
      out.write("                            </li>\r\n");
      out.write("                            <li class=\"product\">\r\n");
      out.write("                                <div class=\"product__inner overflow-hidden p-4d875\">\r\n");
      out.write("                                    <div class=\"woocommerce-LoopProduct-link woocommerce-loop-product__link d-block position-relative\">\r\n");
      out.write("                                        <div class=\"woocommerce-loop-product__thumbnail\">\r\n");
      out.write("                                            <a href=\"https://demo2.madrasthemes.com/bookworm-html/redesigned-octo-fiesta/html-demo/shop/single-product-v5.html\"\r\n");
      out.write("                                               class=\"d-block\"><img src=\"assets/img/150x226/img7.jpg\"\r\n");
      out.write("                                                                    class=\"d-block mx-auto attachment-shop_catalog size-shop_catalog wp-post-image img-fluid\"\r\n");
      out.write("                                                                    alt=\"image-description\"></a>\r\n");
      out.write("                                        </div>\r\n");
      out.write("                                        <div class=\"woocommerce-loop-product__body product__body pt-3 bg-white\">\r\n");
      out.write("                                            <div class=\"text-uppercase font-size-1 mb-1 text-truncate\"><a\r\n");
      out.write("                                                    href=\"https://demo2.madrasthemes.com/bookworm-html/redesigned-octo-fiesta/html-demo/shop/single-product-v5.html\">Paperback</a>\r\n");
      out.write("                                            </div>\r\n");
      out.write("                                            <h2 class=\"woocommerce-loop-product__title product__title h6 text-lh-md mb-1 text-height-2 crop-text-2 h-dark\">\r\n");
      out.write("                                                <a href=\"https://demo2.madrasthemes.com/bookworm-html/redesigned-octo-fiesta/html-demo/shop/single-product-v5.html\">Think\r\n");
      out.write("                                                    Like a Monk: Train Your Mind for Peace and Purpose Everyday</a></h2>\r\n");
      out.write("                                            <div class=\"font-size-2  mb-1 text-truncate\"><a href=\"authors-single.html\"\r\n");
      out.write("                                                                                            class=\"text-gray-700\">Jay Shetty</a>\r\n");
      out.write("                                            </div>\r\n");
      out.write("                                            <div class=\"price d-flex align-items-center font-weight-medium font-size-3\">\r\n");
      out.write("                                        <span class=\"woocommerce-Price-amount amount\"><span\r\n");
      out.write("                                                class=\"woocommerce-Price-currencySymbol\">$</span>29</span>\r\n");
      out.write("                                            </div>\r\n");
      out.write("                                            <div class=\"product__rating d-flex align-items-center font-size-2\">\r\n");
      out.write("                                                <div class=\"text-yellow-darker mr-2\">\r\n");
      out.write("                                                    <small class=\"fas fa-star\"></small>\r\n");
      out.write("                                                    <small class=\"fas fa-star\"></small>\r\n");
      out.write("                                                    <small class=\"fas fa-star\"></small>\r\n");
      out.write("                                                    <small class=\"far fa-star\"></small>\r\n");
      out.write("                                                    <small class=\"far fa-star\"></small>\r\n");
      out.write("                                                </div>\r\n");
      out.write("                                                <div class>(3,714)</div>\r\n");
      out.write("                                            </div>\r\n");
      out.write("                                        </div>\r\n");
      out.write("                                        <div class=\"product__hover d-flex align-items-center\">\r\n");
      out.write("                                            <a href=\"https://demo2.madrasthemes.com/bookworm-html/redesigned-octo-fiesta/html-demo/shop/single-product-v5.html\"\r\n");
      out.write("                                               class=\"text-uppercase text-dark h-dark font-weight-medium mr-auto\">\r\n");
      out.write("                                                <span class=\"product__add-to-cart\">ADD TO CART</span>\r\n");
      out.write("                                                <span class=\"product__add-to-cart-icon font-size-4\"><i\r\n");
      out.write("                                                        class=\"flaticon-icon-126515\"></i></span>\r\n");
      out.write("                                            </a>\r\n");
      out.write("                                            <a href=\"https://demo2.madrasthemes.com/bookworm-html/redesigned-octo-fiesta/html-demo/shop/single-product-v5.html\"\r\n");
      out.write("                                               class=\"mr-1 h-p-bg border-0 btn btn-outline-primary\">\r\n");
      out.write("                                                <i class=\"flaticon-switch\"></i>\r\n");
      out.write("                                            </a>\r\n");
      out.write("                                            <a href=\"https://demo2.madrasthemes.com/bookworm-html/redesigned-octo-fiesta/html-demo/shop/single-product-v5.html\"\r\n");
      out.write("                                               class=\"h-p-bg border-0 btn btn-outline-primary\">\r\n");
      out.write("                                                <i class=\"flaticon-heart\"></i>\r\n");
      out.write("                                            </a>\r\n");
      out.write("                                        </div>\r\n");
      out.write("                                    </div>\r\n");
      out.write("                                </div>\r\n");
      out.write("                            </li>\r\n");
      out.write("                            <li class=\"product\">\r\n");
      out.write("                                <div class=\"product__inner overflow-hidden p-4d875\">\r\n");
      out.write("                                    <div class=\"woocommerce-LoopProduct-link woocommerce-loop-product__link d-block position-relative\">\r\n");
      out.write("                                        <div class=\"woocommerce-loop-product__thumbnail\">\r\n");
      out.write("                                            <a href=\"https://demo2.madrasthemes.com/bookworm-html/redesigned-octo-fiesta/html-demo/shop/single-product-v5.html\"\r\n");
      out.write("                                               class=\"d-block\"><img src=\"assets/img/150x226/img8.jpg\"\r\n");
      out.write("                                                                    class=\"d-block mx-auto attachment-shop_catalog size-shop_catalog wp-post-image img-fluid\"\r\n");
      out.write("                                                                    alt=\"image-description\"></a>\r\n");
      out.write("                                        </div>\r\n");
      out.write("                                        <div class=\"woocommerce-loop-product__body product__body pt-3 bg-white\">\r\n");
      out.write("                                            <div class=\"text-uppercase font-size-1 mb-1 text-truncate\"><a\r\n");
      out.write("                                                    href=\"https://demo2.madrasthemes.com/bookworm-html/redesigned-octo-fiesta/html-demo/shop/single-product-v5.html\">Kindle\r\n");
      out.write("                                                Edition</a></div>\r\n");
      out.write("                                            <h2 class=\"woocommerce-loop-product__title product__title h6 text-lh-md mb-1 text-height-2 crop-text-2 h-dark\">\r\n");
      out.write("                                                <a href=\"https://demo2.madrasthemes.com/bookworm-html/redesigned-octo-fiesta/html-demo/shop/single-product-v5.html\">The\r\n");
      out.write("                                                    Overdue Life of Amy Byler</a></h2>\r\n");
      out.write("                                            <div class=\"font-size-2  mb-1 text-truncate\"><a href=\"authors-single.html\"\r\n");
      out.write("                                                                                            class=\"text-gray-700\">Kelly\r\n");
      out.write("                                                Harms</a></div>\r\n");
      out.write("                                            <div class=\"price d-flex align-items-center font-weight-medium font-size-3\">\r\n");
      out.write("                                        <span class=\"woocommerce-Price-amount amount\"><span\r\n");
      out.write("                                                class=\"woocommerce-Price-currencySymbol\">$</span>29</span>\r\n");
      out.write("                                            </div>\r\n");
      out.write("                                            <div class=\"product__rating d-flex align-items-center font-size-2\">\r\n");
      out.write("                                                <div class=\"text-yellow-darker mr-2\">\r\n");
      out.write("                                                    <small class=\"fas fa-star\"></small>\r\n");
      out.write("                                                    <small class=\"fas fa-star\"></small>\r\n");
      out.write("                                                    <small class=\"fas fa-star\"></small>\r\n");
      out.write("                                                    <small class=\"far fa-star\"></small>\r\n");
      out.write("                                                    <small class=\"far fa-star\"></small>\r\n");
      out.write("                                                </div>\r\n");
      out.write("                                                <div class>(3,714)</div>\r\n");
      out.write("                                            </div>\r\n");
      out.write("                                        </div>\r\n");
      out.write("                                        <div class=\"product__hover d-flex align-items-center\">\r\n");
      out.write("                                            <a href=\"https://demo2.madrasthemes.com/bookworm-html/redesigned-octo-fiesta/html-demo/shop/single-product-v5.html\"\r\n");
      out.write("                                               class=\"text-uppercase text-dark h-dark font-weight-medium mr-auto\">\r\n");
      out.write("                                                <span class=\"product__add-to-cart\">ADD TO CART</span>\r\n");
      out.write("                                                <span class=\"product__add-to-cart-icon font-size-4\"><i\r\n");
      out.write("                                                        class=\"flaticon-icon-126515\"></i></span>\r\n");
      out.write("                                            </a>\r\n");
      out.write("                                            <a href=\"https://demo2.madrasthemes.com/bookworm-html/redesigned-octo-fiesta/html-demo/shop/single-product-v5.html\"\r\n");
      out.write("                                               class=\"mr-1 h-p-bg border-0 btn btn-outline-primary\">\r\n");
      out.write("                                                <i class=\"flaticon-switch\"></i>\r\n");
      out.write("                                            </a>\r\n");
      out.write("                                            <a href=\"https://demo2.madrasthemes.com/bookworm-html/redesigned-octo-fiesta/html-demo/shop/single-product-v5.html\"\r\n");
      out.write("                                               class=\"h-p-bg border-0 btn btn-outline-primary\">\r\n");
      out.write("                                                <i class=\"flaticon-heart\"></i>\r\n");
      out.write("                                            </a>\r\n");
      out.write("                                        </div>\r\n");
      out.write("                                    </div>\r\n");
      out.write("                                </div>\r\n");
      out.write("                            </li>\r\n");
      out.write("                        </ul>\r\n");
      out.write("                    </div>\r\n");
      out.write("                </div>\r\n");
      out.write("            </div>\r\n");
      out.write("        </main>\r\n");
      out.write("    ");
      return false;
    }
    public void invoke( java.io.Writer writer )
      throws jakarta.servlet.jsp.JspException
    {
      jakarta.servlet.jsp.JspWriter out = null;
      if( writer != null ) {
        out = this.jspContext.pushBody(writer);
      } else {
        out = this.jspContext.getOut();
      }
      try {
        Object _jspx_saved_JspContext = this.jspContext.getELContext().getContext(jakarta.servlet.jsp.JspContext.class);
        this.jspContext.getELContext().putContext(jakarta.servlet.jsp.JspContext.class,this.jspContext);
        switch( this.discriminator ) {
          case 0:
            invoke0( out );
            break;
          case 1:
            invoke1( out );
            break;
          case 2:
            invoke2( out );
            break;
        }
        jspContext.getELContext().putContext(jakarta.servlet.jsp.JspContext.class,_jspx_saved_JspContext);
      }
      catch( java.lang.Throwable e ) {
        if (e instanceof jakarta.servlet.jsp.SkipPageException)
            throw (jakarta.servlet.jsp.SkipPageException) e;
        throw new jakarta.servlet.jsp.JspException( e );
      }
      finally {
        if( writer != null ) {
          this.jspContext.popBody();
        }
      }
    }
  }
}
