/*
 * Generated by the Jasper component of Apache Tomcat
 * Version: Apache Tomcat/10.1.7
 * Generated at: 2023-08-29 11:23:09 UTC
 * Note: The last modified time of this file was set to
 *       the last modified time of the source file after
 *       generation to assist with modification tracking.
 */
package org.apache.jsp.WEB_002dINF.views.frontend;

import jakarta.servlet.*;
import jakarta.servlet.http.*;
import jakarta.servlet.jsp.*;

public final class authorList_jsp extends org.apache.jasper.runtime.HttpJspBase
    implements org.apache.jasper.runtime.JspSourceDependent,
                 org.apache.jasper.runtime.JspSourceImports,
                 org.apache.jasper.runtime.JspSourceDirectives {

  private static final jakarta.servlet.jsp.JspFactory _jspxFactory =
          jakarta.servlet.jsp.JspFactory.getDefaultFactory();

  private static java.util.Map<java.lang.String,java.lang.Long> _jspx_dependants;

  static {
    _jspx_dependants = new java.util.HashMap<java.lang.String,java.lang.Long>(2);
    _jspx_dependants.put("file:/C:/Users/Jasir/.m2/repository/lk/callidora/jsp/jsp-template-inheritance/1.0.1/jsp-template-inheritance-1.0.1.jar", Long.valueOf(1692244300354L));
    _jspx_dependants.put("jar:file:/C:/Users/Jasir/.m2/repository/lk/callidora/jsp/jsp-template-inheritance/1.0.1/jsp-template-inheritance-1.0.1.jar!/META-INF/jsp-inheritance.tld", Long.valueOf(1692219220000L));
  }

  private static final java.util.Set<java.lang.String> _jspx_imports_packages;

  private static final java.util.Set<java.lang.String> _jspx_imports_classes;

  static {
    _jspx_imports_packages = new java.util.HashSet<>();
    _jspx_imports_packages.add("jakarta.servlet");
    _jspx_imports_packages.add("jakarta.servlet.http");
    _jspx_imports_packages.add("jakarta.servlet.jsp");
    _jspx_imports_classes = null;
  }

  private volatile jakarta.el.ExpressionFactory _el_expressionfactory;
  private volatile org.apache.tomcat.InstanceManager _jsp_instancemanager;

  public java.util.Map<java.lang.String,java.lang.Long> getDependants() {
    return _jspx_dependants;
  }

  public java.util.Set<java.lang.String> getPackageImports() {
    return _jspx_imports_packages;
  }

  public java.util.Set<java.lang.String> getClassImports() {
    return _jspx_imports_classes;
  }

  public boolean getErrorOnELNotFound() {
    return false;
  }

  public jakarta.el.ExpressionFactory _jsp_getExpressionFactory() {
    if (_el_expressionfactory == null) {
      synchronized (this) {
        if (_el_expressionfactory == null) {
          _el_expressionfactory = _jspxFactory.getJspApplicationContext(getServletConfig().getServletContext()).getExpressionFactory();
        }
      }
    }
    return _el_expressionfactory;
  }

  public org.apache.tomcat.InstanceManager _jsp_getInstanceManager() {
    if (_jsp_instancemanager == null) {
      synchronized (this) {
        if (_jsp_instancemanager == null) {
          _jsp_instancemanager = org.apache.jasper.runtime.InstanceManagerFactory.getInstanceManager(getServletConfig());
        }
      }
    }
    return _jsp_instancemanager;
  }

  public void _jspInit() {
  }

  public void _jspDestroy() {
  }

  public void _jspService(final jakarta.servlet.http.HttpServletRequest request, final jakarta.servlet.http.HttpServletResponse response)
      throws java.io.IOException, jakarta.servlet.ServletException {

    if (!jakarta.servlet.DispatcherType.ERROR.equals(request.getDispatcherType())) {
      final java.lang.String _jspx_method = request.getMethod();
      if ("OPTIONS".equals(_jspx_method)) {
        response.setHeader("Allow","GET, HEAD, POST, OPTIONS");
        return;
      }
      if (!"GET".equals(_jspx_method) && !"POST".equals(_jspx_method) && !"HEAD".equals(_jspx_method)) {
        response.setHeader("Allow","GET, HEAD, POST, OPTIONS");
        response.sendError(HttpServletResponse.SC_METHOD_NOT_ALLOWED, "JSPs only permit GET, POST or HEAD. Jasper also permits OPTIONS");
        return;
      }
    }

    final jakarta.servlet.jsp.PageContext pageContext;
    jakarta.servlet.http.HttpSession session = null;
    final jakarta.servlet.ServletContext application;
    final jakarta.servlet.ServletConfig config;
    jakarta.servlet.jsp.JspWriter out = null;
    final java.lang.Object page = this;
    jakarta.servlet.jsp.JspWriter _jspx_out = null;
    jakarta.servlet.jsp.PageContext _jspx_page_context = null;


    try {
      response.setContentType("text/html;charset=UTF-8");
      pageContext = _jspxFactory.getPageContext(this, request, response,
      			null, true, 8192, true);
      _jspx_page_context = pageContext;
      application = pageContext.getServletContext();
      config = pageContext.getServletConfig();
      session = pageContext.getSession();
      out = pageContext.getOut();
      _jspx_out = out;

      out.write("\r\n");
      out.write("\r\n");
      out.write("\r\n");
      if (_jspx_meth_layout_005fextends_005f0(_jspx_page_context))
        return;
      out.write('\r');
      out.write('\n');
    } catch (java.lang.Throwable t) {
      if (!(t instanceof jakarta.servlet.jsp.SkipPageException)){
        out = _jspx_out;
        if (out != null && out.getBufferSize() != 0)
          try {
            if (response.isCommitted()) {
              out.flush();
            } else {
              out.clearBuffer();
            }
          } catch (java.io.IOException e) {}
        if (_jspx_page_context != null) _jspx_page_context.handlePageException(t);
        else throw new ServletException(t);
      }
    } finally {
      _jspxFactory.releasePageContext(_jspx_page_context);
    }
  }

  private boolean _jspx_meth_layout_005fextends_005f0(jakarta.servlet.jsp.PageContext _jspx_page_context)
          throws java.lang.Throwable {
    jakarta.servlet.jsp.PageContext pageContext = _jspx_page_context;
    jakarta.servlet.jsp.JspWriter out = _jspx_page_context.getOut();
    //  layout:extends
    lk.callidora.jsp.inheritance.ExtendsTag _jspx_th_layout_005fextends_005f0 = new lk.callidora.jsp.inheritance.ExtendsTag();
    _jsp_getInstanceManager().newInstance(_jspx_th_layout_005fextends_005f0);
    try {
      _jspx_th_layout_005fextends_005f0.setJspContext(_jspx_page_context);
      // /WEB-INF/views/frontend/authorList.jsp(4,0) name = name type = null reqTime = true required = true fragment = false deferredValue = false expectedTypeName = null deferredMethod = false methodSignature = null
      _jspx_th_layout_005fextends_005f0.setName("base");
      _jspx_th_layout_005fextends_005f0.setJspBody(new Helper( 0, _jspx_page_context, _jspx_th_layout_005fextends_005f0, null));
      _jspx_th_layout_005fextends_005f0.doTag();
    } finally {
      _jsp_getInstanceManager().destroyInstance(_jspx_th_layout_005fextends_005f0);
    }
    return false;
  }

  private boolean _jspx_meth_layout_005fput_005f0(jakarta.servlet.jsp.tagext.JspTag _jspx_parent, jakarta.servlet.jsp.PageContext _jspx_page_context)
          throws java.lang.Throwable {
    jakarta.servlet.jsp.PageContext pageContext = _jspx_page_context;
    jakarta.servlet.jsp.JspWriter out = _jspx_page_context.getOut();
    //  layout:put
    lk.callidora.jsp.inheritance.PutTag _jspx_th_layout_005fput_005f0 = new lk.callidora.jsp.inheritance.PutTag();
    _jsp_getInstanceManager().newInstance(_jspx_th_layout_005fput_005f0);
    try {
      _jspx_th_layout_005fput_005f0.setJspContext(_jspx_page_context);
      _jspx_th_layout_005fput_005f0.setParent(_jspx_parent);
      // /WEB-INF/views/frontend/authorList.jsp(5,4) name = block type = null reqTime = true required = true fragment = false deferredValue = false expectedTypeName = null deferredMethod = false methodSignature = null
      _jspx_th_layout_005fput_005f0.setBlock("title");
      _jspx_th_layout_005fput_005f0.setJspBody(new Helper( 1, _jspx_page_context, _jspx_th_layout_005fput_005f0, null));
      _jspx_th_layout_005fput_005f0.doTag();
    } finally {
      _jsp_getInstanceManager().destroyInstance(_jspx_th_layout_005fput_005f0);
    }
    return false;
  }

  private boolean _jspx_meth_layout_005fput_005f1(jakarta.servlet.jsp.tagext.JspTag _jspx_parent, jakarta.servlet.jsp.PageContext _jspx_page_context)
          throws java.lang.Throwable {
    jakarta.servlet.jsp.PageContext pageContext = _jspx_page_context;
    jakarta.servlet.jsp.JspWriter out = _jspx_page_context.getOut();
    //  layout:put
    lk.callidora.jsp.inheritance.PutTag _jspx_th_layout_005fput_005f1 = new lk.callidora.jsp.inheritance.PutTag();
    _jsp_getInstanceManager().newInstance(_jspx_th_layout_005fput_005f1);
    try {
      _jspx_th_layout_005fput_005f1.setJspContext(_jspx_page_context);
      _jspx_th_layout_005fput_005f1.setParent(_jspx_parent);
      // /WEB-INF/views/frontend/authorList.jsp(8,4) name = block type = null reqTime = true required = true fragment = false deferredValue = false expectedTypeName = null deferredMethod = false methodSignature = null
      _jspx_th_layout_005fput_005f1.setBlock("contents");
      _jspx_th_layout_005fput_005f1.setJspBody(new Helper( 2, _jspx_page_context, _jspx_th_layout_005fput_005f1, null));
      _jspx_th_layout_005fput_005f1.doTag();
    } finally {
      _jsp_getInstanceManager().destroyInstance(_jspx_th_layout_005fput_005f1);
    }
    return false;
  }

  private class Helper
      extends org.apache.jasper.runtime.JspFragmentHelper
  {
    private jakarta.servlet.jsp.tagext.JspTag _jspx_parent;
    private int[] _jspx_push_body_count;

    public Helper( int discriminator, jakarta.servlet.jsp.JspContext jspContext, jakarta.servlet.jsp.tagext.JspTag _jspx_parent, int[] _jspx_push_body_count ) {
      super( discriminator, jspContext, _jspx_parent );
      this._jspx_parent = _jspx_parent;
      this._jspx_push_body_count = _jspx_push_body_count;
    }
    public boolean invoke0( jakarta.servlet.jsp.JspWriter out ) 
      throws java.lang.Throwable
    {
      out.write("\r\n");
      out.write("    ");
      if (_jspx_meth_layout_005fput_005f0(_jspx_parent, _jspx_page_context))
        return true;
      out.write("\r\n");
      out.write("    ");
      if (_jspx_meth_layout_005fput_005f1(_jspx_parent, _jspx_page_context))
        return true;
      out.write('\r');
      out.write('\n');
      return false;
    }
    public boolean invoke1( jakarta.servlet.jsp.JspWriter out ) 
      throws java.lang.Throwable
    {
      out.write("\r\n");
      out.write("        <title>Author List | eBookStore</title>\r\n");
      out.write("    ");
      return false;
    }
    public boolean invoke2( jakarta.servlet.jsp.JspWriter out ) 
      throws java.lang.Throwable
    {
      out.write("\r\n");
      out.write("\r\n");
      out.write("        <main id=\"content\">\r\n");
      out.write("            <div class=\"space-bottom-2 space-bottom-lg-3\">\r\n");
      out.write("                <div class=\"pb-lg-1\">\r\n");
      out.write("                    <div class=\"page-header border-bottom\">\r\n");
      out.write("                        <div class=\"container\">\r\n");
      out.write("                            <div class=\"d-md-flex justify-content-between align-items-center py-4\">\r\n");
      out.write("                                <h1 class=\"page-title font-size-3 font-weight-medium m-0 text-lh-lg\">Authors</h1>\r\n");
      out.write("                                <nav class=\"woocommerce-breadcrumb font-size-2\">\r\n");
      out.write("                                    <a href=\"https://demo2.madrasthemes.com/bookworm-html/redesigned-octo-fiesta/html-demo/home/index.html\"\r\n");
      out.write("                                       class=\"h-primary\">Home</a>\r\n");
      out.write("                                    <span class=\"breadcrumb-separator mx-1\"><i class=\"fas fa-angle-right\"></i></span>\r\n");
      out.write("                                    <span>Authors</span>\r\n");
      out.write("                                </nav>\r\n");
      out.write("                            </div>\r\n");
      out.write("                        </div>\r\n");
      out.write("                    </div>\r\n");
      out.write("                    <div class=\"container\">\r\n");
      out.write("                        <div class=\"u-cubeportfolio mb-5 mb-lg-7\">\r\n");
      out.write("\r\n");
      out.write("                            <ul id=\"filterControls\"\r\n");
      out.write("                                class=\"d-flex justify-content-between list-inline cbp-l-filters-alignRight cbp-l-filters-alignRight__custom text-left pl-lg-8 pt-4 pt-lg-8 mb-5 mb-lg-8 overflow-auto\">\r\n");
      out.write("                                <li class=\"list-inline-item bg-white text-secondary-gray-700 px-2 px-md-0 font-size-2 border-0 cbp-filter-item m-0 cbp-filter-item-active u-cubeportfolio__item\"\r\n");
      out.write("                                    data-filter=\"*\">All\r\n");
      out.write("                                </li>\r\n");
      out.write("                                <li class=\"list-inline-item bg-white text-secondary-gray-700 px-2 px-md-0 font-size-2 border-0 cbp-filter-item m-0 u-cubeportfolio__item\"\r\n");
      out.write("                                    data-filter=\".branding\">A\r\n");
      out.write("                                </li>\r\n");
      out.write("                                <li class=\"list-inline-item bg-white text-secondary-gray-700 px-2 px-md-0 font-size-2 border-0 cbp-filter-item m-0 u-cubeportfolio__item\"\r\n");
      out.write("                                    data-filter=\".abstract\">B\r\n");
      out.write("                                </li>\r\n");
      out.write("                                <li class=\"list-inline-item bg-white text-secondary-gray-700 px-2 px-md-0 font-size-2 border-0 cbp-filter-item m-0 u-cubeportfolio__item\"\r\n");
      out.write("                                    data-filter=\".graphic\">C\r\n");
      out.write("                                </li>\r\n");
      out.write("                                <li class=\"list-inline-item bg-white text-secondary-gray-700 px-2 px-md-0 font-size-2 border-0 cbp-filter-item m-0 u-cubeportfolio__item\"\r\n");
      out.write("                                    data-filter=\".illustration\">D\r\n");
      out.write("                                </li>\r\n");
      out.write("                                <li class=\"list-inline-item bg-white text-secondary-gray-700 px-2 px-md-0 font-size-2 border-0 cbp-filter-item m-0 u-cubeportfolio__item\"\r\n");
      out.write("                                    data-filter=\".branding\">E\r\n");
      out.write("                                </li>\r\n");
      out.write("                                <li class=\"list-inline-item bg-white text-secondary-gray-700 px-2 px-md-0 font-size-2 border-0 cbp-filter-item m-0 u-cubeportfolio__item\"\r\n");
      out.write("                                    data-filter=\".abstract\">F\r\n");
      out.write("                                </li>\r\n");
      out.write("                                <li class=\"list-inline-item bg-white text-secondary-gray-700 px-2 px-md-0 font-size-2 border-0 cbp-filter-item m-0 u-cubeportfolio__item\"\r\n");
      out.write("                                    data-filter=\".graphic\">G\r\n");
      out.write("                                </li>\r\n");
      out.write("                                <li class=\"list-inline-item bg-white text-secondary-gray-700 px-2 px-md-0 font-size-2 border-0 cbp-filter-item m-0 u-cubeportfolio__item\"\r\n");
      out.write("                                    data-filter=\".illustration\">H\r\n");
      out.write("                                </li>\r\n");
      out.write("                                <li class=\"list-inline-item bg-white text-secondary-gray-700 px-2 px-md-0 font-size-2 border-0 cbp-filter-item m-0 u-cubeportfolio__item\"\r\n");
      out.write("                                    data-filter=\".branding\">I\r\n");
      out.write("                                </li>\r\n");
      out.write("                                <li class=\"list-inline-item bg-white text-secondary-gray-700 px-2 px-md-0 font-size-2 border-0 cbp-filter-item m-0 u-cubeportfolio__item\"\r\n");
      out.write("                                    data-filter=\".abstract\">J\r\n");
      out.write("                                </li>\r\n");
      out.write("                                <li class=\"list-inline-item bg-white text-secondary-gray-700 px-2 px-md-0 font-size-2 border-0 cbp-filter-item m-0 u-cubeportfolio__item\"\r\n");
      out.write("                                    data-filter=\".graphic\">K\r\n");
      out.write("                                </li>\r\n");
      out.write("                                <li class=\"list-inline-item bg-white text-secondary-gray-700 px-2 px-md-0 font-size-2 border-0 cbp-filter-item m-0 u-cubeportfolio__item\"\r\n");
      out.write("                                    data-filter=\".illustration\">L\r\n");
      out.write("                                </li>\r\n");
      out.write("                                <li class=\"list-inline-item bg-white text-secondary-gray-700 px-2 px-md-0 font-size-2 border-0 cbp-filter-item m-0 u-cubeportfolio__item\"\r\n");
      out.write("                                    data-filter=\".branding\">M\r\n");
      out.write("                                </li>\r\n");
      out.write("                                <li class=\"list-inline-item bg-white text-secondary-gray-700 px-2 px-md-0 font-size-2 border-0 cbp-filter-item m-0 u-cubeportfolio__item\"\r\n");
      out.write("                                    data-filter=\".abstract\">N\r\n");
      out.write("                                </li>\r\n");
      out.write("                                <li class=\"list-inline-item bg-white text-secondary-gray-700 px-2 px-md-0 font-size-2 border-0 cbp-filter-item m-0 u-cubeportfolio__item\"\r\n");
      out.write("                                    data-filter=\".graphic\">O\r\n");
      out.write("                                </li>\r\n");
      out.write("                                <li class=\"list-inline-item bg-white text-secondary-gray-700 px-2 px-md-0 font-size-2 border-0 cbp-filter-item m-0 u-cubeportfolio__item\"\r\n");
      out.write("                                    data-filter=\".illustration\">P\r\n");
      out.write("                                </li>\r\n");
      out.write("                                <li class=\"list-inline-item bg-white text-secondary-gray-700 px-2 px-md-0 font-size-2 border-0 cbp-filter-item m-0 u-cubeportfolio__item\"\r\n");
      out.write("                                    data-filter=\".branding\">Q\r\n");
      out.write("                                </li>\r\n");
      out.write("                                <li class=\"list-inline-item bg-white text-secondary-gray-700 px-2 px-md-0 font-size-2 border-0 cbp-filter-item m-0 u-cubeportfolio__item\"\r\n");
      out.write("                                    data-filter=\".abstract\">R\r\n");
      out.write("                                </li>\r\n");
      out.write("                                <li class=\"list-inline-item bg-white text-secondary-gray-700 px-2 px-md-0 font-size-2 border-0 cbp-filter-item m-0 u-cubeportfolio__item\"\r\n");
      out.write("                                    data-filter=\".graphic\">S\r\n");
      out.write("                                </li>\r\n");
      out.write("                                <li class=\"list-inline-item bg-white text-secondary-gray-700 px-2 px-md-0 font-size-2 border-0 cbp-filter-item m-0 u-cubeportfolio__item\"\r\n");
      out.write("                                    data-filter=\".illustration\">T\r\n");
      out.write("                                </li>\r\n");
      out.write("                                <li class=\"list-inline-item bg-white text-secondary-gray-700 px-2 px-md-0 font-size-2 border-0 cbp-filter-item m-0 u-cubeportfolio__item\"\r\n");
      out.write("                                    data-filter=\".branding\">U\r\n");
      out.write("                                </li>\r\n");
      out.write("                                <li class=\"list-inline-item bg-white text-secondary-gray-700 px-2 px-md-0 font-size-2 border-0 cbp-filter-item m-0 u-cubeportfolio__item\"\r\n");
      out.write("                                    data-filter=\".abstract\">V\r\n");
      out.write("                                </li>\r\n");
      out.write("                                <li class=\"list-inline-item bg-white text-secondary-gray-700 px-2 px-md-0 font-size-2 border-0 cbp-filter-item m-0 u-cubeportfolio__item\"\r\n");
      out.write("                                    data-filter=\".graphic\">W\r\n");
      out.write("                                </li>\r\n");
      out.write("                                <li class=\"list-inline-item bg-white text-secondary-gray-700 px-2 px-md-0 font-size-2 border-0 cbp-filter-item m-0 u-cubeportfolio__item\"\r\n");
      out.write("                                    data-filter=\".illustration\">X\r\n");
      out.write("                                </li>\r\n");
      out.write("                                <li class=\"list-inline-item bg-white text-secondary-gray-700 px-2 px-md-0 font-size-2 border-0 cbp-filter-item m-0 u-cubeportfolio__item\"\r\n");
      out.write("                                    data-filter=\".branding\">Y\r\n");
      out.write("                                </li>\r\n");
      out.write("                                <li class=\"list-inline-item bg-white text-secondary-gray-700 px-2 px-md-0 font-size-2 border-0 cbp-filter-item m-0 u-cubeportfolio__item\"\r\n");
      out.write("                                    data-filter=\".abstract\">Z\r\n");
      out.write("                                </li>\r\n");
      out.write("                            </ul>\r\n");
      out.write("\r\n");
      out.write("\r\n");
      out.write("                            <div class=\"cbp\" data-layout=\"grid\" data-controls=\"#filterControls\" data-animation=\"quicksand\"\r\n");
      out.write("                                 data-x-gap=\"20\" data-y-gap=\"100\" data-media-queries=\"[\r\n");
      out.write("                            {&quot;width&quot;: 1100, &quot;cols&quot;: 5},\r\n");
      out.write("                            {&quot;width&quot;: 800, &quot;cols&quot;: 3},\r\n");
      out.write("                            {&quot;width&quot;: 480, &quot;cols&quot;: 1}\r\n");
      out.write("                          ]\">\r\n");
      out.write("\r\n");
      out.write("                                <div class=\"cbp-item graphic\">\r\n");
      out.write("                                    <a class=\"cbp-caption\" href=\"authors-single.html\">\r\n");
      out.write("                                        <img class=\"rounded-circle img-fluid mb-3\" src=\"assets/img/140x140/img1.jpg\"\r\n");
      out.write("                                             alt=\"Image Description\">\r\n");
      out.write("                                        <div class=\"py-3 text-center\">\r\n");
      out.write("                                            <h4 class=\"h6 text-dark\">Barbara O'Neal</h4>\r\n");
      out.write("                                            <span class=\"font-size-2 text-secondary-gray-700\">21,658 Published Books</span>\r\n");
      out.write("                                        </div>\r\n");
      out.write("                                    </a>\r\n");
      out.write("                                </div>\r\n");
      out.write("\r\n");
      out.write("\r\n");
      out.write("                                <div class=\"cbp-item branding\">\r\n");
      out.write("                                    <a class=\"cbp-caption\" href=\"authors-single.html\">\r\n");
      out.write("                                        <img class=\"rounded-circle img-fluid mb-3\" src=\"assets/img/140x140/img2.jpg\"\r\n");
      out.write("                                             alt=\"Image Description\">\r\n");
      out.write("                                        <div class=\"py-3 text-center\">\r\n");
      out.write("                                            <h4 class=\"h6 text-dark\">Stephen King</h4>\r\n");
      out.write("                                            <span class=\"font-size-2 text-secondary-gray-700\">21,658 Published Books</span>\r\n");
      out.write("                                        </div>\r\n");
      out.write("                                    </a>\r\n");
      out.write("                                </div>\r\n");
      out.write("\r\n");
      out.write("\r\n");
      out.write("                                <div class=\"cbp-item branding\">\r\n");
      out.write("                                    <a class=\"cbp-caption\" href=\"authors-single.html\">\r\n");
      out.write("                                        <img class=\"rounded-circle img-fluid mb-3\" src=\"assets/img/140x140/img3.jpg\"\r\n");
      out.write("                                             alt=\"Image Description\">\r\n");
      out.write("                                        <div class=\"py-3 text-center\">\r\n");
      out.write("                                            <h4 class=\"h6 text-dark\">David Williams</h4>\r\n");
      out.write("                                            <span class=\"font-size-2 text-secondary-gray-700\">21,658 Published Books</span>\r\n");
      out.write("                                        </div>\r\n");
      out.write("                                    </a>\r\n");
      out.write("                                </div>\r\n");
      out.write("\r\n");
      out.write("\r\n");
      out.write("                                <div class=\"cbp-item branding\">\r\n");
      out.write("                                    <a class=\"cbp-caption\" href=\"authors-single.html\">\r\n");
      out.write("                                        <img class=\"rounded-circle img-fluid mb-3\" src=\"assets/img/140x140/img4.jpg\"\r\n");
      out.write("                                             alt=\"Image Description\">\r\n");
      out.write("                                        <div class=\"py-3 text-center\">\r\n");
      out.write("                                            <h4 class=\"h6 text-dark\">Joe Wicks</h4>\r\n");
      out.write("                                            <span class=\"font-size-2 text-secondary-gray-700\">21,658 Published Books</span>\r\n");
      out.write("                                        </div>\r\n");
      out.write("                                    </a>\r\n");
      out.write("                                </div>\r\n");
      out.write("\r\n");
      out.write("\r\n");
      out.write("                                <div class=\"cbp-item branding\">\r\n");
      out.write("                                    <a class=\"cbp-caption\" href=\"authors-single.html\">\r\n");
      out.write("                                        <img class=\"rounded-circle img-fluid mb-3\" src=\"assets/img/140x140/img5.jpg\"\r\n");
      out.write("                                             alt=\"Image Description\">\r\n");
      out.write("                                        <div class=\"py-3 text-center\">\r\n");
      out.write("                                            <h4 class=\"h6 text-dark\">Jessica Simpson</h4>\r\n");
      out.write("                                            <span class=\"font-size-2 text-secondary-gray-700\">21,658 Published Books</span>\r\n");
      out.write("                                        </div>\r\n");
      out.write("                                    </a>\r\n");
      out.write("                                </div>\r\n");
      out.write("\r\n");
      out.write("\r\n");
      out.write("                                <div class=\"cbp-item abstract graphic\">\r\n");
      out.write("                                    <a class=\"cbp-caption\" href=\"authors-single.html\">\r\n");
      out.write("                                        <img class=\"rounded-circle img-fluid mb-3\" src=\"assets/img/140x140/img6.jpg\"\r\n");
      out.write("                                             alt=\"Image Description\">\r\n");
      out.write("                                        <div class=\"py-3 text-center\">\r\n");
      out.write("                                            <h4 class=\"h6 text-dark\">Barbara O'Neal</h4>\r\n");
      out.write("                                            <span class=\"font-size-2 text-secondary-gray-700\">21,658 Published Books</span>\r\n");
      out.write("                                        </div>\r\n");
      out.write("                                    </a>\r\n");
      out.write("                                </div>\r\n");
      out.write("\r\n");
      out.write("\r\n");
      out.write("                                <div class=\"cbp-item abstract graphic\">\r\n");
      out.write("                                    <a class=\"cbp-caption\" href=\"authors-single.html\">\r\n");
      out.write("                                        <img class=\"rounded-circle img-fluid mb-3\" src=\"assets/img/140x140/img7.jpg\"\r\n");
      out.write("                                             alt=\"Image Description\">\r\n");
      out.write("                                        <div class=\"py-3 text-center\">\r\n");
      out.write("                                            <h4 class=\"h6 text-dark\">Stephen King</h4>\r\n");
      out.write("                                            <span class=\"font-size-2 text-secondary-gray-700\">21,658 Published Books</span>\r\n");
      out.write("                                        </div>\r\n");
      out.write("                                    </a>\r\n");
      out.write("                                </div>\r\n");
      out.write("\r\n");
      out.write("\r\n");
      out.write("                                <div class=\"cbp-item abstract graphic\">\r\n");
      out.write("                                    <a class=\"cbp-caption\" href=\"authors-single.html\">\r\n");
      out.write("                                        <img class=\"rounded-circle img-fluid mb-3\" src=\"assets/img/140x140/img8.jpg\"\r\n");
      out.write("                                             alt=\"Image Description\">\r\n");
      out.write("                                        <div class=\"py-3 text-center\">\r\n");
      out.write("                                            <h4 class=\"h6 text-dark\">David Williams</h4>\r\n");
      out.write("                                            <span class=\"font-size-2 text-secondary-gray-700\">21,658 Published Books</span>\r\n");
      out.write("                                        </div>\r\n");
      out.write("                                    </a>\r\n");
      out.write("                                </div>\r\n");
      out.write("\r\n");
      out.write("\r\n");
      out.write("                                <div class=\"cbp-item abstract graphic\">\r\n");
      out.write("                                    <a class=\"cbp-caption\" href=\"authors-single.html\">\r\n");
      out.write("                                        <img class=\"rounded-circle img-fluid mb-3\" src=\"assets/img/140x140/img9.jpg\"\r\n");
      out.write("                                             alt=\"Image Description\">\r\n");
      out.write("                                        <div class=\"py-3 text-center\">\r\n");
      out.write("                                            <h4 class=\"h6 text-dark\">Joe Wicks</h4>\r\n");
      out.write("                                            <span class=\"font-size-2 text-secondary-gray-700\">21,658 Published Books</span>\r\n");
      out.write("                                        </div>\r\n");
      out.write("                                    </a>\r\n");
      out.write("                                </div>\r\n");
      out.write("\r\n");
      out.write("\r\n");
      out.write("                                <div class=\"cbp-item illustration abstract\">\r\n");
      out.write("                                    <a class=\"cbp-caption\" href=\"authors-single.html\">\r\n");
      out.write("                                        <img class=\"rounded-circle img-fluid mb-3\" src=\"assets/img/140x140/img10.jpg\"\r\n");
      out.write("                                             alt=\"Image Description\">\r\n");
      out.write("                                        <div class=\"py-3 text-center\">\r\n");
      out.write("                                            <h4 class=\"h6 text-dark\">Jessica Simpson</h4>\r\n");
      out.write("                                            <span class=\"font-size-2 text-secondary-gray-700\">21,658 Published Books</span>\r\n");
      out.write("                                        </div>\r\n");
      out.write("                                    </a>\r\n");
      out.write("                                </div>\r\n");
      out.write("\r\n");
      out.write("\r\n");
      out.write("                                <div class=\"cbp-item illustration branding\">\r\n");
      out.write("                                    <a class=\"cbp-caption\" href=\"authors-single.html\">\r\n");
      out.write("                                        <img class=\"rounded-circle img-fluid mb-3\" src=\"assets/img/140x140/img11.jpg\"\r\n");
      out.write("                                             alt=\"Image Description\">\r\n");
      out.write("                                        <div class=\"py-3 text-center\">\r\n");
      out.write("                                            <h4 class=\"h6 text-dark\">Barbara O'Neal</h4>\r\n");
      out.write("                                            <span class=\"font-size-2 text-secondary-gray-700\">21,658 Published Books</span>\r\n");
      out.write("                                        </div>\r\n");
      out.write("                                    </a>\r\n");
      out.write("                                </div>\r\n");
      out.write("\r\n");
      out.write("\r\n");
      out.write("                                <div class=\"cbp-item illustration branding\">\r\n");
      out.write("                                    <a class=\"cbp-caption\" href=\"authors-single.html\">\r\n");
      out.write("                                        <img class=\"rounded-circle img-fluid mb-3\" src=\"assets/img/140x140/img12.jpg\"\r\n");
      out.write("                                             alt=\"Image Description\">\r\n");
      out.write("                                        <div class=\"py-3 text-center\">\r\n");
      out.write("                                            <h4 class=\"h6 text-dark\">Stephen King</h4>\r\n");
      out.write("                                            <span class=\"font-size-2 text-secondary-gray-700\">21,658 Published Books</span>\r\n");
      out.write("                                        </div>\r\n");
      out.write("                                    </a>\r\n");
      out.write("                                </div>\r\n");
      out.write("\r\n");
      out.write("\r\n");
      out.write("                                <div class=\"cbp-item illustration branding\">\r\n");
      out.write("                                    <a class=\"cbp-caption\" href=\"authors-single.html\">\r\n");
      out.write("                                        <img class=\"rounded-circle img-fluid mb-3\" src=\"assets/img/140x140/img13.jpg\"\r\n");
      out.write("                                             alt=\"Image Description\">\r\n");
      out.write("                                        <div class=\"py-3 text-center\">\r\n");
      out.write("                                            <h4 class=\"h6 text-dark\">David Williams</h4>\r\n");
      out.write("                                            <span class=\"font-size-2 text-secondary-gray-700\">21,658 Published Books</span>\r\n");
      out.write("                                        </div>\r\n");
      out.write("                                    </a>\r\n");
      out.write("                                </div>\r\n");
      out.write("\r\n");
      out.write("\r\n");
      out.write("                                <div class=\"cbp-item illustration branding\">\r\n");
      out.write("                                    <a class=\"cbp-caption\" href=\"authors-single.html\">\r\n");
      out.write("                                        <img class=\"rounded-circle img-fluid mb-3\" src=\"assets/img/140x140/img14.jpg\"\r\n");
      out.write("                                             alt=\"Image Description\">\r\n");
      out.write("                                        <div class=\"py-3 text-center\">\r\n");
      out.write("                                            <h4 class=\"h6 text-dark\">Joe Wicks</h4>\r\n");
      out.write("                                            <span class=\"font-size-2 text-secondary-gray-700\">21,658 Published Books</span>\r\n");
      out.write("                                        </div>\r\n");
      out.write("                                    </a>\r\n");
      out.write("                                </div>\r\n");
      out.write("\r\n");
      out.write("\r\n");
      out.write("                                <div class=\"cbp-item illustration branding\">\r\n");
      out.write("                                    <a class=\"cbp-caption\" href=\"authors-single.html\">\r\n");
      out.write("                                        <img class=\"rounded-circle img-fluid mb-3\" src=\"assets/img/140x140/img15.jpg\"\r\n");
      out.write("                                             alt=\"Image Description\">\r\n");
      out.write("                                        <div class=\"py-3 text-center\">\r\n");
      out.write("                                            <h4 class=\"h6 text-dark\">Jessica Simpson</h4>\r\n");
      out.write("                                            <span class=\"font-size-2 text-secondary-gray-700\">21,658 Published Books</span>\r\n");
      out.write("                                        </div>\r\n");
      out.write("                                    </a>\r\n");
      out.write("                                </div>\r\n");
      out.write("\r\n");
      out.write("                            </div>\r\n");
      out.write("\r\n");
      out.write("                        </div>\r\n");
      out.write("                        <div class=\"d-flex justify-content-center\">\r\n");
      out.write("                            <button type=\"submit\" class=\"btn btn-wide border-dark text-dark rounded-0 transition-3d-hover\">Load\r\n");
      out.write("                                More\r\n");
      out.write("                            </button>\r\n");
      out.write("                        </div>\r\n");
      out.write("                    </div>\r\n");
      out.write("                </div>\r\n");
      out.write("            </div>\r\n");
      out.write("        </main>\r\n");
      out.write("\r\n");
      out.write("    ");
      return false;
    }
    public void invoke( java.io.Writer writer )
      throws jakarta.servlet.jsp.JspException
    {
      jakarta.servlet.jsp.JspWriter out = null;
      if( writer != null ) {
        out = this.jspContext.pushBody(writer);
      } else {
        out = this.jspContext.getOut();
      }
      try {
        Object _jspx_saved_JspContext = this.jspContext.getELContext().getContext(jakarta.servlet.jsp.JspContext.class);
        this.jspContext.getELContext().putContext(jakarta.servlet.jsp.JspContext.class,this.jspContext);
        switch( this.discriminator ) {
          case 0:
            invoke0( out );
            break;
          case 1:
            invoke1( out );
            break;
          case 2:
            invoke2( out );
            break;
        }
        jspContext.getELContext().putContext(jakarta.servlet.jsp.JspContext.class,_jspx_saved_JspContext);
      }
      catch( java.lang.Throwable e ) {
        if (e instanceof jakarta.servlet.jsp.SkipPageException)
            throw (jakarta.servlet.jsp.SkipPageException) e;
        throw new jakarta.servlet.jsp.JspException( e );
      }
      finally {
        if( writer != null ) {
          this.jspContext.popBody();
        }
      }
    }
  }
}
