/*
 * Generated by the Jasper component of Apache Tomcat
 * Version: Apache Tomcat/10.1.7
 * Generated at: 2023-08-29 07:22:45 UTC
 * Note: The last modified time of this file was set to
 *       the last modified time of the source file after
 *       generation to assist with modification tracking.
 */
package org.apache.jsp.WEB_002dINF.views.frontend;

import jakarta.servlet.*;
import jakarta.servlet.http.*;
import jakarta.servlet.jsp.*;

public final class cart_jsp extends org.apache.jasper.runtime.HttpJspBase
    implements org.apache.jasper.runtime.JspSourceDependent,
                 org.apache.jasper.runtime.JspSourceImports,
                 org.apache.jasper.runtime.JspSourceDirectives {

  private static final jakarta.servlet.jsp.JspFactory _jspxFactory =
          jakarta.servlet.jsp.JspFactory.getDefaultFactory();

  private static java.util.Map<java.lang.String,java.lang.Long> _jspx_dependants;

  static {
    _jspx_dependants = new java.util.HashMap<java.lang.String,java.lang.Long>(2);
    _jspx_dependants.put("file:/C:/Users/Jasir/.m2/repository/lk/callidora/jsp/jsp-template-inheritance/1.0.1/jsp-template-inheritance-1.0.1.jar", Long.valueOf(1692244300354L));
    _jspx_dependants.put("jar:file:/C:/Users/Jasir/.m2/repository/lk/callidora/jsp/jsp-template-inheritance/1.0.1/jsp-template-inheritance-1.0.1.jar!/META-INF/jsp-inheritance.tld", Long.valueOf(1692219220000L));
  }

  private static final java.util.Set<java.lang.String> _jspx_imports_packages;

  private static final java.util.Set<java.lang.String> _jspx_imports_classes;

  static {
    _jspx_imports_packages = new java.util.HashSet<>();
    _jspx_imports_packages.add("jakarta.servlet");
    _jspx_imports_packages.add("jakarta.servlet.http");
    _jspx_imports_packages.add("jakarta.servlet.jsp");
    _jspx_imports_classes = null;
  }

  private volatile jakarta.el.ExpressionFactory _el_expressionfactory;
  private volatile org.apache.tomcat.InstanceManager _jsp_instancemanager;

  public java.util.Map<java.lang.String,java.lang.Long> getDependants() {
    return _jspx_dependants;
  }

  public java.util.Set<java.lang.String> getPackageImports() {
    return _jspx_imports_packages;
  }

  public java.util.Set<java.lang.String> getClassImports() {
    return _jspx_imports_classes;
  }

  public boolean getErrorOnELNotFound() {
    return false;
  }

  public jakarta.el.ExpressionFactory _jsp_getExpressionFactory() {
    if (_el_expressionfactory == null) {
      synchronized (this) {
        if (_el_expressionfactory == null) {
          _el_expressionfactory = _jspxFactory.getJspApplicationContext(getServletConfig().getServletContext()).getExpressionFactory();
        }
      }
    }
    return _el_expressionfactory;
  }

  public org.apache.tomcat.InstanceManager _jsp_getInstanceManager() {
    if (_jsp_instancemanager == null) {
      synchronized (this) {
        if (_jsp_instancemanager == null) {
          _jsp_instancemanager = org.apache.jasper.runtime.InstanceManagerFactory.getInstanceManager(getServletConfig());
        }
      }
    }
    return _jsp_instancemanager;
  }

  public void _jspInit() {
  }

  public void _jspDestroy() {
  }

  public void _jspService(final jakarta.servlet.http.HttpServletRequest request, final jakarta.servlet.http.HttpServletResponse response)
      throws java.io.IOException, jakarta.servlet.ServletException {

    if (!jakarta.servlet.DispatcherType.ERROR.equals(request.getDispatcherType())) {
      final java.lang.String _jspx_method = request.getMethod();
      if ("OPTIONS".equals(_jspx_method)) {
        response.setHeader("Allow","GET, HEAD, POST, OPTIONS");
        return;
      }
      if (!"GET".equals(_jspx_method) && !"POST".equals(_jspx_method) && !"HEAD".equals(_jspx_method)) {
        response.setHeader("Allow","GET, HEAD, POST, OPTIONS");
        response.sendError(HttpServletResponse.SC_METHOD_NOT_ALLOWED, "JSPs only permit GET, POST or HEAD. Jasper also permits OPTIONS");
        return;
      }
    }

    final jakarta.servlet.jsp.PageContext pageContext;
    jakarta.servlet.http.HttpSession session = null;
    final jakarta.servlet.ServletContext application;
    final jakarta.servlet.ServletConfig config;
    jakarta.servlet.jsp.JspWriter out = null;
    final java.lang.Object page = this;
    jakarta.servlet.jsp.JspWriter _jspx_out = null;
    jakarta.servlet.jsp.PageContext _jspx_page_context = null;


    try {
      response.setContentType("text/html;charset=UTF-8");
      pageContext = _jspxFactory.getPageContext(this, request, response,
      			null, true, 8192, true);
      _jspx_page_context = pageContext;
      application = pageContext.getServletContext();
      config = pageContext.getServletConfig();
      session = pageContext.getSession();
      out = pageContext.getOut();
      _jspx_out = out;

      out.write("\r\n");
      out.write("\r\n");
      out.write("\r\n");
      if (_jspx_meth_layout_005fextends_005f0(_jspx_page_context))
        return;
    } catch (java.lang.Throwable t) {
      if (!(t instanceof jakarta.servlet.jsp.SkipPageException)){
        out = _jspx_out;
        if (out != null && out.getBufferSize() != 0)
          try {
            if (response.isCommitted()) {
              out.flush();
            } else {
              out.clearBuffer();
            }
          } catch (java.io.IOException e) {}
        if (_jspx_page_context != null) _jspx_page_context.handlePageException(t);
        else throw new ServletException(t);
      }
    } finally {
      _jspxFactory.releasePageContext(_jspx_page_context);
    }
  }

  private boolean _jspx_meth_layout_005fextends_005f0(jakarta.servlet.jsp.PageContext _jspx_page_context)
          throws java.lang.Throwable {
    jakarta.servlet.jsp.PageContext pageContext = _jspx_page_context;
    jakarta.servlet.jsp.JspWriter out = _jspx_page_context.getOut();
    //  layout:extends
    lk.callidora.jsp.inheritance.ExtendsTag _jspx_th_layout_005fextends_005f0 = new lk.callidora.jsp.inheritance.ExtendsTag();
    _jsp_getInstanceManager().newInstance(_jspx_th_layout_005fextends_005f0);
    try {
      _jspx_th_layout_005fextends_005f0.setJspContext(_jspx_page_context);
      // /WEB-INF/views/frontend/cart.jsp(4,0) name = name type = null reqTime = true required = true fragment = false deferredValue = false expectedTypeName = null deferredMethod = false methodSignature = null
      _jspx_th_layout_005fextends_005f0.setName("base");
      _jspx_th_layout_005fextends_005f0.setJspBody(new Helper( 0, _jspx_page_context, _jspx_th_layout_005fextends_005f0, null));
      _jspx_th_layout_005fextends_005f0.doTag();
    } finally {
      _jsp_getInstanceManager().destroyInstance(_jspx_th_layout_005fextends_005f0);
    }
    return false;
  }

  private boolean _jspx_meth_layout_005fput_005f0(jakarta.servlet.jsp.tagext.JspTag _jspx_parent, jakarta.servlet.jsp.PageContext _jspx_page_context)
          throws java.lang.Throwable {
    jakarta.servlet.jsp.PageContext pageContext = _jspx_page_context;
    jakarta.servlet.jsp.JspWriter out = _jspx_page_context.getOut();
    //  layout:put
    lk.callidora.jsp.inheritance.PutTag _jspx_th_layout_005fput_005f0 = new lk.callidora.jsp.inheritance.PutTag();
    _jsp_getInstanceManager().newInstance(_jspx_th_layout_005fput_005f0);
    try {
      _jspx_th_layout_005fput_005f0.setJspContext(_jspx_page_context);
      _jspx_th_layout_005fput_005f0.setParent(_jspx_parent);
      // /WEB-INF/views/frontend/cart.jsp(5,4) name = block type = null reqTime = true required = true fragment = false deferredValue = false expectedTypeName = null deferredMethod = false methodSignature = null
      _jspx_th_layout_005fput_005f0.setBlock("title");
      _jspx_th_layout_005fput_005f0.setJspBody(new Helper( 1, _jspx_page_context, _jspx_th_layout_005fput_005f0, null));
      _jspx_th_layout_005fput_005f0.doTag();
    } finally {
      _jsp_getInstanceManager().destroyInstance(_jspx_th_layout_005fput_005f0);
    }
    return false;
  }

  private boolean _jspx_meth_layout_005fput_005f1(jakarta.servlet.jsp.tagext.JspTag _jspx_parent, jakarta.servlet.jsp.PageContext _jspx_page_context)
          throws java.lang.Throwable {
    jakarta.servlet.jsp.PageContext pageContext = _jspx_page_context;
    jakarta.servlet.jsp.JspWriter out = _jspx_page_context.getOut();
    //  layout:put
    lk.callidora.jsp.inheritance.PutTag _jspx_th_layout_005fput_005f1 = new lk.callidora.jsp.inheritance.PutTag();
    _jsp_getInstanceManager().newInstance(_jspx_th_layout_005fput_005f1);
    try {
      _jspx_th_layout_005fput_005f1.setJspContext(_jspx_page_context);
      _jspx_th_layout_005fput_005f1.setParent(_jspx_parent);
      // /WEB-INF/views/frontend/cart.jsp(8,4) name = block type = null reqTime = true required = true fragment = false deferredValue = false expectedTypeName = null deferredMethod = false methodSignature = null
      _jspx_th_layout_005fput_005f1.setBlock("contents");
      _jspx_th_layout_005fput_005f1.setJspBody(new Helper( 2, _jspx_page_context, _jspx_th_layout_005fput_005f1, null));
      _jspx_th_layout_005fput_005f1.doTag();
    } finally {
      _jsp_getInstanceManager().destroyInstance(_jspx_th_layout_005fput_005f1);
    }
    return false;
  }

  private class Helper
      extends org.apache.jasper.runtime.JspFragmentHelper
  {
    private jakarta.servlet.jsp.tagext.JspTag _jspx_parent;
    private int[] _jspx_push_body_count;

    public Helper( int discriminator, jakarta.servlet.jsp.JspContext jspContext, jakarta.servlet.jsp.tagext.JspTag _jspx_parent, int[] _jspx_push_body_count ) {
      super( discriminator, jspContext, _jspx_parent );
      this._jspx_parent = _jspx_parent;
      this._jspx_push_body_count = _jspx_push_body_count;
    }
    public boolean invoke0( jakarta.servlet.jsp.JspWriter out ) 
      throws java.lang.Throwable
    {
      out.write("\r\n");
      out.write("    ");
      if (_jspx_meth_layout_005fput_005f0(_jspx_parent, _jspx_page_context))
        return true;
      out.write("\r\n");
      out.write("    ");
      if (_jspx_meth_layout_005fput_005f1(_jspx_parent, _jspx_page_context))
        return true;
      out.write('\r');
      out.write('\n');
      return false;
    }
    public boolean invoke1( jakarta.servlet.jsp.JspWriter out ) 
      throws java.lang.Throwable
    {
      out.write("\r\n");
      out.write("        <title>Cart | eBookStore</title>\r\n");
      out.write("    ");
      return false;
    }
    public boolean invoke2( jakarta.servlet.jsp.JspWriter out ) 
      throws java.lang.Throwable
    {
      out.write("\r\n");
      out.write("        <body class=\"right-sidebar woocommerce-cart\">\r\n");
      out.write("        <div class=\"page-header border-bottom\">\r\n");
      out.write("            <div class=\"container\">\r\n");
      out.write("                <div class=\"d-md-flex justify-content-between align-items-center py-4\">\r\n");
      out.write("                    <h1 class=\"page-title font-size-3 font-weight-medium m-0 text-lh-lg\">Cart</h1>\r\n");
      out.write("                    <nav class=\"woocommerce-breadcrumb font-size-2\">\r\n");
      out.write("                        <a href=\"#\" class=\"h-primary\">Home</a>\r\n");
      out.write("                        <span class=\"breadcrumb-separator mx-1\"><i class=\"fas fa-angle-right\"></i></span>\r\n");
      out.write("                        <a href=\"#\" class=\"h-primary\">Shop</a>\r\n");
      out.write("                        <span class=\"breadcrumb-separator mx-1\"><i class=\"fas fa-angle-right\"></i></span>Cart\r\n");
      out.write("                    </nav>\r\n");
      out.write("                </div>\r\n");
      out.write("            </div>\r\n");
      out.write("        </div>\r\n");
      out.write("        <div class=\"site-content bg-punch-light overflow-hidden\" id=\"content\">\r\n");
      out.write("            <div class=\"container\">\r\n");
      out.write("                <header class=\"entry-header space-top-2 space-bottom-1 mb-2\">\r\n");
      out.write("                    <h1 class=\"entry-title font-size-7\">Your cart: 3 items</h1>\r\n");
      out.write("                </header>\r\n");
      out.write("                <div class=\"row pb-8\">\r\n");
      out.write("                    <div id=\"primary\" class=\"content-area\">\r\n");
      out.write("                        <main id=\"main\" class=\"site-main \">\r\n");
      out.write("                            <div class=\"page type-page status-publish hentry\">\r\n");
      out.write("\r\n");
      out.write("                                <div class=\"entry-content\">\r\n");
      out.write("                                    <div class=\"woocommerce\">\r\n");
      out.write("                                        <form class=\"woocommerce-cart-form table-responsive\" action=\"#\" method=\"post\">\r\n");
      out.write("                                            <table class=\"shop_table shop_table_responsive cart woocommerce-cart-form__contents\">\r\n");
      out.write("                                                <thead>\r\n");
      out.write("                                                <tr>\r\n");
      out.write("                                                    <th class=\"product-name\">Product</th>\r\n");
      out.write("                                                    <th class=\"product-price\">Price</th>\r\n");
      out.write("                                                    <th class=\"product-quantity\">Quantity</th>\r\n");
      out.write("                                                    <th class=\"product-subtotal\">Total</th>\r\n");
      out.write("                                                    <th class=\"product-remove\">&nbsp;</th>\r\n");
      out.write("                                                </tr>\r\n");
      out.write("                                                </thead>\r\n");
      out.write("                                                <tbody>\r\n");
      out.write("                                                <tr class=\"woocommerce-cart-form__cart-item cart_item\">\r\n");
      out.write("                                                    <td class=\"product-name\" data-title=\"Product\">\r\n");
      out.write("                                                        <div class=\"d-flex align-items-center\">\r\n");
      out.write("                                                            <a href=\"#\">\r\n");
      out.write("                                                                <img src=\"assets/img/90x138/img1.jpg\"\r\n");
      out.write("                                                                     class=\"attachment-shop_thumbnail size-shop_thumbnail wp-post-image\"\r\n");
      out.write("                                                                     alt>\r\n");
      out.write("                                                            </a>\r\n");
      out.write("                                                            <div class=\"ml-3 m-w-200-lg-down\">\r\n");
      out.write("                                                                <a href=\"#\">The Overdue Life of Amy Byler</a>\r\n");
      out.write("                                                                <a href=\"#\" class=\"text-gray-700 font-size-2 d-block\"\r\n");
      out.write("                                                                   tabindex=\"0\">Kelly Harms</a>\r\n");
      out.write("                                                            </div>\r\n");
      out.write("                                                        </div>\r\n");
      out.write("                                                    </td>\r\n");
      out.write("                                                    <td class=\"product-price\" data-title=\"Price\">\r\n");
      out.write("                                                <span class=\"woocommerce-Price-amount amount\"><span\r\n");
      out.write("                                                        class=\"woocommerce-Price-currencySymbol\">£</span>79.99</span>\r\n");
      out.write("                                                    </td>\r\n");
      out.write("                                                    <td class=\"product-quantity\" data-title=\"Quantity\">\r\n");
      out.write("                                                        <div class=\"quantity d-flex align-items-center\">\r\n");
      out.write("\r\n");
      out.write("                                                            <div class=\"border px-3 width-120\">\r\n");
      out.write("                                                                <div class=\"js-quantity\">\r\n");
      out.write("                                                                    <div class=\"d-flex align-items-center\">\r\n");
      out.write("                                                                        <label class=\"screen-reader-text sr-only\">Quantity</label>\r\n");
      out.write("                                                                        <a class=\"js-minus text-dark\" href=\"javascript:;\">\r\n");
      out.write("                                                                            <svg xmlns=\"http://www.w3.org/2000/svg\"\r\n");
      out.write("                                                                                 xmlns:xlink=\"http://www.w3.org/1999/xlink\"\r\n");
      out.write("                                                                                 width=\"10px\" height=\"1px\">\r\n");
      out.write("                                                                                <path fill-rule=\"evenodd\" fill=\"rgb(22, 22, 25)\"\r\n");
      out.write("                                                                                      d=\"M-0.000,-0.000 L10.000,-0.000 L10.000,1.000 L-0.000,1.000 L-0.000,-0.000 Z\"/>\r\n");
      out.write("                                                                            </svg>\r\n");
      out.write("                                                                        </a>\r\n");
      out.write("                                                                        <input type=\"number\"\r\n");
      out.write("                                                                               class=\"input-text qty text js-result form-control text-center border-0\"\r\n");
      out.write("                                                                               step=\"1\" min=\"1\" max=\"100\" name=\"quantity\"\r\n");
      out.write("                                                                               value=\"1\" title=\"Qty\">\r\n");
      out.write("                                                                        <a class=\"js-plus text-dark\" href=\"javascript:;\">\r\n");
      out.write("                                                                            <svg xmlns=\"http://www.w3.org/2000/svg\"\r\n");
      out.write("                                                                                 xmlns:xlink=\"http://www.w3.org/1999/xlink\"\r\n");
      out.write("                                                                                 width=\"10px\" height=\"10px\">\r\n");
      out.write("                                                                                <path fill-rule=\"evenodd\" fill=\"rgb(22, 22, 25)\"\r\n");
      out.write("                                                                                      d=\"M10.000,5.000 L6.000,5.000 L6.000,10.000 L5.000,10.000 L5.000,5.000 L-0.000,5.000 L-0.000,4.000 L5.000,4.000 L5.000,-0.000 L6.000,-0.000 L6.000,4.000 L10.000,4.000 L10.000,5.000 Z\"/>\r\n");
      out.write("                                                                            </svg>\r\n");
      out.write("                                                                        </a>\r\n");
      out.write("                                                                    </div>\r\n");
      out.write("                                                                </div>\r\n");
      out.write("                                                            </div>\r\n");
      out.write("\r\n");
      out.write("                                                        </div>\r\n");
      out.write("                                                    </td>\r\n");
      out.write("                                                    <td class=\"product-subtotal\" data-title=\"Total\">\r\n");
      out.write("                                                <span class=\"woocommerce-Price-amount amount\"><span\r\n");
      out.write("                                                        class=\"woocommerce-Price-currencySymbol\">£</span>79.99</span>\r\n");
      out.write("                                                    </td>\r\n");
      out.write("                                                    <td class=\"product-remove\">\r\n");
      out.write("                                                        <a href=\"#\" class=\"remove\" aria-label=\"Remove this item\">\r\n");
      out.write("                                                            <svg xmlns=\"http://www.w3.org/2000/svg\"\r\n");
      out.write("                                                                 xmlns:xlink=\"http://www.w3.org/1999/xlink\" width=\"15px\"\r\n");
      out.write("                                                                 height=\"15px\">\r\n");
      out.write("                                                                <path fill-rule=\"evenodd\" fill=\"rgb(22, 22, 25)\"\r\n");
      out.write("                                                                      d=\"M15.011,13.899 L13.899,15.012 L7.500,8.613 L1.101,15.012 L-0.012,13.899 L6.387,7.500 L-0.012,1.101 L1.101,-0.012 L7.500,6.387 L13.899,-0.012 L15.011,1.101 L8.613,7.500 L15.011,13.899 Z\"/>\r\n");
      out.write("                                                            </svg>\r\n");
      out.write("                                                        </a>\r\n");
      out.write("                                                    </td>\r\n");
      out.write("                                                </tr>\r\n");
      out.write("                                                <tr class=\"woocommerce-cart-form__cart-item cart_item\">\r\n");
      out.write("                                                    <td class=\"product-name\" data-title=\"Product\">\r\n");
      out.write("                                                        <div class=\"d-flex align-items-center\">\r\n");
      out.write("                                                            <a href=\"#\">\r\n");
      out.write("                                                                <img src=\"assets/img/90x138/img2.jpg\"\r\n");
      out.write("                                                                     class=\"attachment-shop_thumbnail size-shop_thumbnail wp-post-image\"\r\n");
      out.write("                                                                     alt>\r\n");
      out.write("                                                            </a>\r\n");
      out.write("                                                            <div class=\"ml-3 m-w-200-lg-down\">\r\n");
      out.write("                                                                <a href=\"#\">All You Can Ever Know: A Memoir</a>\r\n");
      out.write("                                                                <a href=\"#\" class=\"text-gray-700 font-size-2 d-block\"\r\n");
      out.write("                                                                   tabindex=\"0\">Kelly Harms</a>\r\n");
      out.write("                                                            </div>\r\n");
      out.write("                                                        </div>\r\n");
      out.write("                                                    </td>\r\n");
      out.write("                                                    <td class=\"product-price\" data-title=\"Price\">\r\n");
      out.write("                                                <span class=\"woocommerce-Price-amount amount\"><span\r\n");
      out.write("                                                        class=\"woocommerce-Price-currencySymbol\">£</span>79.99</span>\r\n");
      out.write("                                                    </td>\r\n");
      out.write("                                                    <td class=\"product-quantity\" data-title=\"Quantity\">\r\n");
      out.write("                                                        <div class=\"quantity d-flex align-items-center\">\r\n");
      out.write("\r\n");
      out.write("                                                            <div class=\"border px-3 width-120\">\r\n");
      out.write("                                                                <div class=\"js-quantity\">\r\n");
      out.write("                                                                    <div class=\"d-flex align-items-center\">\r\n");
      out.write("                                                                        <label class=\"screen-reader-text sr-only\">Quantity</label>\r\n");
      out.write("                                                                        <a class=\"js-minus text-dark\" href=\"javascript:;\">\r\n");
      out.write("                                                                            <svg xmlns=\"http://www.w3.org/2000/svg\"\r\n");
      out.write("                                                                                 xmlns:xlink=\"http://www.w3.org/1999/xlink\"\r\n");
      out.write("                                                                                 width=\"10px\" height=\"1px\">\r\n");
      out.write("                                                                                <path fill-rule=\"evenodd\" fill=\"rgb(22, 22, 25)\"\r\n");
      out.write("                                                                                      d=\"M-0.000,-0.000 L10.000,-0.000 L10.000,1.000 L-0.000,1.000 L-0.000,-0.000 Z\"/>\r\n");
      out.write("                                                                            </svg>\r\n");
      out.write("                                                                        </a>\r\n");
      out.write("                                                                        <input type=\"number\"\r\n");
      out.write("                                                                               class=\"input-text qty text js-result form-control text-center border-0\"\r\n");
      out.write("                                                                               step=\"1\" min=\"1\" max=\"100\" name=\"quantity\"\r\n");
      out.write("                                                                               value=\"1\" title=\"Qty\">\r\n");
      out.write("                                                                        <a class=\"js-plus text-dark\" href=\"javascript:;\">\r\n");
      out.write("                                                                            <svg xmlns=\"http://www.w3.org/2000/svg\"\r\n");
      out.write("                                                                                 xmlns:xlink=\"http://www.w3.org/1999/xlink\"\r\n");
      out.write("                                                                                 width=\"10px\" height=\"10px\">\r\n");
      out.write("                                                                                <path fill-rule=\"evenodd\" fill=\"rgb(22, 22, 25)\"\r\n");
      out.write("                                                                                      d=\"M10.000,5.000 L6.000,5.000 L6.000,10.000 L5.000,10.000 L5.000,5.000 L-0.000,5.000 L-0.000,4.000 L5.000,4.000 L5.000,-0.000 L6.000,-0.000 L6.000,4.000 L10.000,4.000 L10.000,5.000 Z\"/>\r\n");
      out.write("                                                                            </svg>\r\n");
      out.write("                                                                        </a>\r\n");
      out.write("                                                                    </div>\r\n");
      out.write("                                                                </div>\r\n");
      out.write("                                                            </div>\r\n");
      out.write("\r\n");
      out.write("                                                        </div>\r\n");
      out.write("                                                    </td>\r\n");
      out.write("                                                    <td class=\"product-subtotal\" data-title=\"Total\">\r\n");
      out.write("                                                <span class=\"woocommerce-Price-amount amount\"><span\r\n");
      out.write("                                                        class=\"woocommerce-Price-currencySymbol\">£</span>79.99</span>\r\n");
      out.write("                                                    </td>\r\n");
      out.write("                                                    <td class=\"product-remove\">\r\n");
      out.write("                                                        <a href=\"#\" class=\"remove\" aria-label=\"Remove this item\">\r\n");
      out.write("                                                            <svg xmlns=\"http://www.w3.org/2000/svg\"\r\n");
      out.write("                                                                 xmlns:xlink=\"http://www.w3.org/1999/xlink\" width=\"15px\"\r\n");
      out.write("                                                                 height=\"15px\">\r\n");
      out.write("                                                                <path fill-rule=\"evenodd\" fill=\"rgb(22, 22, 25)\"\r\n");
      out.write("                                                                      d=\"M15.011,13.899 L13.899,15.012 L7.500,8.613 L1.101,15.012 L-0.012,13.899 L6.387,7.500 L-0.012,1.101 L1.101,-0.012 L7.500,6.387 L13.899,-0.012 L15.011,1.101 L8.613,7.500 L15.011,13.899 Z\"/>\r\n");
      out.write("                                                            </svg>\r\n");
      out.write("                                                        </a>\r\n");
      out.write("                                                    </td>\r\n");
      out.write("                                                </tr>\r\n");
      out.write("                                                <tr class=\"woocommerce-cart-form__cart-item cart_item\">\r\n");
      out.write("                                                    <td class=\"product-name\" data-title=\"Product\">\r\n");
      out.write("                                                        <div class=\"d-flex align-items-center\">\r\n");
      out.write("                                                            <a href=\"#\">\r\n");
      out.write("                                                                <img src=\"assets/img/90x138/img3.jpg\"\r\n");
      out.write("                                                                     class=\"attachment-shop_thumbnail size-shop_thumbnail wp-post-image\"\r\n");
      out.write("                                                                     alt>\r\n");
      out.write("                                                            </a>\r\n");
      out.write("                                                            <div class=\"ml-3 m-w-200-lg-down\">\r\n");
      out.write("                                                                <a href=\"#\">Winter Garden</a>\r\n");
      out.write("                                                                <a href=\"#\" class=\"text-gray-700 font-size-2 d-block\"\r\n");
      out.write("                                                                   tabindex=\"0\">Kelly Harms</a>\r\n");
      out.write("                                                            </div>\r\n");
      out.write("                                                        </div>\r\n");
      out.write("                                                    </td>\r\n");
      out.write("                                                    <td class=\"product-price\" data-title=\"Price\">\r\n");
      out.write("                                                <span class=\"woocommerce-Price-amount amount\"><span\r\n");
      out.write("                                                        class=\"woocommerce-Price-currencySymbol\">£</span>79.99</span>\r\n");
      out.write("                                                    </td>\r\n");
      out.write("                                                    <td class=\"product-quantity\" data-title=\"Quantity\">\r\n");
      out.write("                                                        <div class=\"quantity d-flex align-items-center\">\r\n");
      out.write("\r\n");
      out.write("                                                            <div class=\"border px-3 width-120\">\r\n");
      out.write("                                                                <div class=\"js-quantity\">\r\n");
      out.write("                                                                    <div class=\"d-flex align-items-center\">\r\n");
      out.write("                                                                        <label class=\"screen-reader-text sr-only\">Quantity</label>\r\n");
      out.write("                                                                        <a class=\"js-minus text-dark\" href=\"javascript:;\">\r\n");
      out.write("                                                                            <svg xmlns=\"http://www.w3.org/2000/svg\"\r\n");
      out.write("                                                                                 xmlns:xlink=\"http://www.w3.org/1999/xlink\"\r\n");
      out.write("                                                                                 width=\"10px\" height=\"1px\">\r\n");
      out.write("                                                                                <path fill-rule=\"evenodd\" fill=\"rgb(22, 22, 25)\"\r\n");
      out.write("                                                                                      d=\"M-0.000,-0.000 L10.000,-0.000 L10.000,1.000 L-0.000,1.000 L-0.000,-0.000 Z\"/>\r\n");
      out.write("                                                                            </svg>\r\n");
      out.write("                                                                        </a>\r\n");
      out.write("                                                                        <input type=\"number\"\r\n");
      out.write("                                                                               class=\"input-text qty text js-result form-control text-center border-0\"\r\n");
      out.write("                                                                               step=\"1\" min=\"1\" max=\"100\" name=\"quantity\"\r\n");
      out.write("                                                                               value=\"1\" title=\"Qty\">\r\n");
      out.write("                                                                        <a class=\"js-plus text-dark\" href=\"javascript:;\">\r\n");
      out.write("                                                                            <svg xmlns=\"http://www.w3.org/2000/svg\"\r\n");
      out.write("                                                                                 xmlns:xlink=\"http://www.w3.org/1999/xlink\"\r\n");
      out.write("                                                                                 width=\"10px\" height=\"10px\">\r\n");
      out.write("                                                                                <path fill-rule=\"evenodd\" fill=\"rgb(22, 22, 25)\"\r\n");
      out.write("                                                                                      d=\"M10.000,5.000 L6.000,5.000 L6.000,10.000 L5.000,10.000 L5.000,5.000 L-0.000,5.000 L-0.000,4.000 L5.000,4.000 L5.000,-0.000 L6.000,-0.000 L6.000,4.000 L10.000,4.000 L10.000,5.000 Z\"/>\r\n");
      out.write("                                                                            </svg>\r\n");
      out.write("                                                                        </a>\r\n");
      out.write("                                                                    </div>\r\n");
      out.write("                                                                </div>\r\n");
      out.write("                                                            </div>\r\n");
      out.write("\r\n");
      out.write("                                                        </div>\r\n");
      out.write("                                                    </td>\r\n");
      out.write("                                                    <td class=\"product-subtotal\" data-title=\"Total\">\r\n");
      out.write("                                                <span class=\"woocommerce-Price-amount amount\"><span\r\n");
      out.write("                                                        class=\"woocommerce-Price-currencySymbol\">£</span>79.99</span>\r\n");
      out.write("                                                    </td>\r\n");
      out.write("                                                    <td class=\"product-remove\">\r\n");
      out.write("                                                        <a href=\"#\" class=\"remove\" aria-label=\"Remove this item\">\r\n");
      out.write("                                                            <svg xmlns=\"http://www.w3.org/2000/svg\"\r\n");
      out.write("                                                                 xmlns:xlink=\"http://www.w3.org/1999/xlink\" width=\"15px\"\r\n");
      out.write("                                                                 height=\"15px\">\r\n");
      out.write("                                                                <path fill-rule=\"evenodd\" fill=\"rgb(22, 22, 25)\"\r\n");
      out.write("                                                                      d=\"M15.011,13.899 L13.899,15.012 L7.500,8.613 L1.101,15.012 L-0.012,13.899 L6.387,7.500 L-0.012,1.101 L1.101,-0.012 L7.500,6.387 L13.899,-0.012 L15.011,1.101 L8.613,7.500 L15.011,13.899 Z\"/>\r\n");
      out.write("                                                            </svg>\r\n");
      out.write("                                                        </a>\r\n");
      out.write("                                                    </td>\r\n");
      out.write("                                                </tr>\r\n");
      out.write("                                                <tr>\r\n");
      out.write("                                                    <td colspan=\"5\" class=\"actions\">\r\n");
      out.write("\r\n");
      out.write("                                                        <input type=\"submit\" class=\"button\" name=\"update_cart\"\r\n");
      out.write("                                                               value=\"Update cart\">\r\n");
      out.write("                                                        <input type=\"hidden\" id=\"_wpnonce\" name=\"_wpnonce\"\r\n");
      out.write("                                                               value=\"db025d7a70\"><input type=\"hidden\" name=\"_wp_http_referer\"\r\n");
      out.write("                                                                                         value=\"/storefront/cart/\">\r\n");
      out.write("                                                    </td>\r\n");
      out.write("                                                </tr>\r\n");
      out.write("                                                </tbody>\r\n");
      out.write("                                            </table>\r\n");
      out.write("                                        </form>\r\n");
      out.write("                                    </div>\r\n");
      out.write("                                </div>\r\n");
      out.write("\r\n");
      out.write("                            </div>\r\n");
      out.write("                        </main>\r\n");
      out.write("                    </div>\r\n");
      out.write("                    <div id=\"secondary\" class=\"sidebar cart-collaterals order-1\" role=\"complementary\">\r\n");
      out.write("                        <div id=\"cartAccordion\" class=\"border border-gray-900 bg-white mb-5\">\r\n");
      out.write("                            <div class=\"p-4d875 border\">\r\n");
      out.write("                                <div id=\"cartHeadingOne\" class=\"cart-head\">\r\n");
      out.write("                                    <a class=\"d-flex align-items-center justify-content-between text-dark\" href=\"#\"\r\n");
      out.write("                                       data-toggle=\"collapse\" data-target=\"#cartCollapseOne\" aria-expanded=\"true\"\r\n");
      out.write("                                       aria-controls=\"cartCollapseOne\">\r\n");
      out.write("                                        <h3 class=\"cart-title mb-0 font-weight-medium font-size-3\">Cart Totals</h3>\r\n");
      out.write("                                        <svg class=\"mins\" xmlns=\"http://www.w3.org/2000/svg\"\r\n");
      out.write("                                             xmlns:xlink=\"http://www.w3.org/1999/xlink\" width=\"15px\" height=\"2px\">\r\n");
      out.write("                                            <path fill-rule=\"evenodd\" fill=\"rgb(22, 22, 25)\"\r\n");
      out.write("                                                  d=\"M0.000,-0.000 L15.000,-0.000 L15.000,2.000 L0.000,2.000 L0.000,-0.000 Z\"/>\r\n");
      out.write("                                        </svg>\r\n");
      out.write("                                        <svg class=\"plus\" xmlns=\"http://www.w3.org/2000/svg\"\r\n");
      out.write("                                             xmlns:xlink=\"http://www.w3.org/1999/xlink\" width=\"15px\" height=\"15px\">\r\n");
      out.write("                                            <path fill-rule=\"evenodd\" fill=\"rgb(22, 22, 25)\"\r\n");
      out.write("                                                  d=\"M15.000,8.000 L9.000,8.000 L9.000,15.000 L7.000,15.000 L7.000,8.000 L0.000,8.000 L0.000,6.000 L7.000,6.000 L7.000,-0.000 L9.000,-0.000 L9.000,6.000 L15.000,6.000 L15.000,8.000 Z\"/>\r\n");
      out.write("                                        </svg>\r\n");
      out.write("                                    </a>\r\n");
      out.write("                                </div>\r\n");
      out.write("                                <div id=\"cartCollapseOne\" class=\"mt-4 cart-content collapse show\"\r\n");
      out.write("                                     aria-labelledby=\"cartHeadingOne\" data-parent=\"#cartAccordion\">\r\n");
      out.write("                                    <table class=\"shop_table shop_table_responsive\">\r\n");
      out.write("                                        <tbody>\r\n");
      out.write("                                        <tr class=\"cart-subtotal\">\r\n");
      out.write("                                            <th>Subtotal</th>\r\n");
      out.write("                                            <td data-title=\"Subtotal\"><span class=\"woocommerce-Price-amount amount\"><span\r\n");
      out.write("                                                    class=\"woocommerce-Price-currencySymbol\">£</span>79.99</span>\r\n");
      out.write("                                            </td>\r\n");
      out.write("                                        </tr>\r\n");
      out.write("                                        <tr class=\"order-shipping\">\r\n");
      out.write("                                            <th>Shipping</th>\r\n");
      out.write("                                            <td data-title=\"Shipping\">Free Shipping</td>\r\n");
      out.write("                                        </tr>\r\n");
      out.write("                                        </tbody>\r\n");
      out.write("                                    </table>\r\n");
      out.write("                                </div>\r\n");
      out.write("                            </div>\r\n");
      out.write("                            <div class=\"p-4d875 border\">\r\n");
      out.write("                                <div id=\"cartHeadingTwo\" class=\"cart-head\">\r\n");
      out.write("                                    <a class=\"d-flex align-items-center justify-content-between text-dark\" href=\"#\"\r\n");
      out.write("                                       data-toggle=\"collapse\" data-target=\"#cartCollapseTwo\" aria-expanded=\"true\"\r\n");
      out.write("                                       aria-controls=\"cartCollapseTwo\">\r\n");
      out.write("                                        <h3 class=\"cart-title mb-0 font-weight-medium font-size-3\">Shipping</h3>\r\n");
      out.write("                                        <svg class=\"mins\" xmlns=\"http://www.w3.org/2000/svg\"\r\n");
      out.write("                                             xmlns:xlink=\"http://www.w3.org/1999/xlink\" width=\"15px\" height=\"2px\">\r\n");
      out.write("                                            <path fill-rule=\"evenodd\" fill=\"rgb(22, 22, 25)\"\r\n");
      out.write("                                                  d=\"M0.000,-0.000 L15.000,-0.000 L15.000,2.000 L0.000,2.000 L0.000,-0.000 Z\"/>\r\n");
      out.write("                                        </svg>\r\n");
      out.write("                                        <svg class=\"plus\" xmlns=\"http://www.w3.org/2000/svg\"\r\n");
      out.write("                                             xmlns:xlink=\"http://www.w3.org/1999/xlink\" width=\"15px\" height=\"15px\">\r\n");
      out.write("                                            <path fill-rule=\"evenodd\" fill=\"rgb(22, 22, 25)\"\r\n");
      out.write("                                                  d=\"M15.000,8.000 L9.000,8.000 L9.000,15.000 L7.000,15.000 L7.000,8.000 L0.000,8.000 L0.000,6.000 L7.000,6.000 L7.000,-0.000 L9.000,-0.000 L9.000,6.000 L15.000,6.000 L15.000,8.000 Z\"/>\r\n");
      out.write("                                        </svg>\r\n");
      out.write("                                    </a>\r\n");
      out.write("                                </div>\r\n");
      out.write("                                <div id=\"cartCollapseTwo\" class=\"mt-4 cart-content collapse show\"\r\n");
      out.write("                                     aria-labelledby=\"cartHeadingTwo\" data-parent=\"#cartAccordion\">\r\n");
      out.write("\r\n");
      out.write("                                    <ul id=\"shipping_method\">\r\n");
      out.write("                                        <li>\r\n");
      out.write("                                            <input type=\"radio\" name=\"shipping_method[0]\" data-index=\"0\"\r\n");
      out.write("                                                   id=\"shipping_method_0_flat_rate1\" value=\"flat_rate:1\"\r\n");
      out.write("                                                   class=\"shipping_method\">\r\n");
      out.write("                                            <label for=\"shipping_method_0_flat_rate1\">Free shipping</label>\r\n");
      out.write("                                        </li>\r\n");
      out.write("                                        <li>\r\n");
      out.write("                                            <input type=\"radio\" name=\"shipping_method[0]\" data-index=\"0\"\r\n");
      out.write("                                                   id=\"shipping_method_0_flat_rate2\" value=\"flat_rate:2\" class=\"shipping_method\"\r\n");
      out.write("                                                   checked=\"checked\">\r\n");
      out.write("                                            <label for=\"shipping_method_0_flat_rate2\">Flat rate: <span\r\n");
      out.write("                                                    class=\"woocommerce-Price-amount amount\"><span\r\n");
      out.write("                                                    class=\"woocommerce-Price-currencySymbol\">$</span>15</span></label>\r\n");
      out.write("                                        </li>\r\n");
      out.write("                                        <li>\r\n");
      out.write("                                            <input type=\"radio\" name=\"shipping_method[0]\" data-index=\"0\"\r\n");
      out.write("                                                   id=\"shipping_method_0_flat_rate3\" value=\"flat_rate:2\" class=\"shipping_method\"\r\n");
      out.write("                                                   checked=\"checked\">\r\n");
      out.write("                                            <label for=\"shipping_method_0_flat_rate3\">Local pickup:: <span\r\n");
      out.write("                                                    class=\"woocommerce-Price-amount amount\"><span\r\n");
      out.write("                                                    class=\"woocommerce-Price-currencySymbol\">$</span>8</span></label>\r\n");
      out.write("                                        </li>\r\n");
      out.write("                                    </ul>\r\n");
      out.write("\r\n");
      out.write("                                    <span class=\"font-size-2\">Shipping to Turkey.</span><a href=\"#\"\r\n");
      out.write("                                                                                           class=\"font-weight-medium h-primary ml-3 font-size-2\">Change\r\n");
      out.write("                                    Address</a>\r\n");
      out.write("                                </div>\r\n");
      out.write("                            </div>\r\n");
      out.write("                            <div class=\"p-4d875 border\">\r\n");
      out.write("                                <div id=\"cartHeadingThree\" class=\"cart-head\">\r\n");
      out.write("                                    <a class=\"d-flex align-items-center justify-content-between text-dark\" href=\"#\"\r\n");
      out.write("                                       data-toggle=\"collapse\" data-target=\"#cartCollapseThree\" aria-expanded=\"true\"\r\n");
      out.write("                                       aria-controls=\"cartCollapseThree\">\r\n");
      out.write("                                        <h3 class=\"cart-title mb-0 font-weight-medium font-size-3\">Coupon</h3>\r\n");
      out.write("                                        <svg class=\"mins\" xmlns=\"http://www.w3.org/2000/svg\"\r\n");
      out.write("                                             xmlns:xlink=\"http://www.w3.org/1999/xlink\" width=\"15px\" height=\"2px\">\r\n");
      out.write("                                            <path fill-rule=\"evenodd\" fill=\"rgb(22, 22, 25)\"\r\n");
      out.write("                                                  d=\"M0.000,-0.000 L15.000,-0.000 L15.000,2.000 L0.000,2.000 L0.000,-0.000 Z\"/>\r\n");
      out.write("                                        </svg>\r\n");
      out.write("                                        <svg class=\"plus\" xmlns=\"http://www.w3.org/2000/svg\"\r\n");
      out.write("                                             xmlns:xlink=\"http://www.w3.org/1999/xlink\" width=\"15px\" height=\"15px\">\r\n");
      out.write("                                            <path fill-rule=\"evenodd\" fill=\"rgb(22, 22, 25)\"\r\n");
      out.write("                                                  d=\"M15.000,8.000 L9.000,8.000 L9.000,15.000 L7.000,15.000 L7.000,8.000 L0.000,8.000 L0.000,6.000 L7.000,6.000 L7.000,-0.000 L9.000,-0.000 L9.000,6.000 L15.000,6.000 L15.000,8.000 Z\"/>\r\n");
      out.write("                                        </svg>\r\n");
      out.write("                                    </a>\r\n");
      out.write("                                </div>\r\n");
      out.write("                                <div id=\"cartCollapseThree\" class=\"mt-4 cart-content collapse show\"\r\n");
      out.write("                                     aria-labelledby=\"cartHeadingThree\" data-parent=\"#cartAccordion\">\r\n");
      out.write("                                    <div class=\"coupon\">\r\n");
      out.write("                                        <label for=\"coupon_code\">Coupon:</label>\r\n");
      out.write("                                        <input type=\"text\" name=\"coupon_code\" class=\"input-text\" id=\"coupon_code\" value\r\n");
      out.write("                                               placeholder=\"Coupon code\" autocomplete=\"off\">\r\n");
      out.write("                                        <input type=\"submit\" class=\"button\" name=\"apply_coupon\" value=\"Apply coupon\">\r\n");
      out.write("                                    </div>\r\n");
      out.write("                                </div>\r\n");
      out.write("                            </div>\r\n");
      out.write("                            <div class=\"p-4d875 border\">\r\n");
      out.write("                                <table class=\"shop_table shop_table_responsive\">\r\n");
      out.write("                                    <tbody>\r\n");
      out.write("                                    <tr class=\"order-total\">\r\n");
      out.write("                                        <th>Total</th>\r\n");
      out.write("                                        <td data-title=\"Total\"><strong><span class=\"woocommerce-Price-amount amount\"><span\r\n");
      out.write("                                                class=\"woocommerce-Price-currencySymbol\">£</span>97.99</span></strong></td>\r\n");
      out.write("                                    </tr>\r\n");
      out.write("                                    </tbody>\r\n");
      out.write("                                </table>\r\n");
      out.write("                            </div>\r\n");
      out.write("                        </div>\r\n");
      out.write("                        <div class=\"wc-proceed-to-checkout\">\r\n");
      out.write("                            <a href=\"checkout.html\"\r\n");
      out.write("                               class=\"checkout-button button alt wc-forward btn btn-dark btn-block rounded-0 py-4\">Proceed to\r\n");
      out.write("                                checkout</a>\r\n");
      out.write("                        </div>\r\n");
      out.write("                    </div>\r\n");
      out.write("                </div>\r\n");
      out.write("            </div>\r\n");
      out.write("        </div>\r\n");
      out.write("        </body>\r\n");
      out.write("\r\n");
      out.write("    ");
      return false;
    }
    public void invoke( java.io.Writer writer )
      throws jakarta.servlet.jsp.JspException
    {
      jakarta.servlet.jsp.JspWriter out = null;
      if( writer != null ) {
        out = this.jspContext.pushBody(writer);
      } else {
        out = this.jspContext.getOut();
      }
      try {
        Object _jspx_saved_JspContext = this.jspContext.getELContext().getContext(jakarta.servlet.jsp.JspContext.class);
        this.jspContext.getELContext().putContext(jakarta.servlet.jsp.JspContext.class,this.jspContext);
        switch( this.discriminator ) {
          case 0:
            invoke0( out );
            break;
          case 1:
            invoke1( out );
            break;
          case 2:
            invoke2( out );
            break;
        }
        jspContext.getELContext().putContext(jakarta.servlet.jsp.JspContext.class,_jspx_saved_JspContext);
      }
      catch( java.lang.Throwable e ) {
        if (e instanceof jakarta.servlet.jsp.SkipPageException)
            throw (jakarta.servlet.jsp.SkipPageException) e;
        throw new jakarta.servlet.jsp.JspException( e );
      }
      finally {
        if( writer != null ) {
          this.jspContext.popBody();
        }
      }
    }
  }
}
