/*
 * Generated by the Jasper component of Apache Tomcat
 * Version: Apache Tomcat/10.1.7
 * Generated at: 2023-09-01 13:36:20 UTC
 * Note: The last modified time of this file was set to
 *       the last modified time of the source file after
 *       generation to assist with modification tracking.
 */
package org.apache.jsp.WEB_002dINF.views.frontend;

import jakarta.servlet.*;
import jakarta.servlet.http.*;
import jakarta.servlet.jsp.*;

public final class contactUs_jsp extends org.apache.jasper.runtime.HttpJspBase
    implements org.apache.jasper.runtime.JspSourceDependent,
                 org.apache.jasper.runtime.JspSourceImports,
                 org.apache.jasper.runtime.JspSourceDirectives {

  private static final jakarta.servlet.jsp.JspFactory _jspxFactory =
          jakarta.servlet.jsp.JspFactory.getDefaultFactory();

  private static java.util.Map<java.lang.String,java.lang.Long> _jspx_dependants;

  static {
    _jspx_dependants = new java.util.HashMap<java.lang.String,java.lang.Long>(2);
    _jspx_dependants.put("file:/C:/Users/Jasir/.m2/repository/lk/callidora/jsp/jsp-template-inheritance/1.0.1/jsp-template-inheritance-1.0.1.jar", Long.valueOf(1692244300354L));
    _jspx_dependants.put("jar:file:/C:/Users/Jasir/.m2/repository/lk/callidora/jsp/jsp-template-inheritance/1.0.1/jsp-template-inheritance-1.0.1.jar!/META-INF/jsp-inheritance.tld", Long.valueOf(1692219220000L));
  }

  private static final java.util.Set<java.lang.String> _jspx_imports_packages;

  private static final java.util.Set<java.lang.String> _jspx_imports_classes;

  static {
    _jspx_imports_packages = new java.util.HashSet<>();
    _jspx_imports_packages.add("jakarta.servlet");
    _jspx_imports_packages.add("jakarta.servlet.http");
    _jspx_imports_packages.add("jakarta.servlet.jsp");
    _jspx_imports_classes = null;
  }

  private volatile jakarta.el.ExpressionFactory _el_expressionfactory;
  private volatile org.apache.tomcat.InstanceManager _jsp_instancemanager;

  public java.util.Map<java.lang.String,java.lang.Long> getDependants() {
    return _jspx_dependants;
  }

  public java.util.Set<java.lang.String> getPackageImports() {
    return _jspx_imports_packages;
  }

  public java.util.Set<java.lang.String> getClassImports() {
    return _jspx_imports_classes;
  }

  public boolean getErrorOnELNotFound() {
    return false;
  }

  public jakarta.el.ExpressionFactory _jsp_getExpressionFactory() {
    if (_el_expressionfactory == null) {
      synchronized (this) {
        if (_el_expressionfactory == null) {
          _el_expressionfactory = _jspxFactory.getJspApplicationContext(getServletConfig().getServletContext()).getExpressionFactory();
        }
      }
    }
    return _el_expressionfactory;
  }

  public org.apache.tomcat.InstanceManager _jsp_getInstanceManager() {
    if (_jsp_instancemanager == null) {
      synchronized (this) {
        if (_jsp_instancemanager == null) {
          _jsp_instancemanager = org.apache.jasper.runtime.InstanceManagerFactory.getInstanceManager(getServletConfig());
        }
      }
    }
    return _jsp_instancemanager;
  }

  public void _jspInit() {
  }

  public void _jspDestroy() {
  }

  public void _jspService(final jakarta.servlet.http.HttpServletRequest request, final jakarta.servlet.http.HttpServletResponse response)
      throws java.io.IOException, jakarta.servlet.ServletException {

    if (!jakarta.servlet.DispatcherType.ERROR.equals(request.getDispatcherType())) {
      final java.lang.String _jspx_method = request.getMethod();
      if ("OPTIONS".equals(_jspx_method)) {
        response.setHeader("Allow","GET, HEAD, POST, OPTIONS");
        return;
      }
      if (!"GET".equals(_jspx_method) && !"POST".equals(_jspx_method) && !"HEAD".equals(_jspx_method)) {
        response.setHeader("Allow","GET, HEAD, POST, OPTIONS");
        response.sendError(HttpServletResponse.SC_METHOD_NOT_ALLOWED, "JSPs only permit GET, POST or HEAD. Jasper also permits OPTIONS");
        return;
      }
    }

    final jakarta.servlet.jsp.PageContext pageContext;
    jakarta.servlet.http.HttpSession session = null;
    final jakarta.servlet.ServletContext application;
    final jakarta.servlet.ServletConfig config;
    jakarta.servlet.jsp.JspWriter out = null;
    final java.lang.Object page = this;
    jakarta.servlet.jsp.JspWriter _jspx_out = null;
    jakarta.servlet.jsp.PageContext _jspx_page_context = null;


    try {
      response.setContentType("text/html;charset=UTF-8");
      pageContext = _jspxFactory.getPageContext(this, request, response,
      			null, true, 8192, true);
      _jspx_page_context = pageContext;
      application = pageContext.getServletContext();
      config = pageContext.getServletConfig();
      session = pageContext.getSession();
      out = pageContext.getOut();
      _jspx_out = out;

      out.write("\r\n");
      out.write("\r\n");
      out.write("\r\n");
      if (_jspx_meth_layout_005fextends_005f0(_jspx_page_context))
        return;
      out.write('\r');
      out.write('\n');
    } catch (java.lang.Throwable t) {
      if (!(t instanceof jakarta.servlet.jsp.SkipPageException)){
        out = _jspx_out;
        if (out != null && out.getBufferSize() != 0)
          try {
            if (response.isCommitted()) {
              out.flush();
            } else {
              out.clearBuffer();
            }
          } catch (java.io.IOException e) {}
        if (_jspx_page_context != null) _jspx_page_context.handlePageException(t);
        else throw new ServletException(t);
      }
    } finally {
      _jspxFactory.releasePageContext(_jspx_page_context);
    }
  }

  private boolean _jspx_meth_layout_005fextends_005f0(jakarta.servlet.jsp.PageContext _jspx_page_context)
          throws java.lang.Throwable {
    jakarta.servlet.jsp.PageContext pageContext = _jspx_page_context;
    jakarta.servlet.jsp.JspWriter out = _jspx_page_context.getOut();
    //  layout:extends
    lk.callidora.jsp.inheritance.ExtendsTag _jspx_th_layout_005fextends_005f0 = new lk.callidora.jsp.inheritance.ExtendsTag();
    _jsp_getInstanceManager().newInstance(_jspx_th_layout_005fextends_005f0);
    try {
      _jspx_th_layout_005fextends_005f0.setJspContext(_jspx_page_context);
      // /WEB-INF/views/frontend/contactUs.jsp(4,0) name = name type = null reqTime = true required = true fragment = false deferredValue = false expectedTypeName = null deferredMethod = false methodSignature = null
      _jspx_th_layout_005fextends_005f0.setName("base");
      _jspx_th_layout_005fextends_005f0.setJspBody(new Helper( 0, _jspx_page_context, _jspx_th_layout_005fextends_005f0, null));
      _jspx_th_layout_005fextends_005f0.doTag();
    } finally {
      _jsp_getInstanceManager().destroyInstance(_jspx_th_layout_005fextends_005f0);
    }
    return false;
  }

  private boolean _jspx_meth_layout_005fput_005f0(jakarta.servlet.jsp.tagext.JspTag _jspx_parent, jakarta.servlet.jsp.PageContext _jspx_page_context)
          throws java.lang.Throwable {
    jakarta.servlet.jsp.PageContext pageContext = _jspx_page_context;
    jakarta.servlet.jsp.JspWriter out = _jspx_page_context.getOut();
    //  layout:put
    lk.callidora.jsp.inheritance.PutTag _jspx_th_layout_005fput_005f0 = new lk.callidora.jsp.inheritance.PutTag();
    _jsp_getInstanceManager().newInstance(_jspx_th_layout_005fput_005f0);
    try {
      _jspx_th_layout_005fput_005f0.setJspContext(_jspx_page_context);
      _jspx_th_layout_005fput_005f0.setParent(_jspx_parent);
      // /WEB-INF/views/frontend/contactUs.jsp(5,4) name = block type = null reqTime = true required = true fragment = false deferredValue = false expectedTypeName = null deferredMethod = false methodSignature = null
      _jspx_th_layout_005fput_005f0.setBlock("title");
      _jspx_th_layout_005fput_005f0.setJspBody(new Helper( 1, _jspx_page_context, _jspx_th_layout_005fput_005f0, null));
      _jspx_th_layout_005fput_005f0.doTag();
    } finally {
      _jsp_getInstanceManager().destroyInstance(_jspx_th_layout_005fput_005f0);
    }
    return false;
  }

  private boolean _jspx_meth_layout_005fput_005f1(jakarta.servlet.jsp.tagext.JspTag _jspx_parent, jakarta.servlet.jsp.PageContext _jspx_page_context)
          throws java.lang.Throwable {
    jakarta.servlet.jsp.PageContext pageContext = _jspx_page_context;
    jakarta.servlet.jsp.JspWriter out = _jspx_page_context.getOut();
    //  layout:put
    lk.callidora.jsp.inheritance.PutTag _jspx_th_layout_005fput_005f1 = new lk.callidora.jsp.inheritance.PutTag();
    _jsp_getInstanceManager().newInstance(_jspx_th_layout_005fput_005f1);
    try {
      _jspx_th_layout_005fput_005f1.setJspContext(_jspx_page_context);
      _jspx_th_layout_005fput_005f1.setParent(_jspx_parent);
      // /WEB-INF/views/frontend/contactUs.jsp(8,4) name = block type = null reqTime = true required = true fragment = false deferredValue = false expectedTypeName = null deferredMethod = false methodSignature = null
      _jspx_th_layout_005fput_005f1.setBlock("contents");
      _jspx_th_layout_005fput_005f1.setJspBody(new Helper( 2, _jspx_page_context, _jspx_th_layout_005fput_005f1, null));
      _jspx_th_layout_005fput_005f1.doTag();
    } finally {
      _jsp_getInstanceManager().destroyInstance(_jspx_th_layout_005fput_005f1);
    }
    return false;
  }

  private class Helper
      extends org.apache.jasper.runtime.JspFragmentHelper
  {
    private jakarta.servlet.jsp.tagext.JspTag _jspx_parent;
    private int[] _jspx_push_body_count;

    public Helper( int discriminator, jakarta.servlet.jsp.JspContext jspContext, jakarta.servlet.jsp.tagext.JspTag _jspx_parent, int[] _jspx_push_body_count ) {
      super( discriminator, jspContext, _jspx_parent );
      this._jspx_parent = _jspx_parent;
      this._jspx_push_body_count = _jspx_push_body_count;
    }
    public boolean invoke0( jakarta.servlet.jsp.JspWriter out ) 
      throws java.lang.Throwable
    {
      out.write("\r\n");
      out.write("    ");
      if (_jspx_meth_layout_005fput_005f0(_jspx_parent, _jspx_page_context))
        return true;
      out.write("\r\n");
      out.write("    ");
      if (_jspx_meth_layout_005fput_005f1(_jspx_parent, _jspx_page_context))
        return true;
      out.write('\r');
      out.write('\n');
      return false;
    }
    public boolean invoke1( jakarta.servlet.jsp.JspWriter out ) 
      throws java.lang.Throwable
    {
      out.write("\r\n");
      out.write("        <title>Contact Us | eBookStore</title>\r\n");
      out.write("    ");
      return false;
    }
    public boolean invoke2( jakarta.servlet.jsp.JspWriter out ) 
      throws java.lang.Throwable
    {
      out.write("\r\n");
      out.write("        <main id=\"content\">\r\n");
      out.write("            <div class=\"py-3 py-lg-7\">\r\n");
      out.write("                <h6 class=\"font-weight-medium font-size-7 text-center my-1\">Contact Us</h6>\r\n");
      out.write("            </div>\r\n");
      out.write("            <iframe src=\"https://www.google.com/maps/embed?pb=!1m18!1m12!1m3!1d1013.5670516110969!2d80.44942927372759!3d7.257199598929997!2m3!1f0!2f0!3f0!3m2!1i1024!2i768!4f13.1!3m3!1m2!1s0x3ae314aec6ea9083%3A0xc996d5f1fb40ae70!2sWalpoladeniya%20Rd%2C%20Mawanella!5e0!3m2!1sen!2slk!4v1691291523880!5m2!1sen!2slk\"\r\n");
      out.write("                    height=\"500\" style=\"border:0; width:100%;\" allowfullscreen></iframe>\r\n");
      out.write('\r');
      out.write('\n');
      out.write('\r');
      out.write('\n');
      out.write("\r\n");
      out.write("            <div class=\"container\">\r\n");
      out.write("                <div class=\"space-bottom-1 space-bottom-lg-2\">\r\n");
      out.write("                    <div class=\"pb-4\">\r\n");
      out.write("                        <div class=\"col-lg-8 mx-auto\">\r\n");
      out.write("                            <div class=\"bg-white mt-n10 mt-md-n13 pt-5 pt-lg-7 px-3 px-md-5 pl-xl-10 pr-xl-3\">\r\n");
      out.write("                                <div class=\"ml-xl-4\">\r\n");
      out.write("                                    <div class=\"mb-4 mb-lg-7\">\r\n");
      out.write("                                        <h6 class=\"font-weight medium font-size-10 mb-4 mb-lg-7\">Contact Information</h6>\r\n");
      out.write("                                        <p class=\"font-weight-medium font-italic\">We will answer any questions you may have\r\n");
      out.write("                                            about our online sales, rights or partnership service right here.\r\n");
      out.write("                                        </p>\r\n");
      out.write("                                    </div>\r\n");
      out.write("                                    <div class=\"mb-4 mb-lg-8\">\r\n");
      out.write("                                        <div class=\"row\">\r\n");
      out.write("                                            <div class=\"col-md-6\">\r\n");
      out.write("                                                <h6 class=\"font-weight-medium font-size-4 mb-4\">Head Office</h6>\r\n");
      out.write("                                                <address class=\"font-size-2 mb-5\">\r\n");
      out.write("                                            <span class=\"mb-2 font-weight-normal text-dark\">\r\n");
      out.write("                                            Mawanella, Kegalle. <br> Sri Lanka\r\n");
      out.write("                                            </span>\r\n");
      out.write("                                                </address>\r\n");
      out.write("                                                <div>\r\n");
      out.write("                                                    <a href=\"mailto:sale@bookworm.com\"\r\n");
      out.write("                                                       class=\"font-size-2 d-block link-black-100 mb-1\">sales@ebookstore.com</a>\r\n");
      out.write("                                                    <a href=\"tel:+1246-345-0695\" class=\"font-size-2 d-block link-black-100\">+94 76-268-4595</a>\r\n");
      out.write("                                                </div>\r\n");
      out.write("                                            </div>\r\n");
      out.write("                                            <div class=\"col-md-6\">\r\n");
      out.write("                                                <h6 class=\"font-size-4 font-weight-medium\">Social Media</h6>\r\n");
      out.write("                                                <ul class=\"list-unstyled mb-0 d-flex\">\r\n");
      out.write("                                                    <li class=\"btn pl-0\">\r\n");
      out.write("                                                        <a class=\"link-black-100\" href=\"#\">\r\n");
      out.write("                                                            <span class=\"fab fa-instagram\"></span>\r\n");
      out.write("                                                        </a>\r\n");
      out.write("                                                    </li>\r\n");
      out.write("                                                    <li class=\"btn\">\r\n");
      out.write("                                                        <a class=\"link-black-100\" href=\"#\">\r\n");
      out.write("                                                            <span class=\"fab fa-facebook-f\"></span>\r\n");
      out.write("                                                        </a>\r\n");
      out.write("                                                    </li>\r\n");
      out.write("                                                    <li class=\"btn\">\r\n");
      out.write("                                                        <a class=\"link-black-100\" href=\"#\">\r\n");
      out.write("                                                            <span class=\"fab fa-youtube\"></span>\r\n");
      out.write("                                                        </a>\r\n");
      out.write("                                                    </li>\r\n");
      out.write("                                                    <li class=\"btn\">\r\n");
      out.write("                                                        <a class=\"link-black-100\" href=\"#\">\r\n");
      out.write("                                                            <span class=\"fab fa-twitter\"></span>\r\n");
      out.write("                                                        </a>\r\n");
      out.write("                                                    </li>\r\n");
      out.write("                                                    <li class=\"btn\">\r\n");
      out.write("                                                        <a class=\"link-black-100\" href=\"#\">\r\n");
      out.write("                                                            <span class=\"fab fa-pinterest\"></span>\r\n");
      out.write("                                                        </a>\r\n");
      out.write("                                                    </li>\r\n");
      out.write("                                                </ul>\r\n");
      out.write("                                            </div>\r\n");
      out.write("                                        </div>\r\n");
      out.write("                                    </div>\r\n");
      out.write("                                    <div class=\"mb-5 mb-xl-9 pb-xl-1\">\r\n");
      out.write("\r\n");
      out.write("                                    </div>\r\n");
      out.write("                                    <div>\r\n");
      out.write("                                        <h6 class=\"font-weight-medium font-size-10 mb-3 pb-xl-1\">Get In Touch</h6>\r\n");
      out.write("                                        <form class=\"js-validate\" novalidate=\"novalidate\">\r\n");
      out.write("                                            <div class=\"row\">\r\n");
      out.write("\r\n");
      out.write("                                                <div class=\"col-sm-6 mb-5\">\r\n");
      out.write("                                                    <div class=\"js-form-message\">\r\n");
      out.write("                                                        <label for=\"exampleFormControlInput1\">Name</label>\r\n");
      out.write("                                                        <input id=\"exampleFormControlInput1\" type=\"text\"\r\n");
      out.write("                                                               class=\"form-control rounded-0\" name=\"name\"\r\n");
      out.write("                                                               aria-label=\"Jack Wayley\" required data-error-class=\"u-has-error\"\r\n");
      out.write("                                                               data-msg=\"Please enter your name.\"\r\n");
      out.write("                                                               data-success-class=\"u-has-success\">\r\n");
      out.write("                                                    </div>\r\n");
      out.write("                                                </div>\r\n");
      out.write("\r\n");
      out.write("\r\n");
      out.write("                                                <div class=\"col-sm-6 mb-5\">\r\n");
      out.write("                                                    <div class=\"js-form-message\">\r\n");
      out.write("                                                        <label for=\"exampleFormControlInput2\">Email</label>\r\n");
      out.write("                                                        <input id=\"exampleFormControlInput2\" type=\"email\"\r\n");
      out.write("                                                               class=\"form-control rounded-0\" name=\"email\"\r\n");
      out.write("                                                               aria-label=\"jackwayley@gmail.com\" required\r\n");
      out.write("                                                               data-msg=\"Please enter a valid email address.\"\r\n");
      out.write("                                                               data-error-class=\"u-has-error\"\r\n");
      out.write("                                                               data-success-class=\"u-has-success\">\r\n");
      out.write("                                                    </div>\r\n");
      out.write("                                                </div>\r\n");
      out.write("\r\n");
      out.write("                                                <div class=\"col-sm-12 mb-5\">\r\n");
      out.write("                                                    <div class=\"js-form-message\">\r\n");
      out.write("                                                        <label for=\"exampleFormControlInput3\">Subject</label>\r\n");
      out.write("                                                        <input id=\"exampleFormControlInput3\" type=\"email\"\r\n");
      out.write("                                                               class=\"form-control rounded-0\" name=\"email\"\r\n");
      out.write("                                                               aria-label=\"jackwayley@gmail.com\" required\r\n");
      out.write("                                                               data-msg=\"Please enter a valid email address.\"\r\n");
      out.write("                                                               data-error-class=\"u-has-error\"\r\n");
      out.write("                                                               data-success-class=\"u-has-success\">\r\n");
      out.write("                                                    </div>\r\n");
      out.write("                                                </div>\r\n");
      out.write("                                                <div class=\"col-sm-12 mb-5\">\r\n");
      out.write("                                                    <div class=\"js-form-message\">\r\n");
      out.write("                                                        <div class=\"input-group flex-column\">\r\n");
      out.write("                                                            <label for=\"exampleFormControlInput4\">Details please! Your review\r\n");
      out.write("                                                                helps other shoppers.</label>\r\n");
      out.write("                                                            <textarea id=\"exampleFormControlInput4\"\r\n");
      out.write("                                                                      class=\"form-control rounded-0 pl-3 font-size-2 placeholder-color-3\"\r\n");
      out.write("                                                                      rows=\"6\" cols=\"77\" name=\"text\"\r\n");
      out.write("                                                                      placeholder=\"What did you like or dislike? What should other shoppers know before buying?\"\r\n");
      out.write("                                                                      aria-label=\"Hi there, I would like to ...\"\r\n");
      out.write("                                                                      required data-msg=\"Please enter a reason.\"\r\n");
      out.write("                                                                      data-error-class=\"u-has-error\"\r\n");
      out.write("                                                                      data-success-class=\"u-has-success\"></textarea>\r\n");
      out.write("                                                        </div>\r\n");
      out.write("                                                    </div>\r\n");
      out.write("                                                </div>\r\n");
      out.write("\r\n");
      out.write("                                                <div class=\"col d-flex justify-content-lg-start\">\r\n");
      out.write("                                                    <button type=\"submit\"\r\n");
      out.write("                                                            class=\"btn btn-wide btn-dark text-white rounded-0 transition-3d-hover height-60\">\r\n");
      out.write("                                                        Sumbit Message\r\n");
      out.write("                                                    </button>\r\n");
      out.write("                                                </div>\r\n");
      out.write("                                            </div>\r\n");
      out.write("                                        </form>\r\n");
      out.write("                                    </div>\r\n");
      out.write("                                </div>\r\n");
      out.write("                            </div>\r\n");
      out.write("                        </div>\r\n");
      out.write("                    </div>\r\n");
      out.write("                </div>\r\n");
      out.write("            </div>\r\n");
      out.write("        </main>\r\n");
      out.write("    ");
      return false;
    }
    public void invoke( java.io.Writer writer )
      throws jakarta.servlet.jsp.JspException
    {
      jakarta.servlet.jsp.JspWriter out = null;
      if( writer != null ) {
        out = this.jspContext.pushBody(writer);
      } else {
        out = this.jspContext.getOut();
      }
      try {
        Object _jspx_saved_JspContext = this.jspContext.getELContext().getContext(jakarta.servlet.jsp.JspContext.class);
        this.jspContext.getELContext().putContext(jakarta.servlet.jsp.JspContext.class,this.jspContext);
        switch( this.discriminator ) {
          case 0:
            invoke0( out );
            break;
          case 1:
            invoke1( out );
            break;
          case 2:
            invoke2( out );
            break;
        }
        jspContext.getELContext().putContext(jakarta.servlet.jsp.JspContext.class,_jspx_saved_JspContext);
      }
      catch( java.lang.Throwable e ) {
        if (e instanceof jakarta.servlet.jsp.SkipPageException)
            throw (jakarta.servlet.jsp.SkipPageException) e;
        throw new jakarta.servlet.jsp.JspException( e );
      }
      finally {
        if( writer != null ) {
          this.jspContext.popBody();
        }
      }
    }
  }
}
