/*
 * Generated by the Jasper component of Apache Tomcat
 * Version: Apache Tomcat/10.1.7
 * Generated at: 2023-08-28 17:41:10 UTC
 * Note: The last modified time of this file was set to
 *       the last modified time of the source file after
 *       generation to assist with modification tracking.
 */
package org.apache.jsp.WEB_002dINF.views.frontend;

import jakarta.servlet.*;
import jakarta.servlet.http.*;
import jakarta.servlet.jsp.*;

public final class faq_jsp extends org.apache.jasper.runtime.HttpJspBase
    implements org.apache.jasper.runtime.JspSourceDependent,
                 org.apache.jasper.runtime.JspSourceImports,
                 org.apache.jasper.runtime.JspSourceDirectives {

  private static final jakarta.servlet.jsp.JspFactory _jspxFactory =
          jakarta.servlet.jsp.JspFactory.getDefaultFactory();

  private static java.util.Map<java.lang.String,java.lang.Long> _jspx_dependants;

  private static final java.util.Set<java.lang.String> _jspx_imports_packages;

  private static final java.util.Set<java.lang.String> _jspx_imports_classes;

  static {
    _jspx_imports_packages = new java.util.HashSet<>();
    _jspx_imports_packages.add("jakarta.servlet");
    _jspx_imports_packages.add("jakarta.servlet.http");
    _jspx_imports_packages.add("jakarta.servlet.jsp");
    _jspx_imports_classes = null;
  }

  private volatile jakarta.el.ExpressionFactory _el_expressionfactory;
  private volatile org.apache.tomcat.InstanceManager _jsp_instancemanager;

  public java.util.Map<java.lang.String,java.lang.Long> getDependants() {
    return _jspx_dependants;
  }

  public java.util.Set<java.lang.String> getPackageImports() {
    return _jspx_imports_packages;
  }

  public java.util.Set<java.lang.String> getClassImports() {
    return _jspx_imports_classes;
  }

  public boolean getErrorOnELNotFound() {
    return false;
  }

  public jakarta.el.ExpressionFactory _jsp_getExpressionFactory() {
    if (_el_expressionfactory == null) {
      synchronized (this) {
        if (_el_expressionfactory == null) {
          _el_expressionfactory = _jspxFactory.getJspApplicationContext(getServletConfig().getServletContext()).getExpressionFactory();
        }
      }
    }
    return _el_expressionfactory;
  }

  public org.apache.tomcat.InstanceManager _jsp_getInstanceManager() {
    if (_jsp_instancemanager == null) {
      synchronized (this) {
        if (_jsp_instancemanager == null) {
          _jsp_instancemanager = org.apache.jasper.runtime.InstanceManagerFactory.getInstanceManager(getServletConfig());
        }
      }
    }
    return _jsp_instancemanager;
  }

  public void _jspInit() {
  }

  public void _jspDestroy() {
  }

  public void _jspService(final jakarta.servlet.http.HttpServletRequest request, final jakarta.servlet.http.HttpServletResponse response)
      throws java.io.IOException, jakarta.servlet.ServletException {

    if (!jakarta.servlet.DispatcherType.ERROR.equals(request.getDispatcherType())) {
      final java.lang.String _jspx_method = request.getMethod();
      if ("OPTIONS".equals(_jspx_method)) {
        response.setHeader("Allow","GET, HEAD, POST, OPTIONS");
        return;
      }
      if (!"GET".equals(_jspx_method) && !"POST".equals(_jspx_method) && !"HEAD".equals(_jspx_method)) {
        response.setHeader("Allow","GET, HEAD, POST, OPTIONS");
        response.sendError(HttpServletResponse.SC_METHOD_NOT_ALLOWED, "JSPs only permit GET, POST or HEAD. Jasper also permits OPTIONS");
        return;
      }
    }

    final jakarta.servlet.jsp.PageContext pageContext;
    jakarta.servlet.http.HttpSession session = null;
    final jakarta.servlet.ServletContext application;
    final jakarta.servlet.ServletConfig config;
    jakarta.servlet.jsp.JspWriter out = null;
    final java.lang.Object page = this;
    jakarta.servlet.jsp.JspWriter _jspx_out = null;
    jakarta.servlet.jsp.PageContext _jspx_page_context = null;


    try {
      response.setContentType("text/html;charset=UTF-8");
      pageContext = _jspxFactory.getPageContext(this, request, response,
      			null, true, 8192, true);
      _jspx_page_context = pageContext;
      application = pageContext.getServletContext();
      config = pageContext.getServletConfig();
      session = pageContext.getSession();
      out = pageContext.getOut();
      _jspx_out = out;

      out.write("\r\n");
      out.write("<!DOCTYPE html>\r\n");
      out.write("<html lang=\"en\">\r\n");
      out.write("\r\n");
      out.write("<head>\r\n");
      out.write("\r\n");
      out.write("    <title>FAQ's | eBookStore</title>\r\n");
      out.write("\r\n");
      out.write("    <meta charset=\"utf-8\">\r\n");
      out.write("    <meta name=\"viewport\" content=\"width=device-width, initial-scale=1, shrink-to-fit=no\">\r\n");
      out.write("\r\n");
      out.write("    <link rel=\"shortcut icon\" href=\"assets/img/favicon.png\">\r\n");
      out.write("\r\n");
      out.write("    <link href=\"https://fonts.googleapis.com/css2?family=Inter:wght@400;500;700&amp;display=swap\" rel=\"stylesheet\">\r\n");
      out.write("    <link rel=\"stylesheet\" href=\"https://use.fontawesome.com/releases/v6.1.1/css/all.css\"/>\r\n");
      out.write("\r\n");
      out.write("    <link rel=\"stylesheet\" href=\"assets/vendor/font-awesome/css/fontawesome-all.min.css\">\r\n");
      out.write("    <link rel=\"stylesheet\" href=\"assets/vendor/flaticon/font/flaticon.css\">\r\n");
      out.write("    <link rel=\"stylesheet\" href=\"assets/vendor/animate.css/animate.css\">\r\n");
      out.write("    <link rel=\"stylesheet\" href=\"assets/vendor/bootstrap-select/dist/css/bootstrap-select.min.css\">\r\n");
      out.write("    <link rel=\"stylesheet\" href=\"assets/vendor/slick-carousel/slick/slick.css\"/>\r\n");
      out.write("    <link rel=\"stylesheet\" href=\"assets/vendor/malihu-custom-scrollbar-plugin/jquery.mCustomScrollbar.css\">\r\n");
      out.write("\r\n");
      out.write("    <link rel=\"stylesheet\" href=\"assets/css/theme.css\">\r\n");
      out.write("</head>\r\n");
      out.write("\r\n");
      out.write("<body>\r\n");
      org.apache.jasper.runtime.JspRuntimeLibrary.include(request, response, "include/header.jsp", out, false);
      out.write("\r\n");
      out.write("<main id=\"content\">\r\n");
      out.write("    <div class=\"container\">\r\n");
      out.write("        <div class=\"py-4 py-lg-5 py-xl-8\">\r\n");
      out.write("            <h6 class=\"font-weight-medium font-size-7 font-size-xs-25 text-center\">Frequently Asked Questions</h6>\r\n");
      out.write("        </div>\r\n");
      out.write("        <div class=\"col-lg-8 mx-auto\">\r\n");
      out.write("            <div class=\"space-bottom-2 space-bottom-lg-3 faq-accordion\">\r\n");
      out.write("                <div class=\"pb-lg-1\">\r\n");
      out.write("                    <div class=\"mb-8 pb-1\">\r\n");
      out.write("                        <h6 class=\"font-weight-medium font-size-4 mb-5\">Shopping</h6>\r\n");
      out.write("\r\n");
      out.write("                        <div id=\"basicsAccordion\">\r\n");
      out.write("\r\n");
      out.write("                            <div class=\"card rounded-0 border-0\">\r\n");
      out.write("                                <div class=\"card-collapse card-header p-0 bg-transparent border-bottom-0\"\r\n");
      out.write("                                     id=\"basicsHeadingOne\">\r\n");
      out.write("                                    <button type=\"button\"\r\n");
      out.write("                                            class=\"collapse-link btn btn-block d-flex align-items-center justify-content-between card-btn py-3 px-0 px-md-4 border rounded-0 shadow-none\"\r\n");
      out.write("                                            data-toggle=\"collapse\" data-target=\"#basicsCollapseOne\" aria-expanded=\"true\"\r\n");
      out.write("                                            aria-controls=\"basicsCollapseOne\">\r\n");
      out.write("                                        <span class=\"mx-md-1\">Delivery charges for orders from the Online Shop?</span>\r\n");
      out.write("                                        <svg class=\"minus\" xmlns=\"http://www.w3.org/2000/svg\"\r\n");
      out.write("                                             xmlns:xlink=\"http://www.w3.org/1999/xlink\" width=\"15px\" height=\"2px\">\r\n");
      out.write("                                            <path fill-rule=\"evenodd\" fill=\"rgb(22, 22, 25)\"\r\n");
      out.write("                                                  d=\"M0.000,-0.000 L15.000,-0.000 L15.000,2.000 L0.000,2.000 L0.000,-0.000 Z\"/>\r\n");
      out.write("                                        </svg>\r\n");
      out.write("                                        <svg class=\"plus\" xmlns=\"http://www.w3.org/2000/svg\"\r\n");
      out.write("                                             xmlns:xlink=\"http://www.w3.org/1999/xlink\" width=\"15px\" height=\"15px\">\r\n");
      out.write("                                            <path fill-rule=\"evenodd\" fill=\"rgb(22, 22, 25)\"\r\n");
      out.write("                                                  d=\"M15.000,8.000 L9.000,8.000 L9.000,15.000 L7.000,15.000 L7.000,8.000 L0.000,8.000 L0.000,6.000 L7.000,6.000 L7.000,-0.000 L9.000,-0.000 L9.000,6.000 L15.000,6.000 L15.000,8.000 Z\"/>\r\n");
      out.write("                                        </svg>\r\n");
      out.write("                                    </button>\r\n");
      out.write("                                </div>\r\n");
      out.write("                                <div id=\"basicsCollapseOne\" class=\"collapse show\" aria-labelledby=\"basicsHeadingOne\"\r\n");
      out.write("                                     data-parent=\"#basicsAccordion\">\r\n");
      out.write("                                    <div class=\"card-body p-3 p-md-4\">\r\n");
      out.write("                                        <div class=\"mx-md-1\">\r\n");
      out.write("                                            <p class=\"mb-4 pb-1 font-size-2\">A placerat ac vestibulum integer vehicula\r\n");
      out.write("                                                suspendisse nostra aptent fermentum tempor a magna erat ligula\r\n");
      out.write("                                                parturient curae sem conubia vestibulum ac inceptos sodales condimentum\r\n");
      out.write("                                                cursus nunc mi consectetur\r\n");
      out.write("                                                condimentum.\r\n");
      out.write("                                            </p>\r\n");
      out.write("                                            <span class=\"font-size-2\">Tristique parturient nulla ullamcorper at ullamcorper non orci iaculis neque augue.</span>\r\n");
      out.write("                                        </div>\r\n");
      out.write("                                    </div>\r\n");
      out.write("                                </div>\r\n");
      out.write("                            </div>\r\n");
      out.write("\r\n");
      out.write("\r\n");
      out.write("                            <div class=\"card rounded-0 border-0 \">\r\n");
      out.write("                                <div class=\"card-header card-collapse p-0 bg-transparent border-bottom-0\"\r\n");
      out.write("                                     id=\"basicsHeadingTwo\">\r\n");
      out.write("                                    <h5 class=\"mb-0\">\r\n");
      out.write("                                        <button type=\"button\"\r\n");
      out.write("                                                class=\"collapse-link btn btn-block d-flex align-items-center justify-content-between card-btn py-3 px-0 px-md-4 border rounded-0 shadow-none mt-minus-1\"\r\n");
      out.write("                                                data-toggle=\"collapse\" data-target=\"#basicsCollapseTwo\"\r\n");
      out.write("                                                aria-expanded=\"false\"\r\n");
      out.write("                                                aria-controls=\"basicsCollapseTwo\">\r\n");
      out.write("                                            <span class=\"mx-md-1\">How long will delivery take?</span>\r\n");
      out.write("                                            <svg class=\"minus\" xmlns=\"http://www.w3.org/2000/svg\"\r\n");
      out.write("                                                 xmlns:xlink=\"http://www.w3.org/1999/xlink\" width=\"15px\" height=\"2px\">\r\n");
      out.write("                                                <path fill-rule=\"evenodd\" fill=\"rgb(22, 22, 25)\"\r\n");
      out.write("                                                      d=\"M0.000,-0.000 L15.000,-0.000 L15.000,2.000 L0.000,2.000 L0.000,-0.000 Z\"/>\r\n");
      out.write("                                            </svg>\r\n");
      out.write("                                            <svg class=\"plus\" xmlns=\"http://www.w3.org/2000/svg\"\r\n");
      out.write("                                                 xmlns:xlink=\"http://www.w3.org/1999/xlink\" width=\"15px\" height=\"15px\">\r\n");
      out.write("                                                <path fill-rule=\"evenodd\" fill=\"rgb(22, 22, 25)\"\r\n");
      out.write("                                                      d=\"M15.000,8.000 L9.000,8.000 L9.000,15.000 L7.000,15.000 L7.000,8.000 L0.000,8.000 L0.000,6.000 L7.000,6.000 L7.000,-0.000 L9.000,-0.000 L9.000,6.000 L15.000,6.000 L15.000,8.000 Z\"/>\r\n");
      out.write("                                            </svg>\r\n");
      out.write("                                        </button>\r\n");
      out.write("                                    </h5>\r\n");
      out.write("                                </div>\r\n");
      out.write("                                <div id=\"basicsCollapseTwo\" class=\"collapse\" aria-labelledby=\"basicsHeadingTwo\"\r\n");
      out.write("                                     data-parent=\"#basicsAccordion\">\r\n");
      out.write("                                    <div class=\"card-body p-3 p-md-4\">\r\n");
      out.write("                                        <div class=\" m-1\">\r\n");
      out.write("                                            <p class=\"mb-4 pb-1 font-size-2\">A placerat ac vestibulum integer vehicula\r\n");
      out.write("                                                suspendisse nostra aptent fermentum tempor a magna erat ligula\r\n");
      out.write("                                                parturient curae sem conubia vestibulum ac inceptos sodales condimentum\r\n");
      out.write("                                                cursus nunc mi consectetur\r\n");
      out.write("                                                condimentum.\r\n");
      out.write("                                            </p>\r\n");
      out.write("                                            <span class=\"font-size-2\">Tristique parturient nulla ullamcorper at ullamcorper non orci iaculis neque augue.</span>\r\n");
      out.write("                                        </div>\r\n");
      out.write("                                    </div>\r\n");
      out.write("                                </div>\r\n");
      out.write("                            </div>\r\n");
      out.write("\r\n");
      out.write("\r\n");
      out.write("                            <div class=\"card rounded-0 border-0\">\r\n");
      out.write("                                <div class=\"card-header card-collapse p-0 bg-transparent border-bottom-0\"\r\n");
      out.write("                                     id=\"basicsHeadingThree\">\r\n");
      out.write("                                    <button type=\"button\"\r\n");
      out.write("                                            class=\"collapse-link btn btn-block d-flex align-items-center justify-content-between card-btn py-3 px-0 px-md-4 border rounded-0 shadow-none mt-minus-1\"\r\n");
      out.write("                                            data-toggle=\"collapse\" data-target=\"#basicsCollapseThree\"\r\n");
      out.write("                                            aria-expanded=\"false\"\r\n");
      out.write("                                            aria-controls=\"basicsCollapseThree\">\r\n");
      out.write("                                        <span class=\"mx-md-1\">Do I receive an invoice for my order?</span>\r\n");
      out.write("                                        <svg class=\"minus\" xmlns=\"http://www.w3.org/2000/svg\"\r\n");
      out.write("                                             xmlns:xlink=\"http://www.w3.org/1999/xlink\" width=\"15px\" height=\"2px\">\r\n");
      out.write("                                            <path fill-rule=\"evenodd\" fill=\"rgb(22, 22, 25)\"\r\n");
      out.write("                                                  d=\"M0.000,-0.000 L15.000,-0.000 L15.000,2.000 L0.000,2.000 L0.000,-0.000 Z\"/>\r\n");
      out.write("                                        </svg>\r\n");
      out.write("                                        <svg class=\"plus\" xmlns=\"http://www.w3.org/2000/svg\"\r\n");
      out.write("                                             xmlns:xlink=\"http://www.w3.org/1999/xlink\" width=\"15px\" height=\"15px\">\r\n");
      out.write("                                            <path fill-rule=\"evenodd\" fill=\"rgb(22, 22, 25)\"\r\n");
      out.write("                                                  d=\"M15.000,8.000 L9.000,8.000 L9.000,15.000 L7.000,15.000 L7.000,8.000 L0.000,8.000 L0.000,6.000 L7.000,6.000 L7.000,-0.000 L9.000,-0.000 L9.000,6.000 L15.000,6.000 L15.000,8.000 Z\"/>\r\n");
      out.write("                                        </svg>\r\n");
      out.write("                                    </button>\r\n");
      out.write("                                </div>\r\n");
      out.write("                                <div id=\"basicsCollapseThree\" class=\"collapse\" aria-labelledby=\"basicsHeadingThree\"\r\n");
      out.write("                                     data-parent=\"#basicsAccordion\">\r\n");
      out.write("                                    <div class=\"card-body p-3 p-md-4\">\r\n");
      out.write("                                        <div class=\"mx-md-1\">\r\n");
      out.write("                                            <p class=\"mb-4 pb-1 font-size-2\">A placerat ac vestibulum integer vehicula\r\n");
      out.write("                                                suspendisse nostra aptent fermentum tempor a magna erat ligula\r\n");
      out.write("                                                parturient curae sem conubia vestibulum ac inceptos sodales condimentum\r\n");
      out.write("                                                cursus nunc mi consectetur\r\n");
      out.write("                                                condimentum.\r\n");
      out.write("                                            </p>\r\n");
      out.write("                                            <span class=\"font-size-2\">Tristique parturient nulla ullamcorper at ullamcorper non orci iaculis neque augue.</span>\r\n");
      out.write("                                        </div>\r\n");
      out.write("                                    </div>\r\n");
      out.write("                                </div>\r\n");
      out.write("                            </div>\r\n");
      out.write("\r\n");
      out.write("\r\n");
      out.write("                            <div class=\"card rounded-0 border-0\">\r\n");
      out.write("                                <div class=\"card-header card-collapse p-0 bg-transparent border-bottom-0\"\r\n");
      out.write("                                     id=\"basicsHeadingFour\">\r\n");
      out.write("                                    <button type=\"button\"\r\n");
      out.write("                                            class=\"collapse-link btn btn-block d-flex align-items-center justify-content-between card-btn py-3 px-0 px-md-4 border rounded-0 shadow-none mt-minus-1\"\r\n");
      out.write("                                            data-toggle=\"collapse\" data-target=\"#basicsCollapseFour\"\r\n");
      out.write("                                            aria-expanded=\"false\"\r\n");
      out.write("                                            aria-controls=\"basicsCollapseFour\">\r\n");
      out.write("                                        <span class=\"mx-1\">Tellus ridicdiam eleifend id ullamcorper?</span>\r\n");
      out.write("                                        <svg class=\"minus\" xmlns=\"http://www.w3.org/2000/svg\"\r\n");
      out.write("                                             xmlns:xlink=\"http://www.w3.org/1999/xlink\" width=\"15px\" height=\"2px\">\r\n");
      out.write("                                            <path fill-rule=\"evenodd\" fill=\"rgb(22, 22, 25)\"\r\n");
      out.write("                                                  d=\"M0.000,-0.000 L15.000,-0.000 L15.000,2.000 L0.000,2.000 L0.000,-0.000 Z\"/>\r\n");
      out.write("                                        </svg>\r\n");
      out.write("                                        <svg class=\"plus\" xmlns=\"http://www.w3.org/2000/svg\"\r\n");
      out.write("                                             xmlns:xlink=\"http://www.w3.org/1999/xlink\" width=\"15px\" height=\"15px\">\r\n");
      out.write("                                            <path fill-rule=\"evenodd\" fill=\"rgb(22, 22, 25)\"\r\n");
      out.write("                                                  d=\"M15.000,8.000 L9.000,8.000 L9.000,15.000 L7.000,15.000 L7.000,8.000 L0.000,8.000 L0.000,6.000 L7.000,6.000 L7.000,-0.000 L9.000,-0.000 L9.000,6.000 L15.000,6.000 L15.000,8.000 Z\"/>\r\n");
      out.write("                                        </svg>\r\n");
      out.write("                                    </button>\r\n");
      out.write("                                </div>\r\n");
      out.write("                                <div id=\"basicsCollapseFour\" class=\"collapse\" aria-labelledby=\"basicsHeadingFour\"\r\n");
      out.write("                                     data-parent=\"#basicsAccordion\">\r\n");
      out.write("                                    <div class=\"card-body p-3 p-md-4\">\r\n");
      out.write("                                        <div class=\"mx-md-1\">\r\n");
      out.write("                                            <p class=\"mb-4 pb-1 font-size-2\">A placerat ac vestibulum integer vehicula\r\n");
      out.write("                                                suspendisse nostra aptent fermentum tempor a magna erat ligula\r\n");
      out.write("                                                parturient curae sem conubia vestibulum ac inceptos sodales condimentum\r\n");
      out.write("                                                cursus nunc mi consectetur\r\n");
      out.write("                                                condimentum.\r\n");
      out.write("                                            </p>\r\n");
      out.write("                                            <span class=\"font-size-2\">Tristique parturient nulla ullamcorper at ullamcorper non orci iaculis neque augue.</span>\r\n");
      out.write("                                        </div>\r\n");
      out.write("                                    </div>\r\n");
      out.write("                                </div>\r\n");
      out.write("                            </div>\r\n");
      out.write("\r\n");
      out.write("                        </div>\r\n");
      out.write("\r\n");
      out.write("                    </div>\r\n");
      out.write("                    <div>\r\n");
      out.write("                        <h6 class=\"font-weight-medium font-size-4 mb-5\">Payment</h6>\r\n");
      out.write("\r\n");
      out.write("                        <div id=\"basicsAccordion1\">\r\n");
      out.write("\r\n");
      out.write("                            <div class=\"card rounded-0 border-0\">\r\n");
      out.write("                                <div class=\"card-collapse card-header p-0 bg-transparent border-bottom-0\"\r\n");
      out.write("                                     id=\"basicsHeadingFive\">\r\n");
      out.write("                                    <button type=\"button\"\r\n");
      out.write("                                            class=\"collapse-link btn btn-block d-flex align-items-center justify-content-between card-btn py-3 px-0 px-md-4 border rounded-0 shadow-none\"\r\n");
      out.write("                                            data-toggle=\"collapse\" data-target=\"#basicsCollapseFive\"\r\n");
      out.write("                                            aria-expanded=\"true\" aria-controls=\"basicsCollapseFive\">\r\n");
      out.write("                                        <span class=\"mx-md-1\">When the order payment is taken of my bank account?</span>\r\n");
      out.write("                                        <svg class=\"minus\" xmlns=\"http://www.w3.org/2000/svg\"\r\n");
      out.write("                                             xmlns:xlink=\"http://www.w3.org/1999/xlink\" width=\"15px\" height=\"2px\">\r\n");
      out.write("                                            <path fill-rule=\"evenodd\" fill=\"rgb(22, 22, 25)\"\r\n");
      out.write("                                                  d=\"M0.000,-0.000 L15.000,-0.000 L15.000,2.000 L0.000,2.000 L0.000,-0.000 Z\"/>\r\n");
      out.write("                                        </svg>\r\n");
      out.write("                                        <svg class=\"plus\" xmlns=\"http://www.w3.org/2000/svg\"\r\n");
      out.write("                                             xmlns:xlink=\"http://www.w3.org/1999/xlink\" width=\"15px\" height=\"15px\">\r\n");
      out.write("                                            <path fill-rule=\"evenodd\" fill=\"rgb(22, 22, 25)\"\r\n");
      out.write("                                                  d=\"M15.000,8.000 L9.000,8.000 L9.000,15.000 L7.000,15.000 L7.000,8.000 L0.000,8.000 L0.000,6.000 L7.000,6.000 L7.000,-0.000 L9.000,-0.000 L9.000,6.000 L15.000,6.000 L15.000,8.000 Z\"/>\r\n");
      out.write("                                        </svg>\r\n");
      out.write("                                    </button>\r\n");
      out.write("                                </div>\r\n");
      out.write("                                <div id=\"basicsCollapseFive\" class=\"collapse show\" aria-labelledby=\"basicsHeadingFive\"\r\n");
      out.write("                                     data-parent=\"#basicsAccordion1\">\r\n");
      out.write("                                    <div class=\"card-body p-3 p-md-4\">\r\n");
      out.write("                                        <div class=\" mx-md-1\">\r\n");
      out.write("                                            <p class=\"mb-4 pb-1 font-size-2\">A placerat ac vestibulum integer vehicula\r\n");
      out.write("                                                suspendisse nostra aptent fermentum tempor a magna erat ligula\r\n");
      out.write("                                                parturient curae sem conubia vestibulum ac inceptos sodales condimentum\r\n");
      out.write("                                                cursus nunc mi consectetur\r\n");
      out.write("                                                condimentum.\r\n");
      out.write("                                            </p>\r\n");
      out.write("                                            <span class=\"font-size-2\">Tristique parturient nulla ullamcorper at ullamcorper non orci iaculis neque augue.</span>\r\n");
      out.write("                                        </div>\r\n");
      out.write("                                    </div>\r\n");
      out.write("                                </div>\r\n");
      out.write("                            </div>\r\n");
      out.write("\r\n");
      out.write("\r\n");
      out.write("                            <div class=\"card rounded-0 border-0 \">\r\n");
      out.write("                                <div class=\"card-header card-collapse p-0 bg-transparent border-bottom-0\"\r\n");
      out.write("                                     id=\"basicsHeadingSix\">\r\n");
      out.write("                                    <h5 class=\"mb-0\">\r\n");
      out.write("                                        <button type=\"button\"\r\n");
      out.write("                                                class=\"collapse-link btn btn-block d-flex align-items-center justify-content-between card-btn py-3 px-0 px-md-4 border rounded-0 shadow-none mt-minus-1\"\r\n");
      out.write("                                                data-toggle=\"collapse\" data-target=\"#basicsCollapseSix\"\r\n");
      out.write("                                                aria-expanded=\"false\"\r\n");
      out.write("                                                aria-controls=\"basicsCollapseSix\">\r\n");
      out.write("                                            <span class=\"mx-1\">What is wishlist?</span>\r\n");
      out.write("                                            <svg class=\"minus\" xmlns=\"http://www.w3.org/2000/svg\"\r\n");
      out.write("                                                 xmlns:xlink=\"http://www.w3.org/1999/xlink\" width=\"15px\" height=\"2px\">\r\n");
      out.write("                                                <path fill-rule=\"evenodd\" fill=\"rgb(22, 22, 25)\"\r\n");
      out.write("                                                      d=\"M0.000,-0.000 L15.000,-0.000 L15.000,2.000 L0.000,2.000 L0.000,-0.000 Z\"/>\r\n");
      out.write("                                            </svg>\r\n");
      out.write("                                            <svg class=\"plus\" xmlns=\"http://www.w3.org/2000/svg\"\r\n");
      out.write("                                                 xmlns:xlink=\"http://www.w3.org/1999/xlink\" width=\"15px\" height=\"15px\">\r\n");
      out.write("                                                <path fill-rule=\"evenodd\" fill=\"rgb(22, 22, 25)\"\r\n");
      out.write("                                                      d=\"M15.000,8.000 L9.000,8.000 L9.000,15.000 L7.000,15.000 L7.000,8.000 L0.000,8.000 L0.000,6.000 L7.000,6.000 L7.000,-0.000 L9.000,-0.000 L9.000,6.000 L15.000,6.000 L15.000,8.000 Z\"/>\r\n");
      out.write("                                            </svg>\r\n");
      out.write("                                        </button>\r\n");
      out.write("                                    </h5>\r\n");
      out.write("                                </div>\r\n");
      out.write("                                <div id=\"basicsCollapseSix\" class=\"collapse\" aria-labelledby=\"basicsHeadingSix\"\r\n");
      out.write("                                     data-parent=\"#basicsAccordion1\">\r\n");
      out.write("                                    <div class=\"card-body p-3 p-md-4\">\r\n");
      out.write("                                        <div class=\"mx-md-1\">\r\n");
      out.write("                                            <p class=\"mb-4 pb-1 font-size-2\">A placerat ac vestibulum integer vehicula\r\n");
      out.write("                                                suspendisse nostra aptent fermentum tempor a magna erat ligula\r\n");
      out.write("                                                parturient curae sem conubia vestibulum ac inceptos sodales condimentum\r\n");
      out.write("                                                cursus nunc mi consectetur\r\n");
      out.write("                                                condimentum.\r\n");
      out.write("                                            </p>\r\n");
      out.write("                                            <span class=\"font-size-2\">Tristique parturient nulla ullamcorper at ullamcorper non orci iaculis neque augue.</span>\r\n");
      out.write("                                        </div>\r\n");
      out.write("                                    </div>\r\n");
      out.write("                                </div>\r\n");
      out.write("                            </div>\r\n");
      out.write("\r\n");
      out.write("\r\n");
      out.write("                            <div class=\"card rounded-0 border-0\">\r\n");
      out.write("                                <div class=\"card-header card-collapse p-0 bg-transparent border-bottom-0\"\r\n");
      out.write("                                     id=\"basicsHeadingSeven\">\r\n");
      out.write("                                    <button type=\"button\"\r\n");
      out.write("                                            class=\"collapse-link btn btn-block d-flex align-items-center justify-content-between card-btn py-3 px-0 px-md-4 border rounded-0 shadow-none mt-minus-1\"\r\n");
      out.write("                                            data-toggle=\"collapse\" data-target=\"#basicsCollapseSeven\"\r\n");
      out.write("                                            aria-expanded=\"false\"\r\n");
      out.write("                                            aria-controls=\"basicsCollapseSeven\">\r\n");
      out.write("                                        <span class=\"mx-md-1\">What should I do if I receive a damaged or wrong product?</span>\r\n");
      out.write("                                        <svg class=\"minus\" xmlns=\"http://www.w3.org/2000/svg\"\r\n");
      out.write("                                             xmlns:xlink=\"http://www.w3.org/1999/xlink\" width=\"15px\" height=\"2px\">\r\n");
      out.write("                                            <path fill-rule=\"evenodd\" fill=\"rgb(22, 22, 25)\"\r\n");
      out.write("                                                  d=\"M0.000,-0.000 L15.000,-0.000 L15.000,2.000 L0.000,2.000 L0.000,-0.000 Z\"/>\r\n");
      out.write("                                        </svg>\r\n");
      out.write("                                        <svg class=\"plus\" xmlns=\"http://www.w3.org/2000/svg\"\r\n");
      out.write("                                             xmlns:xlink=\"http://www.w3.org/1999/xlink\" width=\"15px\" height=\"15px\">\r\n");
      out.write("                                            <path fill-rule=\"evenodd\" fill=\"rgb(22, 22, 25)\"\r\n");
      out.write("                                                  d=\"M15.000,8.000 L9.000,8.000 L9.000,15.000 L7.000,15.000 L7.000,8.000 L0.000,8.000 L0.000,6.000 L7.000,6.000 L7.000,-0.000 L9.000,-0.000 L9.000,6.000 L15.000,6.000 L15.000,8.000 Z\"/>\r\n");
      out.write("                                        </svg>\r\n");
      out.write("                                    </button>\r\n");
      out.write("                                </div>\r\n");
      out.write("                                <div id=\"basicsCollapseSeven\" class=\"collapse\" aria-labelledby=\"basicsHeadingSeven\"\r\n");
      out.write("                                     data-parent=\"#basicsAccordion1\">\r\n");
      out.write("                                    <div class=\"card-body p-3 p-md-4\">\r\n");
      out.write("                                        <div class=\"mx-md-1\">\r\n");
      out.write("                                            <p class=\"mb-4 pb-1 font-size-2\">A placerat ac vestibulum integer vehicula\r\n");
      out.write("                                                suspendisse nostra aptent fermentum tempor a magna erat ligula\r\n");
      out.write("                                                parturient curae sem conubia vestibulum ac inceptos sodales condimentum\r\n");
      out.write("                                                cursus nunc mi consectetur\r\n");
      out.write("                                                condimentum.\r\n");
      out.write("                                            </p>\r\n");
      out.write("                                            <span class=\"font-size-2\">Tristique parturient nulla ullamcorper at ullamcorper non orci iaculis neque augue.</span>\r\n");
      out.write("                                        </div>\r\n");
      out.write("                                    </div>\r\n");
      out.write("                                </div>\r\n");
      out.write("                            </div>\r\n");
      out.write("\r\n");
      out.write("\r\n");
      out.write("                            <div class=\"card rounded-0 border-0\">\r\n");
      out.write("                                <div class=\"card-header card-collapse p-0 bg-transparent border-bottom-0\"\r\n");
      out.write("                                     id=\"basicsHeadingEight\">\r\n");
      out.write("                                    <button type=\"button\"\r\n");
      out.write("                                            class=\"collapse-link btn btn-block d-flex align-items-center justify-content-between card-btn py-3 px-0 px-md-4 border rounded-0 shadow-none mt-minus-1\"\r\n");
      out.write("                                            data-toggle=\"collapse\" data-target=\"#basicsCollapseEight\"\r\n");
      out.write("                                            aria-expanded=\"false\"\r\n");
      out.write("                                            aria-controls=\"basicsCollapseEight\">\r\n");
      out.write("                                        <span class=\"mx-md-1\">Can I change or cancel my order?</span>\r\n");
      out.write("                                        <svg class=\"minus\" xmlns=\"http://www.w3.org/2000/svg\"\r\n");
      out.write("                                             xmlns:xlink=\"http://www.w3.org/1999/xlink\" width=\"15px\" height=\"2px\">\r\n");
      out.write("                                            <path fill-rule=\"evenodd\" fill=\"rgb(22, 22, 25)\"\r\n");
      out.write("                                                  d=\"M0.000,-0.000 L15.000,-0.000 L15.000,2.000 L0.000,2.000 L0.000,-0.000 Z\"/>\r\n");
      out.write("                                        </svg>\r\n");
      out.write("                                        <svg class=\"plus\" xmlns=\"http://www.w3.org/2000/svg\"\r\n");
      out.write("                                             xmlns:xlink=\"http://www.w3.org/1999/xlink\" width=\"15px\" height=\"15px\">\r\n");
      out.write("                                            <path fill-rule=\"evenodd\" fill=\"rgb(22, 22, 25)\"\r\n");
      out.write("                                                  d=\"M15.000,8.000 L9.000,8.000 L9.000,15.000 L7.000,15.000 L7.000,8.000 L0.000,8.000 L0.000,6.000 L7.000,6.000 L7.000,-0.000 L9.000,-0.000 L9.000,6.000 L15.000,6.000 L15.000,8.000 Z\"/>\r\n");
      out.write("                                        </svg>\r\n");
      out.write("                                    </button>\r\n");
      out.write("                                </div>\r\n");
      out.write("                                <div id=\"basicsCollapseEight\" class=\"collapse\" aria-labelledby=\"basicsHeadingEight\"\r\n");
      out.write("                                     data-parent=\"#basicsAccordion1\">\r\n");
      out.write("                                    <div class=\"card-body p-3 p-md-4\">\r\n");
      out.write("                                        <div class=\"mx-md-1\">\r\n");
      out.write("                                            <p class=\"mb-4 pb-1 font-size-2\">A placerat ac vestibulum integer vehicula\r\n");
      out.write("                                                suspendisse nostra aptent fermentum tempor a magna erat ligula\r\n");
      out.write("                                                parturient curae sem conubia vestibulum ac inceptos sodales condimentum\r\n");
      out.write("                                                cursus nunc mi consectetur\r\n");
      out.write("                                                condimentum.\r\n");
      out.write("                                            </p>\r\n");
      out.write("                                            <span class=\"font-size-2\">Tristique parturient nulla ullamcorper at ullamcorper non orci iaculis neque augue.</span>\r\n");
      out.write("                                        </div>\r\n");
      out.write("                                    </div>\r\n");
      out.write("                                </div>\r\n");
      out.write("                            </div>\r\n");
      out.write("\r\n");
      out.write("\r\n");
      out.write("                            <div class=\"card rounded-0 border-0\">\r\n");
      out.write("                                <div class=\"card-header card-collapse p-0 bg-transparent border-bottom-0\"\r\n");
      out.write("                                     id=\"basicsHeadingNine\">\r\n");
      out.write("                                    <button type=\"button\"\r\n");
      out.write("                                            class=\"collapse-link btn btn-block d-flex align-items-center justify-content-between card-btn py-3 px-0 px-md-4 border rounded-0 shadow-none mt-minus-1\"\r\n");
      out.write("                                            data-toggle=\"collapse\" data-target=\"#basicsCollapseNine\"\r\n");
      out.write("                                            aria-expanded=\"false\"\r\n");
      out.write("                                            aria-controls=\"basicsCollapseNine\">\r\n");
      out.write("                                        <span class=\"mx-md-1\">What is \"package tracking\" in my orders?</span>\r\n");
      out.write("                                        <svg class=\"minus\" xmlns=\"http://www.w3.org/2000/svg\"\r\n");
      out.write("                                             xmlns:xlink=\"http://www.w3.org/1999/xlink\" width=\"15px\" height=\"2px\">\r\n");
      out.write("                                            <path fill-rule=\"evenodd\" fill=\"rgb(22, 22, 25)\"\r\n");
      out.write("                                                  d=\"M0.000,-0.000 L15.000,-0.000 L15.000,2.000 L0.000,2.000 L0.000,-0.000 Z\"/>\r\n");
      out.write("                                        </svg>\r\n");
      out.write("                                        <svg class=\"plus\" xmlns=\"http://www.w3.org/2000/svg\"\r\n");
      out.write("                                             xmlns:xlink=\"http://www.w3.org/1999/xlink\" width=\"15px\" height=\"15px\">\r\n");
      out.write("                                            <path fill-rule=\"evenodd\" fill=\"rgb(22, 22, 25)\"\r\n");
      out.write("                                                  d=\"M15.000,8.000 L9.000,8.000 L9.000,15.000 L7.000,15.000 L7.000,8.000 L0.000,8.000 L0.000,6.000 L7.000,6.000 L7.000,-0.000 L9.000,-0.000 L9.000,6.000 L15.000,6.000 L15.000,8.000 Z\"/>\r\n");
      out.write("                                        </svg>\r\n");
      out.write("                                    </button>\r\n");
      out.write("                                </div>\r\n");
      out.write("                                <div id=\"basicsCollapseNine\" class=\"collapse\" aria-labelledby=\"basicsHeadingNine\"\r\n");
      out.write("                                     data-parent=\"#basicsAccordion1\">\r\n");
      out.write("                                    <div class=\"card-body p-3 p-md-4\">\r\n");
      out.write("                                        <div class=\"mx-md-1\">\r\n");
      out.write("                                            <p class=\"mb-4 pb-1 font-size-2\">A placerat ac vestibulum integer vehicula\r\n");
      out.write("                                                suspendisse nostra aptent fermentum tempor a magna erat ligula\r\n");
      out.write("                                                parturient curae sem conubia vestibulum ac inceptos sodales condimentum\r\n");
      out.write("                                                cursus nunc mi consectetur\r\n");
      out.write("                                                condimentum.\r\n");
      out.write("                                            </p>\r\n");
      out.write("                                            <span class=\"font-size-2\">Tristique parturient nulla ullamcorper at ullamcorper non orci iaculis neque augue.</span>\r\n");
      out.write("                                        </div>\r\n");
      out.write("                                    </div>\r\n");
      out.write("                                </div>\r\n");
      out.write("                            </div>\r\n");
      out.write("\r\n");
      out.write("                        </div>\r\n");
      out.write("\r\n");
      out.write("                    </div>\r\n");
      out.write("                </div>\r\n");
      out.write("            </div>\r\n");
      out.write("        </div>\r\n");
      out.write("    </div>\r\n");
      out.write("</main>\r\n");
      org.apache.jasper.runtime.JspRuntimeLibrary.include(request, response, "include/footer.jsp", out, false);
      out.write("\r\n");
      out.write("\r\n");
      out.write("<script src=\"assets/vendor/jquery/dist/jquery.min.js\"></script>\r\n");
      out.write("<script src=\"assets/vendor/jquery-migrate/dist/jquery-migrate.min.js\"></script>\r\n");
      out.write("<script src=\"assets/vendor/popper.js/dist/umd/popper.min.js\"></script>\r\n");
      out.write("<script src=\"assets/vendor/bootstrap/bootstrap.min.js\"></script>\r\n");
      out.write("<script src=\"assets/vendor/bootstrap-select/dist/js/bootstrap-select.min.js\"></script>\r\n");
      out.write("<script src=\"assets/vendor/slick-carousel/slick/slick.min.js\"></script>\r\n");
      out.write("<script src=\"assets/vendor/multilevel-sliding-mobile-menu/dist/jquery.zeynep.js\"></script>\r\n");
      out.write("<script src=\"assets/vendor/malihu-custom-scrollbar-plugin/jquery.mCustomScrollbar.concat.min.js\"></script>\r\n");
      out.write("\r\n");
      out.write("<script src=\"assets/js/hs.core.js\"></script>\r\n");
      out.write("<script src=\"assets/js/components/hs.unfold.js\"></script>\r\n");
      out.write("<script src=\"assets/js/components/hs.malihu-scrollbar.js\"></script>\r\n");
      out.write("<script src=\"assets/js/components/hs.header.js\"></script>\r\n");
      out.write("<script src=\"assets/js/components/hs.slick-carousel.js\"></script>\r\n");
      out.write("<script src=\"assets/js/components/hs.selectpicker.js\"></script>\r\n");
      out.write("<script src=\"assets/js/components/hs.show-animation.js\"></script>\r\n");
      out.write("\r\n");
      out.write("\r\n");
      out.write("<script>\r\n");
      out.write("    $(document).on('ready', function () {\r\n");
      out.write("        // initialization of unfold component\r\n");
      out.write("        $.HSCore.components.HSUnfold.init($('[data-unfold-target]'));\r\n");
      out.write("\r\n");
      out.write("        // initialization of slick carousel\r\n");
      out.write("        $.HSCore.components.HSSlickCarousel.init('.js-slick-carousel');\r\n");
      out.write("\r\n");
      out.write("        // initialization of header\r\n");
      out.write("        $.HSCore.components.HSHeader.init($('#header'));\r\n");
      out.write("\r\n");
      out.write("        // initialization of malihu scrollbar\r\n");
      out.write("        $.HSCore.components.HSMalihuScrollBar.init($('.js-scrollbar'));\r\n");
      out.write("\r\n");
      out.write("        // initialization of show animations\r\n");
      out.write("        $.HSCore.components.HSShowAnimation.init('.js-animation-link');\r\n");
      out.write("\r\n");
      out.write("        // init zeynepjs\r\n");
      out.write("        var zeynep = $('.zeynep').zeynep({\r\n");
      out.write("            onClosed: function () {\r\n");
      out.write("                // enable main wrapper element clicks on any its children element\r\n");
      out.write("                $(\"body main\").attr(\"style\", \"\");\r\n");
      out.write("\r\n");
      out.write("                console.log('the side menu is closed.');\r\n");
      out.write("            },\r\n");
      out.write("            onOpened: function () {\r\n");
      out.write("                // disable main wrapper element clicks on any its children element\r\n");
      out.write("                $(\"body main\").attr(\"style\", \"pointer-events: none;\");\r\n");
      out.write("\r\n");
      out.write("                console.log('the side menu is opened.');\r\n");
      out.write("            }\r\n");
      out.write("        });\r\n");
      out.write("\r\n");
      out.write("        // handle zeynep overlay click\r\n");
      out.write("        $(\".zeynep-overlay\").click(function () {\r\n");
      out.write("            zeynep.close();\r\n");
      out.write("        });\r\n");
      out.write("\r\n");
      out.write("        // open side menu if the button is clicked\r\n");
      out.write("        $(\".cat-menu\").click(function () {\r\n");
      out.write("            if ($(\"html\").hasClass(\"zeynep-opened\")) {\r\n");
      out.write("                zeynep.close();\r\n");
      out.write("            } else {\r\n");
      out.write("                zeynep.open();\r\n");
      out.write("            }\r\n");
      out.write("        });\r\n");
      out.write("    });\r\n");
      out.write("</script>\r\n");
      out.write("</body>\r\n");
      out.write("\r\n");
      out.write("</html>");
    } catch (java.lang.Throwable t) {
      if (!(t instanceof jakarta.servlet.jsp.SkipPageException)){
        out = _jspx_out;
        if (out != null && out.getBufferSize() != 0)
          try {
            if (response.isCommitted()) {
              out.flush();
            } else {
              out.clearBuffer();
            }
          } catch (java.io.IOException e) {}
        if (_jspx_page_context != null) _jspx_page_context.handlePageException(t);
        else throw new ServletException(t);
      }
    } finally {
      _jspxFactory.releasePageContext(_jspx_page_context);
    }
  }
}
