/*
 * Generated by the Jasper component of Apache Tomcat
 * Version: Apache Tomcat/10.1.7
 * Generated at: 2023-08-28 17:08:03 UTC
 * Note: The last modified time of this file was set to
 *       the last modified time of the source file after
 *       generation to assist with modification tracking.
 */
package org.apache.jsp.WEB_002dINF.views.frontend;

import jakarta.servlet.*;
import jakarta.servlet.http.*;
import jakarta.servlet.jsp.*;

public final class myAccountDetails_jsp extends org.apache.jasper.runtime.HttpJspBase
    implements org.apache.jasper.runtime.JspSourceDependent,
                 org.apache.jasper.runtime.JspSourceImports,
                 org.apache.jasper.runtime.JspSourceDirectives {

  private static final jakarta.servlet.jsp.JspFactory _jspxFactory =
          jakarta.servlet.jsp.JspFactory.getDefaultFactory();

  private static java.util.Map<java.lang.String,java.lang.Long> _jspx_dependants;

  private static final java.util.Set<java.lang.String> _jspx_imports_packages;

  private static final java.util.Set<java.lang.String> _jspx_imports_classes;

  static {
    _jspx_imports_packages = new java.util.HashSet<>();
    _jspx_imports_packages.add("jakarta.servlet");
    _jspx_imports_packages.add("jakarta.servlet.http");
    _jspx_imports_packages.add("jakarta.servlet.jsp");
    _jspx_imports_classes = null;
  }

  private volatile jakarta.el.ExpressionFactory _el_expressionfactory;
  private volatile org.apache.tomcat.InstanceManager _jsp_instancemanager;

  public java.util.Map<java.lang.String,java.lang.Long> getDependants() {
    return _jspx_dependants;
  }

  public java.util.Set<java.lang.String> getPackageImports() {
    return _jspx_imports_packages;
  }

  public java.util.Set<java.lang.String> getClassImports() {
    return _jspx_imports_classes;
  }

  public boolean getErrorOnELNotFound() {
    return false;
  }

  public jakarta.el.ExpressionFactory _jsp_getExpressionFactory() {
    if (_el_expressionfactory == null) {
      synchronized (this) {
        if (_el_expressionfactory == null) {
          _el_expressionfactory = _jspxFactory.getJspApplicationContext(getServletConfig().getServletContext()).getExpressionFactory();
        }
      }
    }
    return _el_expressionfactory;
  }

  public org.apache.tomcat.InstanceManager _jsp_getInstanceManager() {
    if (_jsp_instancemanager == null) {
      synchronized (this) {
        if (_jsp_instancemanager == null) {
          _jsp_instancemanager = org.apache.jasper.runtime.InstanceManagerFactory.getInstanceManager(getServletConfig());
        }
      }
    }
    return _jsp_instancemanager;
  }

  public void _jspInit() {
  }

  public void _jspDestroy() {
  }

  public void _jspService(final jakarta.servlet.http.HttpServletRequest request, final jakarta.servlet.http.HttpServletResponse response)
      throws java.io.IOException, jakarta.servlet.ServletException {

    if (!jakarta.servlet.DispatcherType.ERROR.equals(request.getDispatcherType())) {
      final java.lang.String _jspx_method = request.getMethod();
      if ("OPTIONS".equals(_jspx_method)) {
        response.setHeader("Allow","GET, HEAD, POST, OPTIONS");
        return;
      }
      if (!"GET".equals(_jspx_method) && !"POST".equals(_jspx_method) && !"HEAD".equals(_jspx_method)) {
        response.setHeader("Allow","GET, HEAD, POST, OPTIONS");
        response.sendError(HttpServletResponse.SC_METHOD_NOT_ALLOWED, "JSPs only permit GET, POST or HEAD. Jasper also permits OPTIONS");
        return;
      }
    }

    final jakarta.servlet.jsp.PageContext pageContext;
    jakarta.servlet.http.HttpSession session = null;
    final jakarta.servlet.ServletContext application;
    final jakarta.servlet.ServletConfig config;
    jakarta.servlet.jsp.JspWriter out = null;
    final java.lang.Object page = this;
    jakarta.servlet.jsp.JspWriter _jspx_out = null;
    jakarta.servlet.jsp.PageContext _jspx_page_context = null;


    try {
      response.setContentType("text/html");
      pageContext = _jspxFactory.getPageContext(this, request, response,
      			null, true, 8192, true);
      _jspx_page_context = pageContext;
      application = pageContext.getServletContext();
      config = pageContext.getServletConfig();
      session = pageContext.getSession();
      out = pageContext.getOut();
      _jspx_out = out;

      out.write("<!----------------------account details--------------------------->\r\n");
      out.write("<div class=\"tab-pane fade show active\" id=\"pills-five-example1\" role=\"tabpanel\" aria-labelledby=\"pills-five-example1-tab\">\r\n");
      out.write("    <div class=\"border-bottom mb-6 pb-6 mb-lg-8 pb-lg-9\">\r\n");
      out.write("        <div class=\"pt-5 pl-md-5 pt-lg-8 pl-lg-9\">\r\n");
      out.write("            <h6 class=\"font-weight-medium font-size-7 ml-lg-1 mb-lg-8 pb-xl-1\">Account Details</h6>\r\n");
      out.write("            <div class=\"font-weight-medium font-size-22 mb-4 pb-xl-1\">Edit Account</div>\r\n");
      out.write("            <div class=\"row\">\r\n");
      out.write("                <div class=\"col-md-6 mb-4\">\r\n");
      out.write("                    <div class=\"js-form-message\">\r\n");
      out.write("                        <label for=\"exampleFormControlInput1\">First name *</label>\r\n");
      out.write("                        <input type=\"text\" class=\"form-control rounded-0 pl-3 placeholder-color-3\"\r\n");
      out.write("                               id=\"exampleFormControlInput1\" name=\"name\" aria-label=\"Jack Wayley\" placeholder=\"First Name\"\r\n");
      out.write("                               required data-error-class=\"u-has-error\" data-msg=\"Please enter your name.\"\r\n");
      out.write("                               data-success-class=\"u-has-success\">\r\n");
      out.write("                    </div>\r\n");
      out.write("                </div>\r\n");
      out.write("                <div class=\"col-md-6 mb-4\">\r\n");
      out.write("                    <div class=\"js-form-message\">\r\n");
      out.write("                        <label for=\"exampleFormControlInput2\">Last name *</label>\r\n");
      out.write("                        <input type=\"text\" class=\"form-control rounded-0 pl-3 placeholder-color-3\"\r\n");
      out.write("                               id=\"exampleFormControlInput2\" name=\"name\" aria-label=\"Jack Wayley\" placeholder=\"Last Name\"\r\n");
      out.write("                               required data-error-class=\"u-has-error\" data-msg=\"Please enter your name.\"\r\n");
      out.write("                               data-success-class=\"u-has-success\">\r\n");
      out.write("                    </div>\r\n");
      out.write("                </div>\r\n");
      out.write("                <div class=\"col-md-12 mb-4\">\r\n");
      out.write("                    <div class=\"js-form-message\">\r\n");
      out.write("                        <label for=\"exampleFormControlInput3\">Display name</label>\r\n");
      out.write("                        <input type=\"text\" class=\"form-control rounded-0\" name=\"name\" aria-label=\"Jack Wayley\"\r\n");
      out.write("                               id=\"exampleFormControlInput3\" required data-error-class=\"u-has-error\"\r\n");
      out.write("                               data-msg=\"Please enter your name.\" data-success-class=\"u-has-success\">\r\n");
      out.write("                    </div>\r\n");
      out.write("                </div>\r\n");
      out.write("                <div class=\"col-md-12 mb-4 mb-md-0\">\r\n");
      out.write("                    <div class=\"js-form-message\">\r\n");
      out.write("                        <label for=\"exampleFormControlInput4\">Email address</label>\r\n");
      out.write("                        <input type=\"email\" class=\"form-control rounded-0\" name=\"name\" id=\"exampleFormControlInput4\"\r\n");
      out.write("                               aria-label=\"Jack Wayley\" required data-error-class=\"u-has-error\"\r\n");
      out.write("                               data-msg=\"Please enter your name.\" data-success-class=\"u-has-success\" disabled>\r\n");
      out.write("                    </div>\r\n");
      out.write("                </div>\r\n");
      out.write("                <div class=\"col-md-6 mb-4 mt-4\">\r\n");
      out.write("                    <div class=\"js-form-message\">\r\n");
      out.write("                        <label for=\"exampleFormControlInput8\">Mobile</label>\r\n");
      out.write("                        <input type=\"text\" class=\"form-control rounded-0\" name=\"name\" aria-label=\"Jack Wayley\"\r\n");
      out.write("                               id=\"exampleFormControlInput8\" required data-error-class=\"u-has-error\"\r\n");
      out.write("                               data-msg=\"Please enter your name.\" data-success-class=\"u-has-success\">\r\n");
      out.write("                    </div>\r\n");
      out.write("                </div>\r\n");
      out.write("                <div class=\"col-md-6 mb-4 mt-4\">\r\n");
      out.write("                    <div class=\"js-form-message\">\r\n");
      out.write("                        <label for=\"exampleFormControlInput9\">Registered Date</label>\r\n");
      out.write("                        <input type=\"date\" class=\"form-control rounded-0\" name=\"name\" aria-label=\"Jack Wayley\"\r\n");
      out.write("                               id=\"exampleFormControlInput9\" required data-error-class=\"u-has-error\"\r\n");
      out.write("                               data-msg=\"Please enter your name.\" data-success-class=\"u-has-success\" disabled>\r\n");
      out.write("                    </div>\r\n");
      out.write("                </div>\r\n");
      out.write("            </div>\r\n");
      out.write("        </div>\r\n");
      out.write("    </div>\r\n");
      out.write("    <div class=\"border-bottom pl-md-5 pl-lg-9 space-bottom-2 space-bottom-lg-3\">\r\n");
      out.write("        <div class=\"font-weight-medium font-size-22 mb-4 pb-xl-1\">Password Change</div>\r\n");
      out.write("        <div class=\"row\">\r\n");
      out.write("            <div class=\"col-md-12 mb-4\">\r\n");
      out.write("                <div class=\"js-form-message\">\r\n");
      out.write("                    <label for=\"exampleFormControlInput5\">Current Password</label>\r\n");
      out.write("                    <input type=\"password\" class=\"form-control rounded-0\" name=\"name\" id=\"exampleFormControlInput5\"\r\n");
      out.write("                           aria-label=\"Jack Wayley\" required data-error-class=\"u-has-error\"\r\n");
      out.write("                           data-msg=\"Please enter your name.\" data-success-class=\"u-has-success\">\r\n");
      out.write("                </div>\r\n");
      out.write("            </div>\r\n");
      out.write("            <div class=\"col-md-12 mb-4\">\r\n");
      out.write("                <div class=\"js-form-message\">\r\n");
      out.write("                    <label for=\"exampleFormControlInput6\">New Password</label>\r\n");
      out.write("                    <input type=\"password\" class=\"form-control rounded-0\" name=\"name\" id=\"exampleFormControlInput6\"\r\n");
      out.write("                           aria-label=\"Jack Wayley\" required data-error-class=\"u-has-error\"\r\n");
      out.write("                           data-msg=\"Please enter your name.\" data-success-class=\"u-has-success\">\r\n");
      out.write("                </div>\r\n");
      out.write("            </div>\r\n");
      out.write("            <div class=\"col-md-12 mb-5\">\r\n");
      out.write("                <div class=\"js-form-message\">\r\n");
      out.write("                    <label for=\"exampleFormControlInput7\">Confirm new password</label>\r\n");
      out.write("                    <input type=\"password\" class=\"form-control rounded-0\" name=\"name\" id=\"exampleFormControlInput7\"\r\n");
      out.write("                           aria-label=\"Jack Wayley\" required data-error-class=\"u-has-error\"\r\n");
      out.write("                           data-msg=\"Please enter your name.\" data-success-class=\"u-has-success\">\r\n");
      out.write("                </div>\r\n");
      out.write("            </div>\r\n");
      out.write("            <div class=\"ml-3\">\r\n");
      out.write("                <button type=\"submit\"\r\n");
      out.write("                        class=\"btn btn-wide btn-dark text-white rounded-0 transition-3d-hover height-60 width-390\">Save\r\n");
      out.write("                    Changes\r\n");
      out.write("                </button>\r\n");
      out.write("            </div>\r\n");
      out.write("        </div>\r\n");
      out.write("    </div>\r\n");
      out.write("    <!----------------------address edit--------------------------->\r\n");
      out.write("    <div class=\"border-bottom pl-md-5 pl-lg-9 space-bottom-2 space-bottom-lg-3 mt-5\">\r\n");
      out.write("        <h6 class=\"font-weight-medium font-size-22 mb-4 pb-xl-1\">Addresses</h6>\r\n");
      out.write("        <div class=\"row row-cols-1 row-cols-md-2\">\r\n");
      out.write("            <div class=\"col\">\r\n");
      out.write("                <div class=\"mb-6 mb-md-0\">\r\n");
      out.write("                    <h6 class=\"font-weight-medium font-size-22 mb-3\">Billing Address\r\n");
      out.write("                    </h6>\r\n");
      out.write("                    <address class=\"d-flex flex-column mb-4\">\r\n");
      out.write("                        <span class=\"text-gray-600 font-size-2\">Ali Tufan</span>\r\n");
      out.write("                        <span class=\"text-gray-600 font-size-2\">Bedford St,</span>\r\n");
      out.write("                        <span class=\"text-gray-600 font-size-2\">Covent Garden, </span>\r\n");
      out.write("                        <span class=\"text-gray-600 font-size-2\">London WC2E 9ED</span>\r\n");
      out.write("                        <span class=\"text-gray-600 font-size-2\">United Kingdom</span>\r\n");
      out.write("                    </address>\r\n");
      out.write("                    <div class=\"d-flex\">\r\n");
      out.write("                        <button type=\"submit\" class=\"btn btn-dark width-150 rounded-0 btn-wide font-weight-medium\">\r\n");
      out.write("                            Edit\r\n");
      out.write("                        </button>\r\n");
      out.write("                    </div>\r\n");
      out.write("                </div>\r\n");
      out.write("            </div>\r\n");
      out.write("            <div class=\"col\">\r\n");
      out.write("                <h6 class=\"font-weight-medium font-size-22 mb-3\">Shipping Address\r\n");
      out.write("                </h6>\r\n");
      out.write("                <address class=\"d-flex flex-column mb-4\">\r\n");
      out.write("                    <span class=\"text-gray-600 font-size-2\">Ali Tufan</span>\r\n");
      out.write("                    <span class=\"text-gray-600 font-size-2\">Bedford St,</span>\r\n");
      out.write("                    <span class=\"text-gray-600 font-size-2\">Covent Garden, </span>\r\n");
      out.write("                    <span class=\"text-gray-600 font-size-2\">London WC2E 9ED</span>\r\n");
      out.write("                    <span class=\"text-gray-600 font-size-2\">United Kingdom</span>\r\n");
      out.write("                </address>\r\n");
      out.write("                <div class=\"d-flex\">\r\n");
      out.write("                    <button type=\"submit\" class=\"btn btn-dark width-150 rounded-0 btn-wide font-weight-medium\">Edit\r\n");
      out.write("                    </button>\r\n");
      out.write("                </div>\r\n");
      out.write("            </div>\r\n");
      out.write("        </div>\r\n");
      out.write("    </div>\r\n");
      out.write("    <!----------------------address edit--------------------------->\r\n");
      out.write("\r\n");
      out.write('\r');
      out.write('\n');
      out.write('\r');
      out.write('\n');
      out.write('\r');
      out.write('\n');
      out.write('\r');
      out.write('\n');
      out.write('\r');
      out.write('\n');
      out.write('\r');
      out.write('\n');
      out.write('\r');
      out.write('\n');
      out.write('\r');
      out.write('\n');
      out.write('\r');
      out.write('\n');
      out.write('\r');
      out.write('\n');
      out.write('\r');
      out.write('\n');
      out.write('\r');
      out.write('\n');
      out.write('\r');
      out.write('\n');
      out.write('\r');
      out.write('\n');
      out.write('\r');
      out.write('\n');
      out.write('\r');
      out.write('\n');
      out.write('\r');
      out.write('\n');
      out.write('\r');
      out.write('\n');
      out.write("\r\n");
      out.write("</div>\r\n");
      out.write("\r\n");
      out.write("<!----------------------account details--------------------------->\r\n");
    } catch (java.lang.Throwable t) {
      if (!(t instanceof jakarta.servlet.jsp.SkipPageException)){
        out = _jspx_out;
        if (out != null && out.getBufferSize() != 0)
          try {
            if (response.isCommitted()) {
              out.flush();
            } else {
              out.clearBuffer();
            }
          } catch (java.io.IOException e) {}
        if (_jspx_page_context != null) _jspx_page_context.handlePageException(t);
        else throw new ServletException(t);
      }
    } finally {
      _jspxFactory.releasePageContext(_jspx_page_context);
    }
  }
}
