/*
 * Generated by the Jasper component of Apache Tomcat
 * Version: Apache Tomcat/10.1.7
 * Generated at: 2023-08-25 13:23:31 UTC
 * Note: The last modified time of this file was set to
 *       the last modified time of the source file after
 *       generation to assist with modification tracking.
 */
package org.apache.jsp.WEB_002dINF.views.frontend;

import jakarta.servlet.*;
import jakarta.servlet.http.*;
import jakarta.servlet.jsp.*;

public final class myAccount_jsp extends org.apache.jasper.runtime.HttpJspBase
    implements org.apache.jasper.runtime.JspSourceDependent,
                 org.apache.jasper.runtime.JspSourceImports,
                 org.apache.jasper.runtime.JspSourceDirectives {

  private static final jakarta.servlet.jsp.JspFactory _jspxFactory =
          jakarta.servlet.jsp.JspFactory.getDefaultFactory();

  private static java.util.Map<java.lang.String,java.lang.Long> _jspx_dependants;

  private static final java.util.Set<java.lang.String> _jspx_imports_packages;

  private static final java.util.Set<java.lang.String> _jspx_imports_classes;

  static {
    _jspx_imports_packages = new java.util.HashSet<>();
    _jspx_imports_packages.add("jakarta.servlet");
    _jspx_imports_packages.add("jakarta.servlet.http");
    _jspx_imports_packages.add("jakarta.servlet.jsp");
    _jspx_imports_classes = null;
  }

  private volatile jakarta.el.ExpressionFactory _el_expressionfactory;
  private volatile org.apache.tomcat.InstanceManager _jsp_instancemanager;

  public java.util.Map<java.lang.String,java.lang.Long> getDependants() {
    return _jspx_dependants;
  }

  public java.util.Set<java.lang.String> getPackageImports() {
    return _jspx_imports_packages;
  }

  public java.util.Set<java.lang.String> getClassImports() {
    return _jspx_imports_classes;
  }

  public boolean getErrorOnELNotFound() {
    return false;
  }

  public jakarta.el.ExpressionFactory _jsp_getExpressionFactory() {
    if (_el_expressionfactory == null) {
      synchronized (this) {
        if (_el_expressionfactory == null) {
          _el_expressionfactory = _jspxFactory.getJspApplicationContext(getServletConfig().getServletContext()).getExpressionFactory();
        }
      }
    }
    return _el_expressionfactory;
  }

  public org.apache.tomcat.InstanceManager _jsp_getInstanceManager() {
    if (_jsp_instancemanager == null) {
      synchronized (this) {
        if (_jsp_instancemanager == null) {
          _jsp_instancemanager = org.apache.jasper.runtime.InstanceManagerFactory.getInstanceManager(getServletConfig());
        }
      }
    }
    return _jsp_instancemanager;
  }

  public void _jspInit() {
  }

  public void _jspDestroy() {
  }

  public void _jspService(final jakarta.servlet.http.HttpServletRequest request, final jakarta.servlet.http.HttpServletResponse response)
      throws java.io.IOException, jakarta.servlet.ServletException {

    if (!jakarta.servlet.DispatcherType.ERROR.equals(request.getDispatcherType())) {
      final java.lang.String _jspx_method = request.getMethod();
      if ("OPTIONS".equals(_jspx_method)) {
        response.setHeader("Allow","GET, HEAD, POST, OPTIONS");
        return;
      }
      if (!"GET".equals(_jspx_method) && !"POST".equals(_jspx_method) && !"HEAD".equals(_jspx_method)) {
        response.setHeader("Allow","GET, HEAD, POST, OPTIONS");
        response.sendError(HttpServletResponse.SC_METHOD_NOT_ALLOWED, "JSPs only permit GET, POST or HEAD. Jasper also permits OPTIONS");
        return;
      }
    }

    final jakarta.servlet.jsp.PageContext pageContext;
    jakarta.servlet.http.HttpSession session = null;
    final jakarta.servlet.ServletContext application;
    final jakarta.servlet.ServletConfig config;
    jakarta.servlet.jsp.JspWriter out = null;
    final java.lang.Object page = this;
    jakarta.servlet.jsp.JspWriter _jspx_out = null;
    jakarta.servlet.jsp.PageContext _jspx_page_context = null;


    try {
      response.setContentType("text/html;charset=UTF-8");
      pageContext = _jspxFactory.getPageContext(this, request, response,
      			null, true, 8192, true);
      _jspx_page_context = pageContext;
      application = pageContext.getServletContext();
      config = pageContext.getServletConfig();
      session = pageContext.getSession();
      out = pageContext.getOut();
      _jspx_out = out;

      out.write("\r\n");
      out.write("<!DOCTYPE html>\r\n");
      out.write("<html lang=\"en\">\r\n");
      out.write("\r\n");
      out.write("<head>\r\n");
      out.write("    <title>User Profile | eBookStore</title>\r\n");
      out.write("\r\n");
      out.write("    <meta charset=\"utf-8\">\r\n");
      out.write("    <meta name=\"viewport\" content=\"width=device-width, initial-scale=1, shrink-to-fit=no\">\r\n");
      out.write("\r\n");
      out.write("    <link rel=\"shortcut icon\" href=\"assets/img/favicon.png\">\r\n");
      out.write("    <link href=\"https://fonts.googleapis.com/css2?family=Inter:wght@400;500;700&amp;display=swap\" rel=\"stylesheet\">\r\n");
      out.write("    <link rel=\"stylesheet\" href=\"https://use.fontawesome.com/releases/v6.1.1/css/all.css\"/>\r\n");
      out.write("    <!-- <link rel=\"stylesheet\" href=\"https://cdn.jsdelivr.net/npm/bootstrap-icons@1.8.3/font/bootstrap-icons.css\"> -->\r\n");
      out.write("\r\n");
      out.write("    <link rel=\"stylesheet\" href=\"assets/vendor/font-awesome/css/fontawesome-all.min.css\">\r\n");
      out.write("    <link rel=\"stylesheet\" href=\"assets/vendor/flaticon/font/flaticon.css\">\r\n");
      out.write("    <link rel=\"stylesheet\" href=\"assets/vendor/animate.css/animate.css\">\r\n");
      out.write("    <link rel=\"stylesheet\" href=\"assets/vendor/bootstrap-select/dist/css/bootstrap-select.min.css\">\r\n");
      out.write("    <link rel=\"stylesheet\" href=\"assets/vendor/slick-carousel/slick/slick.css\"/>\r\n");
      out.write("    <link rel=\"stylesheet\" href=\"assets/vendor/malihu-custom-scrollbar-plugin/jquery.mCustomScrollbar.css\">\r\n");
      out.write("\r\n");
      out.write("    <link rel=\"stylesheet\" href=\"assets/css/theme.css\">\r\n");
      out.write("</head>\r\n");
      out.write("\r\n");
      out.write("<body>\r\n");
      out.write("<main id=\"content\">\r\n");
      out.write("    <div class=\"container\">\r\n");
      out.write("        <div class=\"row\">\r\n");
      out.write("            <div class=\"col-md-3 border-right\">\r\n");
      out.write("                <h6 class=\"font-weight-medium font-size-7 pt-5 pt-lg-8  mb-5 mb-lg-7\">My account</h6>\r\n");
      out.write("                <div class=\"tab-wrapper\">\r\n");
      out.write("                    <ul class=\"my__account-nav nav flex-column mb-0\" role=\"tablist\" id=\"pills-tab\">\r\n");
      out.write("                        <li class=\"nav-item mx-0\">\r\n");
      out.write("                            <a class=\"nav-link d-flex align-items-center px-0 active\" id=\"pills-one-example1-tab\"\r\n");
      out.write("                               data-toggle=\"pill\" href=\"#pills-one-example1\" role=\"tab\"\r\n");
      out.write("                               aria-controls=\"pills-one-example1\" aria-selected=\"false\">\r\n");
      out.write("                                <span class=\"font-weight-normal text-gray-600\">Dashboard</span>\r\n");
      out.write("                            </a>\r\n");
      out.write("                        </li>\r\n");
      out.write("                        <li class=\"nav-item mx-0\">\r\n");
      out.write("                            <a class=\"nav-link d-flex align-items-center px-0\" id=\"pills-two-example1-tab\"\r\n");
      out.write("                               data-toggle=\"pill\" href=\"#pills-two-example1\" role=\"tab\"\r\n");
      out.write("                               aria-controls=\"pills-two-example1\" aria-selected=\"false\">\r\n");
      out.write("                                <span class=\"font-weight-normal text-gray-600\">Orders</span>\r\n");
      out.write("                            </a>\r\n");
      out.write("                        </li>\r\n");
      out.write("                        <li class=\"nav-item mx-0\">\r\n");
      out.write("                            <a class=\"nav-link d-flex align-items-center px-0\" id=\"pills-three-example1-tab\"\r\n");
      out.write("                               data-toggle=\"pill\" href=\"#pills-three-example1\" role=\"tab\"\r\n");
      out.write("                               aria-controls=\"pills-three-example1\" aria-selected=\"false\">\r\n");
      out.write("                                <span class=\"font-weight-normal text-gray-600\">Downloads</span>\r\n");
      out.write("                            </a>\r\n");
      out.write("                        </li>\r\n");
      out.write("                        <li class=\"nav-item mx-0\">\r\n");
      out.write("                            <a class=\"nav-link d-flex align-items-center px-0\" id=\"pills-four-example1-tab\"\r\n");
      out.write("                               data-toggle=\"pill\" href=\"#pills-four-example1\" role=\"tab\"\r\n");
      out.write("                               aria-controls=\"pills-four-example1\" aria-selected=\"false\">\r\n");
      out.write("                                <span class=\"font-weight-normal text-gray-600\">Addresses</span>\r\n");
      out.write("                            </a>\r\n");
      out.write("                        </li>\r\n");
      out.write("                        <li class=\"nav-item mx-0\">\r\n");
      out.write("                            <a class=\"nav-link d-flex align-items-center px-0\" id=\"pills-five-example1-tab\"\r\n");
      out.write("                               data-toggle=\"pill\" href=\"#pills-five-example1\" role=\"tab\"\r\n");
      out.write("                               aria-controls=\"pills-five-example1\" aria-selected=\"false\">\r\n");
      out.write("                                <span class=\"font-weight-normal text-gray-600\">Account details</span>\r\n");
      out.write("                            </a>\r\n");
      out.write("                        </li>\r\n");
      out.write("                        <li class=\"nav-item mx-0\">\r\n");
      out.write("                            <a class=\"nav-link d-flex align-items-center px-0\" id=\"pills-six-example1-tab\"\r\n");
      out.write("                               data-toggle=\"pill\" href=\"#pills-six-example1\" role=\"tab\"\r\n");
      out.write("                               aria-controls=\"pills-six-example1\" aria-selected=\"false\">\r\n");
      out.write("                                <span class=\"font-weight-normal text-gray-600\">Wishlist</span>\r\n");
      out.write("                            </a>\r\n");
      out.write("                        </li>\r\n");
      out.write("                        <li class=\"nav-item mx-0\">\r\n");
      out.write("                            <a class=\"nav-link d-flex align-items-center px-0\" href=\"#\">\r\n");
      out.write("                                <span class=\"font-weight-normal text-gray-600\">Logout</span>\r\n");
      out.write("                            </a>\r\n");
      out.write("                        </li>\r\n");
      out.write("                    </ul>\r\n");
      out.write("                </div>\r\n");
      out.write("            </div>\r\n");
      out.write("            <div class=\"col-md-9\">\r\n");
      out.write("                <div class=\"tab-content\" id=\"pills-tabContent\">\r\n");
      out.write("\r\n");
      out.write("                    <!----------------------Dashboard--------------------------->\r\n");
      out.write("                    <!-- my-account-dashboard is already edited to add to this -->\r\n");
      out.write("                    <div class=\"tab-pane fade show active\" id=\"pills-one-example1\" role=\"tabpanel\"\r\n");
      out.write("                         aria-labelledby=\"pills-one-example1-tab\">\r\n");
      out.write("                        <div class=\"pt-5 pt-lg-8 pl-md-5 pl-lg-9 space-bottom-2 space-bottom-lg-3 mb-xl-1\">\r\n");
      out.write("                            <h6 class=\"font-weight-medium font-size-7 ml-lg-1 mb-lg-8 pb-xl-1\">Dashboard</h6>\r\n");
      out.write("                            <div class=\"ml-lg-1 mb-4\">\r\n");
      out.write("                                <span class=\"font-size-22\">Hello alitfn58</span>\r\n");
      out.write("                                <span class=\"font-size-2\"> (not alitfn58? <a class=\"link-black-100\" href=\"#\">Log out</a>)</span>\r\n");
      out.write("                            </div>\r\n");
      out.write("                            <div class=\"mb-4\">\r\n");
      out.write("                                <p class=\"mb-0 font-size-2 ml-lg-1 text-gray-600\">From your account dashboard you can\r\n");
      out.write("                                    view your <span class=\"text-dark\">recent orders,</span> manage your <span\r\n");
      out.write("                                            class=\"text-dark\">shipping and billing addresses,</span> and edit your <span\r\n");
      out.write("                                            class=\"text-dark\">password and account details.</span></p>\r\n");
      out.write("                            </div>\r\n");
      out.write("                            <div class=\"row no-gutters row-cols-1 row-cols-md-2 row-cols-lg-3\">\r\n");
      out.write("                                <div class=\"col\">\r\n");
      out.write("                                    <div class=\"border py-6 text-center\">\r\n");
      out.write("                                        <a href=\"#\" class=\"btn btn-primary rounded-circle px-4 mb-2\">\r\n");
      out.write("                                            <span class=\"flaticon-order font-size-10 btn-icon__inner\"></span>\r\n");
      out.write("                                        </a>\r\n");
      out.write("                                        <div class=\"font-size-3 mb-xl-1\">Orders</div>\r\n");
      out.write("                                    </div>\r\n");
      out.write("                                </div>\r\n");
      out.write("                                <div class=\"col\">\r\n");
      out.write("                                    <div class=\"border border-left-0 py-6 text-center\">\r\n");
      out.write("                                        <a href=\"#\" class=\"btn bg-gray-200 rounded-circle px-4 mb-2\">\r\n");
      out.write("                                            <span class=\"flaticon-cloud-computing font-size-10 btn-icon__inner text-primary\"></span>\r\n");
      out.write("                                        </a>\r\n");
      out.write("                                        <div class=\"font-size-3 mb-xl-1\">Downloads</div>\r\n");
      out.write("                                    </div>\r\n");
      out.write("                                </div>\r\n");
      out.write("                                <div class=\"col\">\r\n");
      out.write("                                    <div class=\"border border-left-0 py-6 text-center\">\r\n");
      out.write("                                        <a href=\"#\" class=\"btn bg-gray-200 rounded-circle px-4 mb-2\">\r\n");
      out.write("                                            <span class=\"flaticon-place font-size-10 btn-icon__inner text-primary\"></span>\r\n");
      out.write("                                        </a>\r\n");
      out.write("                                        <div class=\"font-size-3 mb-xl-1\">Addresses</div>\r\n");
      out.write("                                    </div>\r\n");
      out.write("                                </div>\r\n");
      out.write("                                <div class=\"col\">\r\n");
      out.write("                                    <div class=\"border py-6 text-center\">\r\n");
      out.write("                                        <a href=\"#\" class=\"btn bg-gray-200 rounded-circle px-4 mb-2\">\r\n");
      out.write("                                            <span class=\"flaticon-user-1 font-size-10 btn-icon__inner text-primary\"></span>\r\n");
      out.write("                                        </a>\r\n");
      out.write("                                        <div class=\"font-size-3 mb-xl-1\">Account Details</div>\r\n");
      out.write("                                    </div>\r\n");
      out.write("                                </div>\r\n");
      out.write("                                <div class=\"col\">\r\n");
      out.write("                                    <div class=\"border border-left-0 py-6 text-center\">\r\n");
      out.write("                                        <a href=\"#\" class=\"btn bg-gray-200  rounded-circle px-4 mb-2\">\r\n");
      out.write("                                            <span class=\"flaticon-heart font-size-10 btn-icon__inner text-primary\"></span>\r\n");
      out.write("                                        </a>\r\n");
      out.write("                                        <div class=\"font-size-3 mb-xl-1\">Wishlist</div>\r\n");
      out.write("                                    </div>\r\n");
      out.write("                                </div>\r\n");
      out.write("                                <div class=\"col\">\r\n");
      out.write("                                    <div class=\"border border-left-0 py-6 text-center\">\r\n");
      out.write("                                        <a href=\"#\" class=\"btn bg-gray-200 rounded-circle px-4 mb-2\">\r\n");
      out.write("                                            <span class=\"flaticon-exit font-size-10 btn-icon__inner text-primary\"></span>\r\n");
      out.write("                                        </a>\r\n");
      out.write("                                        <div class=\"font-size-3 mb-xl-1\">Orders</div>\r\n");
      out.write("                                    </div>\r\n");
      out.write("                                </div>\r\n");
      out.write("                            </div>\r\n");
      out.write("                        </div>\r\n");
      out.write("                    </div>\r\n");
      out.write("                    <!----------------------Dashboard--------------------------->\r\n");
      out.write("\r\n");
      out.write("\r\n");
      out.write("                    <!----------------------orders--------------------------->\r\n");
      out.write("                    <div class=\"tab-pane fade\" id=\"pills-two-example1\" role=\"tabpanel\"\r\n");
      out.write("                         aria-labelledby=\"pills-two-example1-tab\">\r\n");
      out.write("                        <div class=\"pt-5 pl-md-5 pt-lg-8 pl-lg-9 space-bottom-lg-2 mb-lg-4\">\r\n");
      out.write("                            <h6 class=\"font-weight-medium font-size-7 ml-lg-1 mb-lg-8 pb-xl-1\">orders</h6>\r\n");
      out.write("                            <table class=\"table\">\r\n");
      out.write("                                <thead>\r\n");
      out.write("                                <tr class=\"border\">\r\n");
      out.write("                                    <th scope=\"col\" class=\"py-3 border-bottom-0 font-weight-medium pl-3 pl-lg-5\">Order\r\n");
      out.write("                                    </th>\r\n");
      out.write("                                    <th scope=\"col\" class=\"py-3 border-bottom-0 font-weight-medium\">Date</th>\r\n");
      out.write("                                    <th scope=\"col\" class=\"py-3 border-bottom-0 font-weight-medium\">Staus</th>\r\n");
      out.write("                                    <th scope=\"col\" class=\"py-3 border-bottom-0 font-weight-medium\">Total</th>\r\n");
      out.write("                                    <th scope=\"col\" class=\"py-3 border-bottom-0 font-weight-medium\">Actions</th>\r\n");
      out.write("                                </tr>\r\n");
      out.write("                                </thead>\r\n");
      out.write("                                <tbody>\r\n");
      out.write("                                <tr class=\"border\">\r\n");
      out.write("                                    <th class=\"pl-3 pl-md-5 font-weight-normal align-middle py-6\">#30785</th>\r\n");
      out.write("                                    <td class=\"align-middle py-5\">March 26, 2020</td>\r\n");
      out.write("                                    <td class=\"align-middle py-5\">On hold</td>\r\n");
      out.write("                                    <td class=\"align-middle py-5\">\r\n");
      out.write("                                        <span class=\"text-primary\">$1,855.00</span> for 5 items\r\n");
      out.write("                                    </td>\r\n");
      out.write("                                    <td class=\"align-middle py-5\">\r\n");
      out.write("                                        <div class=\"d-flex justify-content-center\">\r\n");
      out.write("                                            <button type=\"submit\"\r\n");
      out.write("                                                    class=\"btn btn-dark rounded-0 btn-wide font-weight-medium\">View\r\n");
      out.write("                                            </button>\r\n");
      out.write("                                        </div>\r\n");
      out.write("                                    </td>\r\n");
      out.write("                                </tr>\r\n");
      out.write("                                <tr class=\"border\">\r\n");
      out.write("                                    <th class=\"pl-3 pl-md-5 font-weight-normal align-middle py-6\">#30785</th>\r\n");
      out.write("                                    <td class=\"align-middle py-5\">March 26, 2020</td>\r\n");
      out.write("                                    <td class=\"align-middle py-5\">On hold</td>\r\n");
      out.write("                                    <td class=\"align-middle py-5\">\r\n");
      out.write("                                        <span class=\"text-primary\">$1,855.00</span> for 5 items\r\n");
      out.write("                                    </td>\r\n");
      out.write("                                    <td class=\"align-middle py-5\">\r\n");
      out.write("                                        <div class=\"d-flex justify-content-center\">\r\n");
      out.write("                                            <button type=\"submit\"\r\n");
      out.write("                                                    class=\"btn btn-dark rounded-0 btn-wide font-weight-medium\">View\r\n");
      out.write("                                            </button>\r\n");
      out.write("                                        </div>\r\n");
      out.write("                                    </td>\r\n");
      out.write("                                </tr>\r\n");
      out.write("                                <tr class=\"border\">\r\n");
      out.write("                                    <th class=\"pl-3 pl-md-5 font-weight-normal align-middle py-6\">#30785</th>\r\n");
      out.write("                                    <td class=\"align-middle py-5\">March 26, 2020</td>\r\n");
      out.write("                                    <td class=\"align-middle py-5\">On hold</td>\r\n");
      out.write("                                    <td class=\"align-middle py-5\">\r\n");
      out.write("                                        <span class=\"text-primary\">$1,855.00</span> for 5 items\r\n");
      out.write("                                    </td>\r\n");
      out.write("                                    <td class=\"align-middle py-5\">\r\n");
      out.write("                                        <div class=\"d-flex justify-content-center\">\r\n");
      out.write("                                            <button type=\"submit\"\r\n");
      out.write("                                                    class=\"btn btn-dark rounded-0 btn-wide font-weight-medium\">View\r\n");
      out.write("                                            </button>\r\n");
      out.write("                                        </div>\r\n");
      out.write("                                    </td>\r\n");
      out.write("                                </tr>\r\n");
      out.write("                                </tbody>\r\n");
      out.write("                            </table>\r\n");
      out.write("                        </div>\r\n");
      out.write("                    </div>\r\n");
      out.write("                    <!----------------------orders--------------------------->\r\n");
      out.write("\r\n");
      out.write("\r\n");
      out.write("                    <!----------------------Downloads--------------------------->\r\n");
      out.write("                    <div class=\"tab-pane fade\" id=\"pills-three-example1\" role=\"tabpanel\"\r\n");
      out.write("                         aria-labelledby=\"pills-three-example1-tab\">\r\n");
      out.write("                        <div class=\"pt-5 pl-md-5 pt-lg-8 pl-lg-9 space-bottom-lg-2 mb-lg-4\">\r\n");
      out.write("                            <h6 class=\"font-weight-medium font-size-7 ml-lg-1 mb-lg-8 pb-xl-1\">Downloads</h6>\r\n");
      out.write("                            <table class=\"table\">\r\n");
      out.write("                                <thead>\r\n");
      out.write("                                <tr class=\"border\">\r\n");
      out.write("                                    <th scope=\"col\" class=\"py-3 border-bottom-0 font-weight-medium pl-3 pl-md-5\">Order\r\n");
      out.write("                                    </th>\r\n");
      out.write("                                    <th scope=\"col\" class=\"py-3 border-bottom-0 font-weight-medium\">Date</th>\r\n");
      out.write("                                    <th scope=\"col\" class=\"py-3 border-bottom-0 font-weight-medium\">Staus</th>\r\n");
      out.write("                                    <th scope=\"col\" class=\"py-3 border-bottom-0 font-weight-medium\">Total</th>\r\n");
      out.write("                                    <th scope=\"col\" class=\"py-3 border-bottom-0 font-weight-medium\">Actions</th>\r\n");
      out.write("                                </tr>\r\n");
      out.write("                                </thead>\r\n");
      out.write("                                <tbody>\r\n");
      out.write("                                <tr class=\"border\">\r\n");
      out.write("                                    <th class=\"pl-3 pl-md-5 font-weight-normal align-middle py-6\">#30785</th>\r\n");
      out.write("                                    <td class=\"align-middle py-5\">March 26, 2020</td>\r\n");
      out.write("                                    <td class=\"align-middle py-5\">On hold</td>\r\n");
      out.write("                                    <td class=\"align-middle py-5\">\r\n");
      out.write("                                        <span class=\"text-primary\">$1,855.00</span> for 5 items\r\n");
      out.write("                                    </td>\r\n");
      out.write("                                    <td class=\"align-middle py-5\">\r\n");
      out.write("                                        <div class=\"d-flex justify-content-center\">\r\n");
      out.write("                                            <button type=\"submit\"\r\n");
      out.write("                                                    class=\"btn btn-dark rounded-0 btn-wide font-weight-medium\">View\r\n");
      out.write("                                            </button>\r\n");
      out.write("                                        </div>\r\n");
      out.write("                                    </td>\r\n");
      out.write("                                </tr>\r\n");
      out.write("                                </tbody>\r\n");
      out.write("                            </table>\r\n");
      out.write("                        </div>\r\n");
      out.write("                    </div>\r\n");
      out.write("                    <!----------------------Downloads--------------------------->\r\n");
      out.write("\r\n");
      out.write("\r\n");
      out.write("                    <!----------------------address edit--------------------------->\r\n");
      out.write("                    <div class=\"tab-pane fade\" id=\"pills-four-example1\" role=\"tabpanel\"\r\n");
      out.write("                         aria-labelledby=\"pills-four-example1-tab\">\r\n");
      out.write("                        <div class=\"pt-5 pl-md-5 pt-lg-8 pl-lg-9 space-bottom-2 mb-lg-4\">\r\n");
      out.write("                            <h6 class=\"font-weight-medium font-size-7 ml-lg-1 mb-5 mb-lg-8 pb-xl-1\">Addresses</h6>\r\n");
      out.write("                            <div class=\"row row-cols-1 row-cols-md-2\">\r\n");
      out.write("                                <div class=\"col\">\r\n");
      out.write("                                    <div class=\"mb-6 mb-md-0\">\r\n");
      out.write("                                        <h6 class=\"font-weight-medium font-size-22 mb-3\">Billing Address\r\n");
      out.write("                                        </h6>\r\n");
      out.write("                                        <address class=\"d-flex flex-column mb-4\">\r\n");
      out.write("                                            <span class=\"text-gray-600 font-size-2\">Ali Tufan</span>\r\n");
      out.write("                                            <span class=\"text-gray-600 font-size-2\">Bedford St,</span>\r\n");
      out.write("                                            <span class=\"text-gray-600 font-size-2\">Covent Garden, </span>\r\n");
      out.write("                                            <span class=\"text-gray-600 font-size-2\">London WC2E 9ED</span>\r\n");
      out.write("                                            <span class=\"text-gray-600 font-size-2\">United Kingdom</span>\r\n");
      out.write("                                        </address>\r\n");
      out.write("                                        <div class=\"d-flex\">\r\n");
      out.write("                                            <button type=\"submit\"\r\n");
      out.write("                                                    class=\"btn btn-dark width-150 rounded-0 btn-wide font-weight-medium\">\r\n");
      out.write("                                                Edit\r\n");
      out.write("                                            </button>\r\n");
      out.write("                                        </div>\r\n");
      out.write("                                    </div>\r\n");
      out.write("                                </div>\r\n");
      out.write("                                <div class=\"col\">\r\n");
      out.write("                                    <h6 class=\"font-weight-medium font-size-22 mb-3\">Shipping Address\r\n");
      out.write("                                    </h6>\r\n");
      out.write("                                    <address class=\"d-flex flex-column mb-4\">\r\n");
      out.write("                                        <span class=\"text-gray-600 font-size-2\">Ali Tufan</span>\r\n");
      out.write("                                        <span class=\"text-gray-600 font-size-2\">Bedford St,</span>\r\n");
      out.write("                                        <span class=\"text-gray-600 font-size-2\">Covent Garden, </span>\r\n");
      out.write("                                        <span class=\"text-gray-600 font-size-2\">London WC2E 9ED</span>\r\n");
      out.write("                                        <span class=\"text-gray-600 font-size-2\">United Kingdom</span>\r\n");
      out.write("                                    </address>\r\n");
      out.write("                                    <div class=\"d-flex\">\r\n");
      out.write("                                        <button type=\"submit\"\r\n");
      out.write("                                                class=\"btn btn-dark width-150 rounded-0 btn-wide font-weight-medium\">\r\n");
      out.write("                                            Edit\r\n");
      out.write("                                        </button>\r\n");
      out.write("                                    </div>\r\n");
      out.write("                                </div>\r\n");
      out.write("                            </div>\r\n");
      out.write("                        </div>\r\n");
      out.write("                    </div>\r\n");
      out.write("                    <!----------------------address edit--------------------------->\r\n");
      out.write("\r\n");
      out.write("\r\n");
      out.write("                    <!----------------------account details--------------------------->\r\n");
      out.write("                    <div class=\"tab-pane fade\" id=\"pills-five-example1\" role=\"tabpanel\"\r\n");
      out.write("                         aria-labelledby=\"pills-five-example1-tab\">\r\n");
      out.write("                        <div class=\"border-bottom mb-6 pb-6 mb-lg-8 pb-lg-9\">\r\n");
      out.write("                            <div class=\"pt-5 pl-md-5 pt-lg-8 pl-lg-9\">\r\n");
      out.write("                                <h6 class=\"font-weight-medium font-size-7 ml-lg-1 mb-lg-8 pb-xl-1\">Account Details</h6>\r\n");
      out.write("                                <div class=\"font-weight-medium font-size-22 mb-4 pb-xl-1\">Edit Account</div>\r\n");
      out.write("                                <div class=\"row\">\r\n");
      out.write("                                    <div class=\"col-md-6 mb-4\">\r\n");
      out.write("                                        <div class=\"js-form-message\">\r\n");
      out.write("                                            <label for=\"exampleFormControlInput1\">First name *</label>\r\n");
      out.write("                                            <input type=\"text\" class=\"form-control rounded-0 pl-3 placeholder-color-3\"\r\n");
      out.write("                                                   id=\"exampleFormControlInput1\" name=\"name\" aria-label=\"Jack Wayley\"\r\n");
      out.write("                                                   placeholder=\"Ali\" required data-error-class=\"u-has-error\"\r\n");
      out.write("                                                   data-msg=\"Please enter your name.\"\r\n");
      out.write("                                                   data-success-class=\"u-has-success\">\r\n");
      out.write("                                        </div>\r\n");
      out.write("                                    </div>\r\n");
      out.write("                                    <div class=\"col-md-6 mb-4\">\r\n");
      out.write("                                        <div class=\"js-form-message\">\r\n");
      out.write("                                            <label for=\"exampleFormControlInput2\">Last name *</label>\r\n");
      out.write("                                            <input type=\"text\" class=\"form-control rounded-0 pl-3 placeholder-color-3\"\r\n");
      out.write("                                                   id=\"exampleFormControlInput2\" name=\"name\" aria-label=\"Jack Wayley\"\r\n");
      out.write("                                                   placeholder=\"TUF..\" required data-error-class=\"u-has-error\"\r\n");
      out.write("                                                   data-msg=\"Please enter your name.\"\r\n");
      out.write("                                                   data-success-class=\"u-has-success\">\r\n");
      out.write("                                        </div>\r\n");
      out.write("                                    </div>\r\n");
      out.write("                                    <div class=\"col-md-12 mb-4\">\r\n");
      out.write("                                        <div class=\"js-form-message\">\r\n");
      out.write("                                            <label for=\"exampleFormControlInput3\">Display name</label>\r\n");
      out.write("                                            <input type=\"text\" class=\"form-control rounded-0\" name=\"name\"\r\n");
      out.write("                                                   aria-label=\"Jack Wayley\" id=\"exampleFormControlInput3\" required\r\n");
      out.write("                                                   data-error-class=\"u-has-error\" data-msg=\"Please enter your name.\"\r\n");
      out.write("                                                   data-success-class=\"u-has-success\">\r\n");
      out.write("                                        </div>\r\n");
      out.write("                                    </div>\r\n");
      out.write("                                    <div class=\"col-md-12 mb-4 mb-md-0\">\r\n");
      out.write("                                        <div class=\"js-form-message\">\r\n");
      out.write("                                            <label for=\"exampleFormControlInput4\">Email address</label>\r\n");
      out.write("                                            <input type=\"email\" class=\"form-control rounded-0\" name=\"name\"\r\n");
      out.write("                                                   id=\"exampleFormControlInput4\" aria-label=\"Jack Wayley\" required\r\n");
      out.write("                                                   data-error-class=\"u-has-error\" data-msg=\"Please enter your name.\"\r\n");
      out.write("                                                   data-success-class=\"u-has-success\">\r\n");
      out.write("                                        </div>\r\n");
      out.write("                                    </div>\r\n");
      out.write("                                </div>\r\n");
      out.write("                            </div>\r\n");
      out.write("                        </div>\r\n");
      out.write("                        <div class=\"pl-md-5 pl-lg-9 space-bottom-2 space-bottom-lg-3\">\r\n");
      out.write("                            <div class=\"font-weight-medium font-size-22 mb-4 pb-xl-1\">Password Change</div>\r\n");
      out.write("                            <div class=\"row\">\r\n");
      out.write("                                <div class=\"col-md-12 mb-4\">\r\n");
      out.write("                                    <div class=\"js-form-message\">\r\n");
      out.write("                                        <label for=\"exampleFormControlInput5\">Current Password</label>\r\n");
      out.write("                                        <input type=\"password\" class=\"form-control rounded-0\" name=\"name\"\r\n");
      out.write("                                               id=\"exampleFormControlInput5\" aria-label=\"Jack Wayley\" required\r\n");
      out.write("                                               data-error-class=\"u-has-error\" data-msg=\"Please enter your name.\"\r\n");
      out.write("                                               data-success-class=\"u-has-success\">\r\n");
      out.write("                                    </div>\r\n");
      out.write("                                </div>\r\n");
      out.write("                                <div class=\"col-md-12 mb-4\">\r\n");
      out.write("                                    <div class=\"js-form-message\">\r\n");
      out.write("                                        <label for=\"exampleFormControlInput6\">New Password</label>\r\n");
      out.write("                                        <input type=\"password\" class=\"form-control rounded-0\" name=\"name\"\r\n");
      out.write("                                               id=\"exampleFormControlInput6\" aria-label=\"Jack Wayley\" required\r\n");
      out.write("                                               data-error-class=\"u-has-error\" data-msg=\"Please enter your name.\"\r\n");
      out.write("                                               data-success-class=\"u-has-success\">\r\n");
      out.write("                                    </div>\r\n");
      out.write("                                </div>\r\n");
      out.write("                                <div class=\"col-md-12 mb-5\">\r\n");
      out.write("                                    <div class=\"js-form-message\">\r\n");
      out.write("                                        <label for=\"exampleFormControlInput7\">Confirm new password</label>\r\n");
      out.write("                                        <input type=\"password\" class=\"form-control rounded-0\" name=\"name\"\r\n");
      out.write("                                               id=\"exampleFormControlInput7\" aria-label=\"Jack Wayley\" required\r\n");
      out.write("                                               data-error-class=\"u-has-error\" data-msg=\"Please enter your name.\"\r\n");
      out.write("                                               data-success-class=\"u-has-success\">\r\n");
      out.write("                                    </div>\r\n");
      out.write("                                </div>\r\n");
      out.write("                                <div class=\"ml-3\">\r\n");
      out.write("                                    <button type=\"submit\"\r\n");
      out.write("                                            class=\"btn btn-wide btn-dark text-white rounded-0 transition-3d-hover height-60 width-390\">\r\n");
      out.write("                                        Save Changes\r\n");
      out.write("                                    </button>\r\n");
      out.write("                                </div>\r\n");
      out.write("                            </div>\r\n");
      out.write("                        </div>\r\n");
      out.write("                    </div>\r\n");
      out.write("                    <!----------------------account details--------------------------->\r\n");
      out.write("\r\n");
      out.write("\r\n");
      out.write("                    <!----------------------Wishlist--------------------------->\r\n");
      out.write("                    <div class=\"tab-pane fade\" id=\"pills-six-example1\" role=\"tabpanel\"\r\n");
      out.write("                         aria-labelledby=\"pills-six-example1-tab\">\r\n");
      out.write("                        <div class=\"pt-5 pl-md-5 pt-lg-8 pl-lg-9 space-bottom-lg-3\">\r\n");
      out.write("                            <h6 class=\"font-weight-medium font-size-7 ml-lg-1 mb-lg-8 pb-xl-1\">Wishlist</h6>\r\n");
      out.write("                            <table class=\"table mb-0\">\r\n");
      out.write("                                <thead>\r\n");
      out.write("                                <tr class=\"border\">\r\n");
      out.write("                                    <th scope=\"col\" class=\"py-3 border-bottom-0 font-weight-medium pl-3 pl-md-5\">\r\n");
      out.write("                                        Prouct\r\n");
      out.write("                                    </th>\r\n");
      out.write("                                    <th scope=\"col\" class=\"py-3 border-bottom-0 font-weight-medium\">Price</th>\r\n");
      out.write("                                    <th scope=\"col\" class=\"py-3 border-bottom-0 font-weight-medium\">Stock Staus</th>\r\n");
      out.write("                                    <th scope=\"col\" class=\"py-3 border-bottom-0 font-weight-medium\">Actions</th>\r\n");
      out.write("                                </tr>\r\n");
      out.write("                                </thead>\r\n");
      out.write("                                <tbody>\r\n");
      out.write("                                <tr class=\"border\">\r\n");
      out.write("                                    <th class=\"pl-3 pl-md-5 font-weight-normal align-middle py-6\">\r\n");
      out.write("                                        <div class=\"d-flex align-items-center\">\r\n");
      out.write("                                            <a class=\"d-block\" href=\"#\">\r\n");
      out.write("                                                <img class=\"img-fluid\" src=\"assets/img/90x138/img1.jpg\"\r\n");
      out.write("                                                     alt=\"Image-Description\">\r\n");
      out.write("                                            </a>\r\n");
      out.write("                                            <div class=\"ml-xl-4\">\r\n");
      out.write("                                                <div class=\"font-weight-normal\">\r\n");
      out.write("                                                    <a href=\"#\">The Overdue Life of Amy Byler</a>\r\n");
      out.write("                                                </div>\r\n");
      out.write("                                                <div class=\"font-size-2\"><a href=\"#\" class=\"text-gray-700\" tabindex=\"0\">Jay\r\n");
      out.write("                                                    Shetty</a></div>\r\n");
      out.write("                                            </div>\r\n");
      out.write("                                        </div>\r\n");
      out.write("                                    </th>\r\n");
      out.write("                                    <td class=\"align-middle py-5\">$37</td>\r\n");
      out.write("                                    <td class=\"align-middle py-5\">In Stock</td>\r\n");
      out.write("                                    <td class=\"align-middle py-5\">\r\n");
      out.write("                                        <span class=\"product__add-to-cart\">ADD TO CART</span>\r\n");
      out.write("                                    </td>\r\n");
      out.write("                                </tr>\r\n");
      out.write("                                <tr class=\"border\">\r\n");
      out.write("                                    <th class=\"pl-3 pl-md-5 font-weight-normal align-middle py-6\">\r\n");
      out.write("                                        <div class=\"d-flex align-items-center\">\r\n");
      out.write("                                            <a class=\"d-block\" href=\"#\">\r\n");
      out.write("                                                <img class=\"img-fluid\" src=\"assets/img/90x138/img3.jpg\"\r\n");
      out.write("                                                     alt=\"Image-Description\">\r\n");
      out.write("                                            </a>\r\n");
      out.write("                                            <div class=\"ml-xl-4\">\r\n");
      out.write("                                                <div class=\"font-weight-normal\">\r\n");
      out.write("                                                    <a href=\"#\">The Overdue Life of Amy Byler</a>\r\n");
      out.write("                                                </div>\r\n");
      out.write("                                                <div class=\"font-size-2\"><a href=\"#\" class=\"text-gray-700\" tabindex=\"0\">Jay\r\n");
      out.write("                                                    Shetty</a></div>\r\n");
      out.write("                                            </div>\r\n");
      out.write("                                        </div>\r\n");
      out.write("                                    </th>\r\n");
      out.write("                                    <td class=\"align-middle py-5\">$37</td>\r\n");
      out.write("                                    <td class=\"align-middle py-5\">In Stock</td>\r\n");
      out.write("                                    <td class=\"align-middle py-5\">\r\n");
      out.write("                                        <span class=\"product__add-to-cart\">ADD TO CART</span>\r\n");
      out.write("                                    </td>\r\n");
      out.write("                                </tr>\r\n");
      out.write("                                <tr class=\"border\">\r\n");
      out.write("                                    <th class=\"pl-5 font-weight-normal align-middle py-6\">\r\n");
      out.write("                                        <div class=\"d-flex align-items-center\">\r\n");
      out.write("                                            <a class=\"d-block\" href=\"#\">\r\n");
      out.write("                                                <img class=\"img-fluid\" src=\"assets/img/90x138/img4.jpg\"\r\n");
      out.write("                                                     alt=\"Image-Description\">\r\n");
      out.write("                                            </a>\r\n");
      out.write("                                            <div class=\"ml-xl-4\">\r\n");
      out.write("                                                <div class=\"font-weight-normal\">\r\n");
      out.write("                                                    <a href=\"#\">The Overdue Life of Amy Byler</a>\r\n");
      out.write("                                                </div>\r\n");
      out.write("                                                <div class=\"font-size-2\"><a href=\"#\" class=\"text-gray-700\" tabindex=\"0\">Jay\r\n");
      out.write("                                                    Shetty</a></div>\r\n");
      out.write("                                            </div>\r\n");
      out.write("                                        </div>\r\n");
      out.write("                                    </th>\r\n");
      out.write("                                    <td class=\"align-middle py-5\">$37</td>\r\n");
      out.write("                                    <td class=\"align-middle py-5\">In Stock</td>\r\n");
      out.write("                                    <td class=\"align-middle py-5\">\r\n");
      out.write("                                        <span class=\"product__add-to-cart\">ADD TO CART</span>\r\n");
      out.write("                                    </td>\r\n");
      out.write("                                </tr>\r\n");
      out.write("                                </tbody>\r\n");
      out.write("                            </table>\r\n");
      out.write("                        </div>\r\n");
      out.write("                    </div>\r\n");
      out.write("                    <!----------------------Wishlist--------------------------->\r\n");
      out.write("\r\n");
      out.write("                </div>\r\n");
      out.write("            </div>\r\n");
      out.write("        </div>\r\n");
      out.write("    </div>\r\n");
      out.write("</main>\r\n");
      out.write("\r\n");
      out.write("\r\n");
      out.write("<script src=\"assets/vendor/jquery/dist/jquery.min.js\"></script>\r\n");
      out.write("<script src=\"assets/vendor/jquery-migrate/dist/jquery-migrate.min.js\"></script>\r\n");
      out.write("<script src=\"assets/vendor/popper.js/dist/umd/popper.min.js\"></script>\r\n");
      out.write("<script src=\"assets/vendor/bootstrap/bootstrap.min.js\"></script>\r\n");
      out.write("<script src=\"assets/vendor/bootstrap-select/dist/js/bootstrap-select.min.js\"></script>\r\n");
      out.write("<script src=\"assets/vendor/slick-carousel/slick/slick.min.js\"></script>\r\n");
      out.write("<script src=\"assets/vendor/multilevel-sliding-mobile-menu/dist/jquery.zeynep.js\"></script>\r\n");
      out.write("<script src=\"assets/vendor/malihu-custom-scrollbar-plugin/jquery.mCustomScrollbar.concat.min.js\"></script>\r\n");
      out.write("\r\n");
      out.write("<script src=\"assets/js/hs.core.js\"></script>\r\n");
      out.write("<script src=\"assets/js/components/hs.unfold.js\"></script>\r\n");
      out.write("<script src=\"assets/js/components/hs.malihu-scrollbar.js\"></script>\r\n");
      out.write("<script src=\"assets/js/components/hs.header.js\"></script>\r\n");
      out.write("<script src=\"assets/js/components/hs.slick-carousel.js\"></script>\r\n");
      out.write("<script src=\"assets/js/components/hs.selectpicker.js\"></script>\r\n");
      out.write("<script src=\"assets/js/components/hs.show-animation.js\"></script>\r\n");
      out.write("\r\n");
      out.write("\r\n");
      out.write("<script>\r\n");
      out.write("    $(document).on('ready', function () {\r\n");
      out.write("        // initialization of unfold component\r\n");
      out.write("        $.HSCore.components.HSUnfold.init($('[data-unfold-target]'));\r\n");
      out.write("\r\n");
      out.write("        // initialization of slick carousel\r\n");
      out.write("        $.HSCore.components.HSSlickCarousel.init('.js-slick-carousel');\r\n");
      out.write("\r\n");
      out.write("        // initialization of header\r\n");
      out.write("        $.HSCore.components.HSHeader.init($('#header'));\r\n");
      out.write("\r\n");
      out.write("        // initialization of malihu scrollbar\r\n");
      out.write("        $.HSCore.components.HSMalihuScrollBar.init($('.js-scrollbar'));\r\n");
      out.write("\r\n");
      out.write("        // initialization of show animations\r\n");
      out.write("        $.HSCore.components.HSShowAnimation.init('.js-animation-link');\r\n");
      out.write("\r\n");
      out.write("        // init zeynepjs\r\n");
      out.write("        var zeynep = $('.zeynep').zeynep({\r\n");
      out.write("            onClosed: function () {\r\n");
      out.write("                // enable main wrapper element clicks on any its children element\r\n");
      out.write("                $(\"body main\").attr(\"style\", \"\");\r\n");
      out.write("\r\n");
      out.write("                console.log('the side menu is closed.');\r\n");
      out.write("            },\r\n");
      out.write("            onOpened: function () {\r\n");
      out.write("                // disable main wrapper element clicks on any its children element\r\n");
      out.write("                $(\"body main\").attr(\"style\", \"pointer-events: none;\");\r\n");
      out.write("\r\n");
      out.write("                console.log('the side menu is opened.');\r\n");
      out.write("            }\r\n");
      out.write("        });\r\n");
      out.write("\r\n");
      out.write("        // handle zeynep overlay click\r\n");
      out.write("        $(\".zeynep-overlay\").click(function () {\r\n");
      out.write("            zeynep.close();\r\n");
      out.write("        });\r\n");
      out.write("\r\n");
      out.write("        // open side menu if the button is clicked\r\n");
      out.write("        $(\".cat-menu\").click(function () {\r\n");
      out.write("            if ($(\"html\").hasClass(\"zeynep-opened\")) {\r\n");
      out.write("                zeynep.close();\r\n");
      out.write("            } else {\r\n");
      out.write("                zeynep.open();\r\n");
      out.write("            }\r\n");
      out.write("        });\r\n");
      out.write("    });\r\n");
      out.write("</script>\r\n");
      out.write("</body>\r\n");
      out.write("\r\n");
      out.write("</html>\r\n");
    } catch (java.lang.Throwable t) {
      if (!(t instanceof jakarta.servlet.jsp.SkipPageException)){
        out = _jspx_out;
        if (out != null && out.getBufferSize() != 0)
          try {
            if (response.isCommitted()) {
              out.flush();
            } else {
              out.clearBuffer();
            }
          } catch (java.io.IOException e) {}
        if (_jspx_page_context != null) _jspx_page_context.handlePageException(t);
        else throw new ServletException(t);
      }
    } finally {
      _jspxFactory.releasePageContext(_jspx_page_context);
    }
  }
}
